### ISSUE TITLE
[Linux] Game fails to start if timidity.cfg file does not exist in known location

### ISSUE THREAD

**Issue by Vaporeon** [nukeykt/NBlood#1]
throwing error "source/blood/src/sound.cpp(475):"
It would be nice for the game to continue without midi support since pre-recorded audio is superior anyway.

**Comment by mirrornoir** [comment]
I ran into this error as well. It's easily fixed with a symbolic link from an existing `timidity.cfg` to one of the locations the game expects. For what it's worth, if the list of locations were expanded `/etc/timidity++/timidity.conf` is another common location.

**Comment by alexey-lysiuk** [comment]
I believe this can be closed. NBlood now starts without `timidity.cfg` loaded. As for its search paths, they were derived from EDuke32 without a change.
