### ISSUE TITLE
Bloated Butchers sometimes catch on fire indefinitely

### ISSUE THREAD

**Issue by h3xx** [nukeykt/NBlood#111]
Sometimes when using the flair gun on Bloated Butchers, they will catch on fire and run around like normal (even setting other things on fire), but will fail to die and collapse.

In my playthrough, it happened once in episode 2, and then again in episode 5, so it's a very rare occurrence. Both times it was a Butcher, and it hasn't happened with any other mob.

If you load a save with them in, they won't continue to move (but that's probably an unrelated bug). Regardless, they were moving at the time of the save.

Notes:
- Another flair shot will cause them to move and collapse afterward
- Explosion damage will cause them to die, and the burning corpse will fly up in the air as normal
- Seen in the One Whole Unit CD pack

Save file:
- https://github.com/h3xx/NBlood/blob/gh-111-issue-data/game0000.sav (E5M1)
- Made with current head of master (879560ff9c660251af7a4fdb5550f971af2aab46)

**Comment by CommonLoon102** [comment]
What do you mean by

> Seen in the One Whole Unit CD pack

Do you mean that you have seen this in the original version too?
If this is happening in vanilla too (DOS v1.21) then I think this won't be fixed.
I had a pull request yesterday regarding flaming bugs, and it was not merged either:
https://github.com/nukeykt/NBlood/pull/110

> Sorry, but i'm against of significant gameplay changes at this point

**Comment by CommonLoon102** [comment]
I get assertion failed when I try to load your save :(

> seq.cpp line 96
> pSprite->extra == nXSprite

**Comment by h3xx** [comment]
I mean using NBlood with the data files from One Whole Unit.

**Comment by CommonLoon102** [comment]
I couldn't reproduce it but I remember I've seen this before in the DOS version too and not just with butchers. It is very rare though.

**Comment by h3xx** [comment]
Oh. Well if you want to keep the bugs intact from the DOS version, you can close this.

**Comment by CommonLoon102** [comment]
No, you can close this :)
I can't, and @nukeykt doesn't maintain the issues.

**Comment by CommonLoon102** [comment]
https://blood-wiki.org/index.php/Flame_guy

"The "Flame Guy" bug happens when the enemy continues to run around infinitely. Usually this happens when the enemy runs into a wall and becomes clipped (trapped between separate areas)."

**Comment by h3xx** [comment]
Although it would be nice to patch the bugs in the original engine (because why not?) I'm unsure if this is one of the design goals of nBlood.

**Comment by CommonLoon102** [comment]
Yeah I think too that this should be patched, but if @nukeykt is against it then there is no point of fixing this because it won't get merged.
