### ISSUE TITLE
2D mode doesn't update

### ISSUE THREAD

**Issue by CommonLoon102** [nukeykt/NBlood#117]
This is a bug in the original too.

If you press the tab (by default) to switch to the 2D map mode and play like this, the map should automatically update when you explore new areas. This is not happening it stays black. Currently, you have to switch back to 3D mode and then back to 2D to see the updated map.
In Duke Nukem 3D with EDuke this problem doesn't occur.

**Comment by nukeykt** [comment]
It's because blood relies on renderer's "automapping" feature unlike other build games. You'll need to run renderer on background to workaround this, which is not quite a good idea imo
