### ISSUE TITLE
Purple fills the area at certain angles

### ISSUE THREAD

**Issue by Jan200101** [nukeykt/NBlood#119]
![image](https://user-images.githubusercontent.com/15076013/63211882-a4768380-c0fd-11e9-8537-76b8df8dac9b.png)
The easiest way to replicate it is by jumping on the tombstones in e1m1

Sorry for the vague title

**Comment by CommonLoon102** [comment]
It only flickers some purple for me, I couldn't get a full static purple void.
But the mapedit branch seems fine for me, no purple stuff at all. Can you please try with the latest mapedit branch?

**Comment by Jan200101** [comment]
the mapedit branch seems to reuse parts of the viewport during the moment the purple void appears on master

**Comment by CommonLoon102** [comment]
> 
> 
> the mapedit branch seems to reuse parts of the viewport during the moment the purple void appears on master

I don't think I understand 100% what you mean, but I can feel a little bump in master branch when the purple things appear for a few millisecs. In mapedit branch I feel the same but no purple stuff. In DOS I feel the same bump.

**Comment by nukeykt** [comment]
It's fixed in mapedit branch

**Comment by Jan200101** [comment]
on the mapedit branch the issue of the pink / purple void is fixed
yet there are still some issues that look like rendering artifacts when doing the same actions as you had to do to trigger the void
this is only a minor issue though and unless you jump around like maniac, like I do, you will not face this issue

closing because the original issue has been fixed

**Comment by CommonLoon102** [comment]
I know what you talking about, but when I tested it in DOS those "artifacts" were still there. I think it has something to do with the fence and height difference, when it switches between two floors, I can sense a little bump.

**Comment by CommonLoon102** [comment]
How difficult it would be to cherry pick and merge only those changes which fix this issue from mapedit to master?

**Comment by CommonLoon102** [comment]
@nukeykt: How difficult it would be to cherry pick and merge only those changes which fix this issue from mapedit to master?

**Comment by nukeykt** [comment]
I dunno. I believe this was fixed when i backported polymost changes from eduke32
