### ISSUE TITLE
No ini selector on Linux

### ISSUE THREAD

**Issue by CommonLoon102** [nukeykt/NBlood#126]
On Linux (screenshot from Lubuntu 18 32 bit latest) there is no ini file selector in the startup window. How can I start Cryptic Passage then? I saw somebody mentioned using `./nblood -i cryptic.ini` but it says `invalid argument: -i`.

[Imgur](https://imgur.com/8ZNUTOw)

[Imgur](https://imgur.com/aOXHzzx)

**Comment by Jan200101** [comment]
according to the help message invoked with `-help` the correct parameter would be `-ini`

**Comment by CommonLoon102** [comment]
Thanks, it works with `-ini`

**Comment by CommonLoon102** [comment]
I guess who can use Linux and compile the game from sources those can start it with a parameter too.
