### ISSUE TITLE
Several issues during compilation for a port

### ISSUE THREAD

**Issue by Rinnegatamante** [nukeykt/NBlood#13]
Hi, i'm trying to compile NBlood based on my EDuke32 port for PSVITA. I've edited accordingly the same files as i did on EDuke32 however during compilation i'm getting several issues that seems to come from an erroneously way to include header files. I fixed a bunch of them by adding Vita only "patches" however now i'm stuck to this.

![immagine](https://user-images.githubusercontent.com/9152710/52902558-b17bee00-3212-11e9-81aa-f8b0ff49f35a.png)

**Comment by nukeykt** [comment]
Does commit 1d15db7ca84dc124da7216a868baa23ceb287465 make any improvement?

**Comment by Rinnegatamante** [comment]
I think it should improve the situation, i did something similar on my own and managed to build it (i had to replace also a lot of int with int32_t and do a lot of explicit casts due to newlib bugs, however that's the commit: https://github.com/Rinnegatamante/NBlood-Vita/commit/85f466da452156b68e9b11f5194e91779be809c8 ).
Now i'm getting crashes seemingly inside kz4lib (i tried to log that func and last call is about |blood.def).
