### ISSUE TITLE
Game freeze after using "Lara Croft" cheat twice and then pressing "Next Weapon"

### ISSUE THREAD

**Issue by dibollinger** [nukeykt/NBlood#14]
(Turns out that this bug also exists in the original Blood executable)

The "Lara Croft" cheat gives the player all weapons and infinite ammo. 
Typing it in a second time attempts to deactivate it, and as such takes away all of the player's weapons, including the default pitchfork.
Using either the "Next Weapon" or "Previous Weapon" key in this state causes the game to freeze, as there are no weapons to pick from. (possible infinite loop?)

**Comment by CommonLoon102** [comment]
Yes, it gets into an infinite loop. Normally, when you out of ammo from every weapon it will switch to the pitchfork, but the second "Lara Croft" took away that too, so it gets into an infinite loop.
