### ISSUE TITLE
E2M4 Reflection glitch

### ISSUE THREAD

**Issue by shockinglycavalier** [nukeykt/NBlood#143]
![blud0002](https://user-images.githubusercontent.com/50780884/63640413-671e7280-c676-11e9-905c-abb6d3e17f53.png)

Visual glitch with mirror on wall using Polymost renderer in dev build posted on duke4 forums (NBlood v1.0-223-gb1f6a1b Built May 19 2019 01:13:03, GCC 7.3.0, 64-bit). 

Issue is not reproducible using classic renderer nor in version 1.01.

**Comment by CommonLoon102** [comment]
So why you open this issue if this is already fixed?

**Comment by shockinglycavalier** [comment]
Sorry, maybe I wasn't clear. The issue is not reproducible in version 1.01 which was April 2019. This dev build is from May so, unless I'm mistaken, the bug was introduced some time _after_ 1.01.

**Comment by CommonLoon102** [comment]
Thanks.
The issue is still present in latest master (polymost only) but in mapedit branch the mirror works as it should (both in polymost and classic).

**Comment by CommonLoon102** [comment]
Fixed in master.
