### ISSUE TITLE
Gargoyles which were statues won't leave a corpse

### ISSUE THREAD

**Issue by CommonLoon102** [nukeykt/NBlood#144]
The good news is that it is the same in the original.

If you kill them with the pitchfork, after they die, they won't have a corpse, they just disappear. Only the small brown ones have this issue, the large gray one is OK, it will have a corpse.

**Comment by NoOneBlood** [comment]
It happens on any enemy that have trigger flags checked (such as vector, proximity and so on). You can clearly see it in E6M1 with axe zombies.
