### ISSUE TITLE
Life seed with voxel pack not rotating

### ISSUE THREAD

**Issue by CommonLoon102** [nukeykt/NBlood#169]
It is rotating in BloodGDX 1.04.
It is an issue because sometimes it is not facing to the player, for example the reward life seed on Dark Carnival is not facing me when it ascends.

I'm opening this issue because it might be an easy fix to enable rotation for custom voxels.
The tommy gun should rotate too but it isn't either.

**Comment by nukeykt** [comment]
Fixed in 1d7f26ea2b85ed0c9c7a1dcfc984c1cdb005ab96

**Comment by CommonLoon102** [comment]
They are still not rotating for me, any idea why?

**Comment by nukeykt** [comment]
Use bloodgdx.def

**Comment by CommonLoon102** [comment]
Thanks, the rotate parameters were missing from blood.def.
