### ISSUE TITLE
a small error that I got when reloading a savegame

### ISSUE THREAD

**Issue by BielBdeLuna** [nukeykt/NBlood#188]
after reloading a savegame, it's not a common issue

> Assertion failed: nLevel >= 0 && nLevel < pEpisodeInfo->nLevels in file source/blood/src/levels.cpp at line 158

**Comment by CommonLoon102** [comment]
What version do you use? Saving and loading does not work between different builds.

**Comment by BielBdeLuna** [comment]
it was a savegame I just made, and used by several times, but then it failed

> NBlood v1.01-614-g76cbfd0
> Built Sep 20 2019 12:44:09, GCC 8.3.0, 64-bit 
> Using /home/biel/games/blood/ for game data
> Using /home/biel/.config/nblood/ for game data
> Initializing SDL 2.0.9
> Using "x11" video driver
> Using "nblood.pk3" as main game data file.
> Using file "bloodupscale.pk3" as game data.
> Initializing OSD...
> Executing "settings.cfg"
> Setting video mode 320x200 (0-bpp windowed)
> Refresh rate: 60Hz
> polymost_glreset()
> OpenGL information
>  Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Mobile  3.0 Mesa 19.0.8
> Initializing Build 3D engine
> Initializing engine
> Loading palettes
> Loading translucency table
> Loading gamma correction table
> Creating standard color lookups
> Loading tiles
> Initialized 96,0M cache
> Loading "blood_widescreen.def"
> .Loading module "bloodupscale.def"
> .....................................................
> Loading "blood.def"
> ..Loading module "bloodupscale.def"
> .....................................................
> Definitions file "blood.def" loaded in 304 ms.
> Loading cosine table
> Initializing view subsystem
> Initializing status bar
> Initializing dynamic fire
> Initializing weapon animations
> There are 4 demo(s) in the loop
> Loading control setup
> No game controllers found
> Initializing network users
> Setting video mode 1366x768 (32-bpp fullscreen)
> Refresh rate: 60Hz
> polymost_glreset()
> polymost_glreset()
> Opened "texturecache" as cache file
> Initializing sound system
> Waiting for network players!
> 
> fluidsynth: warning: Failed to pin the sample data to RAM; swapping is possible.
> fluidsynth: warning: Instrument not found on channel 0 [bank=56 prog=48], substituted [bank=0 prog=48]
> fluidsynth: warning: Instrument not found on channel 1 [bank=56 prog=47], substituted [bank=0 prog=47]
> fluidsynth: warning: Instrument not found on channel 2 [bank=56 prog=89], substituted [bank=0 prog=89]
> fluidsynth: warning: Instrument not found on channel 3 [bank=56 prog=116], substituted [bank=0 prog=116]
> fluidsynth: warning: Instrument not found on channel 4 [bank=56 prog=89], substituted [bank=0 prog=89]
> fluidsynth: warning: Instrument not found on channel 6 [bank=56 prog=49], substituted [bank=0 prog=49]
> fluidsynth: warning: Instrument not found on channel 7 [bank=56 prog=116], substituted [bank=0 prog=116]
> fluidsynth: warning: Instrument not found on channel 8 [bank=56 prog=54], substituted [bank=0 prog=54]
> Load tile 2955: p12-m5-e0 upscale/tile2955tr.png... 26 ms
> Load tile 3040: p12-m5-e0 upscale/tile3040tr.png... 24 ms
> Assertion failed: nLevel >= 0 && nLevel < pEpisodeInfo->nLevels in file source/blood/src/levels.cpp at line 158

**Comment by BielBdeLuna** [comment]
correction it happened to me not after a load game but after loading a game and pressing the map( tabulation key ) i could reproduce this twice on a row but i cannot reproduce it any more, i haven't changed anything

**Comment by CommonLoon102** [comment]
Do you remember which map was it?

I couldn't reproduce this, I did the following:
1. Start new game on E1M1
2. Quick save
3. Press Tab
4. Constantly pressing F9 (quick load)

**Comment by BielBdeLuna** [comment]
It was e6m8 or whatever is the last one of the last episode, the one with the werebeasts

**Comment by CommonLoon102** [comment]
Can't reproduce on it either.
