### ISSUE TITLE
Try to resolve a sanitizer error in view.cpp

### ISSUE THREAD

**Issue by NY00123** [nukeykt/NBlood#19]
This at least resolves a specific sanitizer error I had, albeit with possibly differing behaviors:

`-    if (nLowerLink >= 0 && (sprite[nLowerLink].type == 10 || sprite[nUpperLink].type == 14))`
`+    if (nLowerLink >= 0 && (sprite[nLowerLink].type == 10 || sprite[nLowerLink].type == 14))`

**Comment by nukeykt** [comment]
This appears to be copy-paste error. In disassembly `nLowerLink` is used here. Thanks!
