### ISSUE TITLE
Kill Counter Bug

### ISSUE THREAD

**Issue by randomcodegen** [nukeykt/NBlood#2]
Spawned Civilians add to max kill counter but don't count as kills. They should not add to the max kills.

e.g. E1M3 open the door to exit the super secret area. It spawns 4 cultists + 2 civilians increasing the kill counter by 6 but only 4 kills have an effect on the kill counter.

-edit-

Just checked in dosbox and this turns out to be a vanilla bug. Not sure if it should get a fix.
This does however stop the player from 100%ing some levels so maybe it should get an optional fix.

**Comment by randomcodegen** [comment]
Another level where 100% kills are impossible is e1m4 except it's not spawn-related. On every difficulty 2 kills will be missing and I believe they are the two bleeding gargoyle statues at the normal level-end button.

**Comment by CommonLoon102** [comment]
Is it possible that this is a bug in the map itself? There are similar bugs in case of secret areas on some maps where you can find more than the maximum or you cannot find all the secrets.

**Comment by CommonLoon102** [comment]
Not a bug.
