### ISSUE TITLE
Flickering sprites in Caleb's Dream 

### ISSUE THREAD

**Issue by VGkav** [nukeykt/NBlood#205]
http://www.blood.freeminded.de/index.php?section=maps&id=370

Just load the map and after the delirium effect ends, go to the window flapping in the wind, while moving there is a glitch on the table. It's fine on the current stable BloodGDX

**Comment by AnotherLife** [comment]
It is fine on 1,21 on Dosbox

**Comment by CommonLoon102** [comment]
Yes, it is flickering in polymost. In classic renderer it is not flickering but you can see it through other textures (like in DOS).
