### ISSUE TITLE
Unable to compile without OpenGL

### ISSUE THREAD

**Issue by Jan200101** [nukeykt/NBlood#221]
voxoff and voxreserve (among others probably but I did not do enough testing) are defined only with USE_OPENGL but used without it

both are defined in source/build/include/build.h

eduke32 moved voxoff to engine.cpp long ago so its not a upstream issue

**Comment by CommonLoon102** [comment]
I know, I had this fixed in my wasm branch, just move them out of the USE_OPENGL ifdef.
See: https://github.com/CommonLoon102/NBlood/commit/6c1d6bdd641f5a5cbfadeee88082957b6201743d

**Comment by Jan200101** [comment]
#228 should have fixed this
I'm going to reopen it if its still borked
