### ISSUE TITLE
Sprite and voxel flickering

### ISSUE THREAD

**Issue by CommonLoon102** [nukeykt/NBlood#232]
Sprites and voxels tend to flicker in master: https://cdn.discordapp.com/attachments/544944689028136970/637372476443066368/flicker.avi

It wasn't like this before. I haven't pinpointed the commit which is causing this yet.
Only OpenGL is affected.

The map on the video is E5M1.

**Comment by Hendricks266** [comment]
Does this still happen? I recall an issue like this affecting Ion Fury but it got fixed.

**Comment by CommonLoon102** [comment]
Yes, it still happens.

**Comment by CommonLoon102** [comment]
The same commit is causing this as for this other issue: https://github.com/nukeykt/NBlood/issues/295

**Comment by CommonLoon102** [comment]
Commenting out this line "fixes" the issue: https://github.com/nukeykt/NBlood/blob/658c992487edd85e8ed3236fe8284f386ce17000/source/build/src/engine.cpp#L9105

**Comment by nukeykt** [comment]
Fixed in 888bda5c1a227d645dc66e037a5c57ba9ab06220
