### ISSUE TITLE
in Ubuntu 19.10 i get a segmentation fault without any other message just at the start

### ISSUE THREAD

**Issue by BielBdeLuna** [nukeykt/NBlood#238]
...compiling with RELEASE=0 to see if i can pinpoint where this fails

**Comment by BielBdeLuna** [comment]
with RELEASE=0 I don't get any further messages besides the segmentation fault, compiling with DEBUGANYWAY=1

**Comment by BielBdeLuna** [comment]
nope, I get the same segmentation fault without any other message, maybe RELEASE=0 and DEBUGANYWAY=1 only act when building the engine?

**Comment by Jan200101** [comment]
having this same issue on Fedora 30 x86_64 with RELEASE=0 it compiles and runs just fine
checking with gdb I found this on the stack
```
Assertion failed: pItem != NULL in file source/blood/src/gamemenu.cpp at line 2596\n
```

**Comment by BielBdeLuna** [comment]
ah yes, I'm also on x86_64.

**Comment by CommonLoon102** [comment]
Same issue on Ubuntu 18, we can say the Linux port is broken.

**Comment by BielBdeLuna** [comment]
it wasn't broken before on Ubuntu 19.4 as I could play it then, so something broke it in either in the change of version of Ubuntu or in the recent commits to the engine.

**Comment by CommonLoon102** [comment]
The fix is already done, it will be merged very soon.

**Comment by CommonLoon102** [comment]
It should be fine now.

**Comment by BielBdeLuna** [comment]
fine! now IT lives agaaaiin!
