### ISSUE TITLE
Command line parameter -j not working

### ISSUE THREAD

**Issue by ectorhga** [nukeykt/NBlood#239]
Hi,

I just tried to load nblood on a Raspberry Pi 3b+ with the option to set the game directory (-j) but it doesn't work.  I'm running Raspbian Stretch (for retropie) and compiled with the option USE_OPENGL=0.

As soon as I enter a leading "/" to the path, I get the error "missing argument". I tried different approaches, but none worked. As soon as I leave out the "/", the game starts, but the path is (of course) not valid: i.e. "home/pi/..." instead of "/home/pi/..."

I created an Github account mainly to follow the development of nblood, and I have very little programming experience, so I hope I did everything right with this issue report.

Thanks a lot for your work on this Blood-port! So far it runs quite nicely on the rpi3b+ except for the message: "videoSetGamma(): That operation is not supported" which is probably related to not using openGL?

**Comment by Jan200101** [comment]
after some testing I found if you use it like this it works just fine
`nblood -j=DIR`

**Comment by ectorhga** [comment]
Nice! I will try that tonight!

**Comment by CommonLoon102** [comment]
It shouldn't work like this though or this should be mentioned in the help.

**Comment by Jan200101** [comment]
For some reasons if whatever you give `-j` starts with a slash it will ignore it
It's quite weird

**Comment by actraiser30** [comment]
hello are there any instructions to build on a raspberry pi ?

thanks
