### ISSUE TITLE
Unable to compile on ppc64le

### ISSUE THREAD

**Issue by Jan200101** [nukeykt/NBlood#241]
[builder-live.log.gz](https://copr-be.cloud.fedoraproject.org/results/sentry/NBlood/fedora-rawhide-ppc64le/01084398-nblood-unstable/builder-live.log.gz)

a (now removed) change to eduke included emmintrin.h in zpl.h was included in commit ffd9705616dd51c77468cdef24c790d7eeec4b96
this results in any ppc64le build to fail with the error message `Please read comment above.  Use -DNO_WARN_X86_INTRINSICS to disable this error.`
This issue will be closed once upstream is merged

**Comment by CommonLoon102** [comment]
The introduction of ZPL also broke BSD builds, but with latest eduke32 it will be fine again.

**Comment by CommonLoon102** [comment]
I think it should be OK now, ZPL has been gutted and merged to NBlood.
