### ISSUE TITLE
source/blood/src/blood.cpp(1467): Missing argument ehhh what?

### ISSUE THREAD

**Issue by BielBdeLuna** [nukeykt/NBlood#243]
I have the upscale mod inside a mod folder in that way:

the game is in:
~/game/blood/ 

and the mod in:
~/game/blood/mods/bloodupscale.pk3

I have the following script file with the filename "play blood upscale.sh" with the following content:
```
#!/bin/sh

BASEFOLDER=$PWD

./nblood -g $BASEFOLDER/mods/bloodupscale.pk3 -mh bloodupscale.def
```

I entered the following command:

> $ ./play\ blood\ upscale.sh 

but it fails with a "accept" window displaying the following message:

> source/blood/src/blood.cpp(1467): Missing argument

after accepting it the engine closes

three things: 

1. maybe a "-g file" should add the folder where this file is as if a -j argument is passed?

2. maybe there should be a "missing file" or a "file not found" message instead of a c++ error message?

3. what is the best practice for mods?

**Comment by nukeykt** [comment]
Try using `=` as separator, i.e `./nblood -g=$BASEFOLDER/mods/bloodupscale.pk3 -mh bloodupscale.def`

**Comment by BielBdeLuna** [comment]
yeah, now it works, but what should be the best practice to have the mods files not mixed with the base game files?

could the game files be in a "base" folder and have the mods in their own folder? like in the idTech engine?
