### ISSUE TITLE
Add Rednukem to README.md

### ISSUE THREAD

**Issue by axredneck** [nukeykt/NBlood#250]
As far as i understand it's possible to play Redneck Rampage with NBlood, but readme.md describes only Blood.

**Comment by CommonLoon102** [comment]
It is not possible.

**Comment by Hendricks266** [comment]
The code has been merged into the same repository but Rednukem is a separate executable.

The README.md should probably clarify this, you're right.

**Comment by CommonLoon102** [comment]
Maybe include Shadow Warrior too then.

**Comment by Hendricks266** [comment]
> Maybe include Shadow Warrior too then.

No, VoidSW is part of the mainline EDuke32 repository.
