### ISSUE TITLE
No redneck fun on startup

### ISSUE THREAD

**Issue by BielBdeLuna** [nukeykt/NBlood#252]
source/blood/src/screen.cpp(202): BLOOD.PAL not found (RFF files may be wrong version)

**Comment by Hendricks266** [comment]
Redneck Rampage cannot be played with NBlood.exe. The code repositories have been merged, nothing more. #250

**Comment by BielBdeLuna** [comment]
so why close it?

**Comment by Hendricks266** [comment]
It's not a bug, and as far as documentation goes it's a duplicate of #250.

Try `make rednukem`.

**Comment by BielBdeLuna** [comment]
ok
