### ISSUE TITLE
Considering renaming the project to something more generic (e.g. NBuild).

### ISSUE THREAD

**Issue by neuromancer** [nukeykt/NBlood#259]
Since this repository allows to to play different Build games, I wonder if you can consider changing the name to something more generic.

**Comment by Hendricks266** [comment]
NBlood, Rednukem, and PCExhumed fall under the umbrella of the EDuke32 project, and the codebases are kept closely in sync in both directions. At present, reverse engineered codes live in this repository, and officially released ones live upstream. That is the primary distinction. All of the ports ultimately use EDuke32's engine, therefore it would not be appropriate to give this repository a signifier of its own based on the engine. On our Discord server I've chosen the term _NBlood Group_ to refer to the ports that live here.

**Comment by neuromancer** [comment]
Fair enough.
