### ISSUE TITLE
Rednukem: Interplay MVE support

### ISSUE THREAD

**Issue by BSzili** [nukeykt/NBlood#266]
Redneck Rampage Rides Again's REDINT.MVE intro is in this format, and it would be nice if RedNukem could play it back. FFmpeg has a working decoder for it, which could be useful as a reference.

**Comment by sirlemonhead** [comment]
Will have this implemented soon hopefully!

**Comment by sirlemonhead** [comment]
Running into some syncing issues! Audio is playing 2 seconds or so before the video. Hopefully have this fixed soon.
