### ISSUE TITLE
Blood: Monolith and GTI intro logos

### ISSUE THREAD

**Issue by CommonLoon102** [nukeykt/NBlood#268]
I think we should add back to play Monotlith and GTI SMK files when starting Blood because a lot of people remember incorrectly and they expect them to play. In Blood version 1.21 they were disabled: https://blood-wiki.org/index.php?title=Bugs_in_Blood#Version_1.21_.28One_Unit:_Whole_Blood.29 (see first bug).

Because of this, people think that SMK playback doesn't work and that they couldn't set up correctly the `movie` folder. Users could see it is working by starting a new game on episode 1 but they usually don't do that they just expect the logos at the start.

We could add a -nointro parameter if there isn't one already.

edit: -quick is exactly for this already, so I didn't add -nointro

**Comment by sirlemonhead** [comment]
Yes, I think this should be done. I'm one of the many who expect to see them (I don't think I ever updated/patched beyond the plasma back 'back in the day' - whatever version that was.

There is already a parameter, -quick, which should be used for this.
