### ISSUE TITLE
Package NBlood as a Flatpak

### ISSUE THREAD

**Issue by poperigby** [nukeykt/NBlood#272]
Getting NBlood as easy to install as possible would be beneficial.

**Comment by CommonLoon102** [comment]
Why no snap or AppImage?

**Comment by PopeRigby** [comment]
Those are also good ideas.

**Comment by Jan200101** [comment]
in my opinion AppImages are the easiest and simplest solution for Linux packaging and existing solutions like AppImageUpdate allows those who have it to have update

**Comment by PopeRigby** [comment]
Is there any reason not to just have both?

**Comment by Jan200101** [comment]
there is no problem with having both and I'll even gladly work on getting it ready to work on flatpak
though some questions come to mind like what filesystem access should it have

by default everything is sandboxed but things like automatic game asset location would not work correctly so should everything be accessable?

**Comment by PopeRigby** [comment]
I think you can limit file system access to certain folders. Not entirely sure though.

**Comment by Jan200101** [comment]
yeah its possible to limit it to certain folders but you can install gog games and steam games anywhere really so setting a hard path for those could be problematic when it finds the game somewhere else

**Comment by CamJRP** [comment]
Permission problems can be solved with flatseal. 
I too would appreciate a flatpak. Eduke32 has one that you can directly download by the software center GUI in Linux Mint and many other distros.
Flatpak keep the base system clean and safe, are automatically updated, and are much lighter and faster than snaps. INMHO.
