### ISSUE TITLE
Main menu music continues to play after a save game is loaded

### ISSUE THREAD

**Issue by PopeRigby** [nukeykt/NBlood#277]
[Here's](https://imgur.com/PdbTen5) and example of it happening. As you can see, going into the sound settings and clicking `APPLY CHANGES` stops the main menu music, and the level's music is able to play.

**Comment by CommonLoon102** [comment]
Which map is on the video?

**Comment by CommonLoon102** [comment]
OK, I found it and I was able to reproduce it. On your video it is the end of E3M2. That map doesn't have a music. Just like E1M5 doesn't have music either. Music is not defined in blood.ini for these maps.
I'll look into the issue.

**Comment by CommonLoon102** [comment]
The fixed version of the game is available here, you can close the issue if it is solved: https://lerppu.net/wannabethesis/nblood/20200113-2073/

**Comment by PopeRigby** [comment]
Are there only Windows binaries in that repository? I'm on Linux.

**Comment by CommonLoon102** [comment]
If you are on Linux, why don't you compile it yourself?

**Comment by PopeRigby** [comment]
I don't see the source code in there.

**Comment by CommonLoon102** [comment]
Linux binaries were never distributed, I don't know how you are playing it on Linux then, if you didn't compile it from source. The fix was already merged into master yesterday, you can close the issue.

**Comment by PopeRigby** [comment]
> Linux binaries were never distributed, I don't know how you are playing it on Linux then, if you didn't compile it from source.
I was using the [AUR](https://aur.archlinux.org/).
> The fix was already merged into master yesterday, you can close the issue.
Thank you.
