### ISSUE TITLE
Remove collision from gibs

### ISSUE THREAD

**Issue by PopeRigby** [nukeykt/NBlood#279]
Walking over gibs and having your character move around from the collision can be quite annoying.

**Comment by Hendricks266** [comment]
@NoOneBlood Is this a regression?

**Comment by CommonLoon102** [comment]
You walk on top gibs in DOS too.

**Comment by PopeRigby** [comment]
I never noticed it in the DOS version. I don't think it would affect the gameplay if it was removed in NBlood.

**Comment by CommonLoon102** [comment]
That would make demos desync, which is against the NBlood development philosophies. But hey, you can still fork it!

**Comment by Hendricks266** [comment]
I would highly discourage a gameplay behavior fork. This would be best suited for a mod, when/if suitable modding capabilities are added.

**Comment by CommonLoon102** [comment]
I suggested to fork since there are no modding capabilities. There is no other option.

**Comment by Hendricks266** [comment]
If you maintain your own branch with the change in your own local git repository that you rebase over master when you update, I don't see any problem with that.

**Comment by CommonLoon102** [comment]
Yes of course, I meant that.
