### ISSUE TITLE
Quick save menu key "stuck" after playing one level

### ISSUE THREAD

**Issue by neuromancer** [nukeykt/NBlood#28]
After playing one level (episode 2), saving occasionally using F6 key, it gets "stuck": every time you press it, the menu will open and close very quickly (almost like a flash).

**Comment by CommonLoon102** [comment]
For me it seems it works as it should. Only the first time you have to select a quick save slot then what you see is the screen what it shows wile saving, which takes less than 100ms so you only see a flash.

**Comment by CommonLoon102** [comment]
Not a bug, should be closed.
