### ISSUE TITLE
Vulkan renderer

### ISSUE THREAD

**Issue by PopeRigby** [nukeykt/NBlood#280]
This would probably be a good idea to improve performance quite a bit.

**Comment by Hendricks266** [comment]
Please don't make pie in the sky feature requests like this. Our performance drawbacks are not the ones solved by an OpenGL to Vulkan transition. It would be helpful, yes, and a totally new renderer should target Vulkan, but it's not worth tracking as an issue.

**Comment by PopeRigby** [comment]
Why is it not worth tracking in an issue?

**Comment by CommonLoon102** [comment]
Because nobody will work on it.

**Comment by Hendricks266** [comment]
It's trivial to open a GitHub issue and type in a few words, but a Vulkan renderer would take man-months. As I have already stated, a Vulkan renderer is not on the critical path for improving our performance. Issue tracking is an aid to a project's development. It is not for drive-by spitballing.

**Comment by PopeRigby** [comment]
Alright my bad. I thought using it to track a goal was within that scope.
