### ISSUE TITLE
Completing switch puzzle in E3M5 doesn't open door

### ISSUE THREAD

**Issue by PopeRigby** [nukeykt/NBlood#281]
[Here's what happens for me](https://imgur.com/lNMQc3u)
[This is what's supposed to happen](https://youtu.be/TT6dVE2q5CQ?t=294)

According to [this](https://blood-wiki.org/index.php?title=E3M5:_Spare_Parts#Walkthrough) guide, I did the puzzle right, it's just not opening.

**Comment by CommonLoon102** [comment]
You need to wait until it opens.

**Comment by PopeRigby** [comment]
For how long? I've waited for a couple minutes and it doesn't open.

**Comment by sirlemonhead** [comment]
I can't replicate this with the latest build. Which version are you using and can you provide a savegame file?

**Comment by CommonLoon102** [comment]
He must be using an older version where the combination switch bug hasn't fixed yet. Issue can be closed.

**Comment by PopeRigby** [comment]
I'm on the master branch, so I don't think that's the case. I'll upload my save.

**Comment by CommonLoon102** [comment]
It opens after the red bars go down and the mechanic sounds stop. Then the little door in the wall for the skull key opens at the opposite side of the levers, at the same time the window opens in the wall where you tried to jump on your video. You need to wait about 13 seconds, but on your video you didn't wait that much. Despite that, it might still not work for you if you don't compile from latest sources.

**Comment by Hendricks266** [comment]
Please recompile from the latest source in git master, using `make clean` first if you have built previously.

**Comment by CommonLoon102** [comment]
And don't forget git pull. :)

**Comment by PopeRigby** [comment]
Alright, it's still broken on HEAD.

**Comment by CommonLoon102** [comment]
Instead of loading the save, start the map with `mario 3 5` and try that way.

**Comment by PopeRigby** [comment]
It says mario isn't a valid command

**Comment by CommonLoon102** [comment]
You need to enter it as a cheat via the send chat message feature, like every other cheat.

**Comment by PopeRigby** [comment]
Ok, so it works if I warp to the level. It might have something to do with me messing up the puzzle the first time.

**Comment by CommonLoon102** [comment]
No, it has something to do with the save. When you save, you save the whole map state, and it got screwed up already when you saved it with the bugged version.

**Comment by PopeRigby** [comment]
So what do I do? Is the save unrecoverable?

**Comment by Hendricks266** [comment]
If you use the noclip cheat to bypass the puzzle, I think everything should work fine again when you reach the following map.

**Comment by CommonLoon102** [comment]
Or if you don't want to cheat, do a pitchfork start. I'm sorry for your loss (ammo, armor and weapons).

**Comment by PopeRigby** [comment]
That's probably what I'll end up doing.  I don't want to cheat. Do you think this is a bug in NBlood that can be fixed?

**Comment by Hendricks266** [comment]
It is fixed. The problem is that a save created with a version before the fix was added will inherit hte problem.

**Comment by CommonLoon102** [comment]
No. Usually you can't even load saves from earlier versions. This is how the BUILD engine works.

**Comment by PopeRigby** [comment]
Ok. Closing.
