### ISSUE TITLE
Final cutscene doesn't play

### ISSUE THREAD

**Issue by PopeRigby** [nukeykt/NBlood#285]
[This](https://youtu.be/-vIr-rTd5N0) cutscene doesn't play, despite killing Tchernobog, and the ending credits playing.

**Comment by CommonLoon102** [comment]
It plays for me in latest master. Do you have all the needed smk files?

**Comment by CommonLoon102** [comment]
It is possible that you were pressing some keys when the video wanted to play, in that case, it skips instantly, I think we should only allow skipping by pressing escape, because currently it skips for any keyboard/mouse/joystick button.

@nukeykt @Hendricks266 what do you think?
