### ISSUE TITLE
Blood: Out for Blood mod map 4 OpenGL issue

### ISSUE THREAD

**Issue by CommonLoon102** [nukeykt/NBlood#295]
On OFB04 at the very beginning of the map, the little forest area is being rendered very strange in OpenGL. In software rendering it is OK.
https://media.discordapp.net/attachments/544944689028136970/670976459191484429/ofb04.png

In 1.01 it is OK.
I've seen similar graphic glitches in other custom maps too.

**Comment by CommonLoon102** [comment]
It got broken by this commit: https://github.com/nukeykt/NBlood/commit/55117cf08a8629d2d5e10c766e9b18c3a6ca4c19

**Comment by nukeykt** [comment]
fixed in 658c992487edd85e8ed3236fe8284f386ce17000
