### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by alexey-lysiuk** [nukeykt/NBlood#3]
Please add a continuous integration, [Travis CI](https://travis-ci.org/) for example.

I can provide a configuration for Travis if you would like to use it.

**Comment by nukeykt** [comment]
Oh yeah, good suggestion. Please send config file, i newer used any CI before.

**Comment by alexey-lysiuk** [comment]
BTW if you want to keep a more linear commit history, you can merge a PR without merge commit or even rebase pull requests on top of the current head.
