### ISSUE TITLE
PCExhumed: demo playback

### ISSUE THREAD

**Issue by BSzili** [nukeykt/NBlood#303]
I tried the demo playback by enabling the timer in menu.cpp. It worked until the very end where the player touches the sarcophagus. Instead of ending the demo he gets pushed to the right and the control is partially returned. AFAIR this used to work about a month ago, so I'll try to find which commit broke it. 
Interestingly renaming demo.vcr to data.vcr, and launching the game with the "-playback" argument still works, and the demo ends as intended when the sarcophagus is touched.

**Comment by sirlemonhead** [comment]
[pcexhumed_issue_303.zip](https://github.com/nukeykt/NBlood/files/4168335/pcexhumed_issue_303.zip)

Thanks, will take a look. I've created a demo file and level/map file that finishes in a few seconds.. I'd go mad having to sit through that full demo each time!

**Comment by BSzili** [comment]
I went back to the first PCExhumed merge into this repo, but it seems to have the same issue, so I probably remembered wrong and only used -playback to play the whole thing. Anyway, at least now there's an easy repro for the bug :)

**Comment by sirlemonhead** [comment]
That's fixed now!
