### ISSUE TITLE
Issue with Bone Eel attack state

### ISSUE THREAD

**Issue by alexey-lysiuk** [nukeykt/NBlood#31]
Occasionally, I managed to trigger the following assertion failure:
`pXSprite->target >= 0 && pXSprite->target < kMaxSprites in file /Volumes/ramdisk/NBlood/source/blood/src/aiboneel.cpp at line 86`
The value of `pXSprite->target` is -1.

Good news is it happens right after loading of [this saved game](https://github.com/nukeykt/NBlood/files/2898006/game0004.sav.zip).
Bad news is it doesn't seem to have enough information to figure out what's wrong with it.

In addition, the given assertion should be moved at the beginning of `BiteSeqCallback()` because out-of-bounds access to `sprite` array in [this line](https://github.com/nukeykt/NBlood/blob/407b568df1817780ab74245b47202adb88137bfe/source/blood/src/aiboneel.cpp#L78).

**Comment by david0rk** [comment]
I have a save file that replicates the issue if it is helpful. 

i just got done submitting the bug report for the HOM issue with polymost, and after playing a bit my save had this issue crop up.  
save is from a level in deathwish[( https://www.moddb.com/mods/death-wish-for-blood)]
[game0000.sav.zip](https://github.com/nukeykt/NBlood/files/2916461/game0000.sav.zip)

**Comment by david0rk** [comment]
Ok, so i've been poking around at this one, i've found a workaround that clears this specific case.
It may point to  a bigger issue (uninitialized/improperly handled state) , its ugly, but I've submitted a pull request.

**Comment by CommonLoon102** [comment]
Seems to be fixed:
https://github.com/nukeykt/NBlood/blob/master/source/blood/src/aiboneel.cpp#L87

**Comment by david0rk** [comment]
Yeah, I think my pull request was accepted, but the bug was never flagged as fixed/closed

**Comment by Hendricks266** [comment]
Fixed in 00107feb0c310ce24a3d022bde3be18dc2d342a8
