### ISSUE TITLE
Blood: cinematics playback is partially broken

### ISSUE THREAD

**Issue by CommonLoon102** [nukeykt/NBlood#311]
If the GTI.SMK played at start then game cinematics won't play back correctly (but only in case of fullscreen OpenGL).

It looks like this: https://cdn.discordapp.com/attachments/461290354726010891/676947552838483988/gti.png

**Comment by Hendricks266** [comment]
Fixed by c4bef953ddde3202c7eb61e2182902dc4acb7ba2
