### ISSUE TITLE
Dynamite & Aero Cans do not explode after death when you respawn fast, and sound gets stuck in map.

### ISSUE THREAD

**Issue by hvownij** [nukeykt/NBlood#315]
Tested and was replicated easily.

Take dynamite bundle and hold fire down, have 2nd player kill you.  If you do not respawn fast, and watch the wick burn down, the correct behavior happens, it explodes.  

Do the same thing as above, this time respawn while the wick is still burning.  The explosion does not ever happen, and you are left with the burning wick sound forever in the map.

This same issue happens with aero cans.  the noise level is much louder with this weapon.

**Comment by CommonLoon102** [comment]
Have you tried compiling the game with `NOONE_EXTENSIONS=0`? And check if this bug is still there. Those extensions caused a lot of regressions recently, maybe this is also one of them.

**Comment by hvownij** [comment]
This behavior is present in nblood stable release also.

**Comment by CommonLoon102** [comment]
I've tested this in NBlood latest master and I was able to reproduce.
Altough, I tested it in DosBox and the very same things happen there too. It is a bug from the original. Therefore I'm not sure if it is needed to be fixed at all.

**Comment by hvownij** [comment]
I dont believe that the sound playing forever should be overlooked.  At the
very least this should be removed.

**Comment by CommonLoon102** [comment]
As a workaround you can turn off the sounds and turn on again, then the burning fuse sound go away.
