### ISSUE TITLE
Polymost HOM 

### ISSUE THREAD

**Issue by david0rk** [nukeykt/NBlood#32]
I've noticed various hall of mirrors type bugs using the polymost renderer, issue goes away the classic renderer. 

screenshot of issue https://imgur.com/a/LpaeXwK 
Easiest way to reproduce is level one in deathwish 
https://www.moddb.com/mods/death-wish-for-blood

**Comment by nukeykt** [comment]
Does 2969d430f3dba23d73382a1735e4ac1f189d8c1b make any difference with this particular HOM in DWE1M1

**Comment by david0rk** [comment]
It fixed the issue in DWE1M1.

i also tried DWE2M1 which i remember having similar issues

![1](https://user-images.githubusercontent.com/5011196/53747799-13bf2a80-3e72-11e9-935e-0ea557479a1a.png)
![2](https://user-images.githubusercontent.com/5011196/53747800-13bf2a80-3e72-11e9-921e-4e2a2051d9fa.png)
![3](https://user-images.githubusercontent.com/5011196/53747802-1457c100-3e72-11e9-89f3-2b0e72545eb5.png)
![4](https://user-images.githubusercontent.com/5011196/53747803-1457c100-3e72-11e9-99f4-96dcc228791e.png)

**Comment by nukeykt** [comment]
DWE2M1 is a different issue. I think this one due to some calculation error with slopes

**Comment by david0rk** [comment]
gotcha, i've got a screen of that same area in vanilla blood in dosbox. 
![screenshot_2019-03-04_17-09-07](https://user-images.githubusercontent.com/5011196/53766283-6e6f7b00-3ea0-11e9-89d7-6350aef7d2fa.png)

**Comment by nukeykt** [comment]
Fixed in 8113ee42de0895749299425185fe97259a204068
