### ISSUE TITLE
NBlood Fullscreen checkbox not working in max resolution (always opens in fullscreen mode)

### ISSUE THREAD

**Issue by MexMeRcUrY** [nukeykt/NBlood#326]
![image](https://user-images.githubusercontent.com/379976/75137461-467ab800-56ad-11ea-8a84-8dfc5fed3a20.png)

![image](https://user-images.githubusercontent.com/379976/75137531-775aed00-56ad-11ea-8262-5878cabff740.png)

**Comment by CommonLoon102** [comment]
And if you click `Maximize` in task explorer, it will disappear and you won't see the game anymore. You have to kill the process.

**Comment by MexMeRcUrY** [comment]
> And if you click `Maximize` in task explorer, it will disappear and you won't see the game anymore. You have to kill the process. (In case of windowed maximum resolution)
> 
> But I have to say that playing in maximum resolution in windowed mode doesn't make any sense. Some games can work like this, but you cannot see the whole game because it cannot fit on your screen... Or maybe it spans over to another monitor. It is just not good for anything. But Windowed Borderless can help tearing for some people, and that is what we have in case of NBlood if you select the maximum resolution in windowed mode, a `windowed borderless` mode which actually playable beause you can see everything and alt+tab works fine. I don't think it needs to be fixed. It is a feature, not a bug.

Thank you for the Explanation @CommonLoon102 !
