### ISSUE TITLE
Blood: Dynamite bundle thrown too soon

### ISSUE THREAD

**Issue by CommonLoon102** [nukeykt/NBlood#329]
If the FPS is capped below 30 (fps limit at 30 and fps offset is between -10 and -1 (inclusively)) then the game logic will have some weird things. For example, if I hold the primary fire key to throw a dynamite bundle, Caleb will throw it sooner than I release the primary fire key. The lower the FPS the sooner he throws.

**Comment by MexMeRcUrY** [comment]
I have been able to reproduce a similar issue with addons (with regular FPS config) Caleb will throw it sooner than I release the primary fire key.
Addon in autoload folder: https://www.moddb.com/mods/blood-xhd/addons/blood-xhd?
install addon:
1. extract only ZXHD_Blood.zip
2.- extract and rename ZXHD_Blood.def to blood.def
3.- copy the blood.def to ZXHD_Blood.zip
4.- move ZXHD_Blood.zip to the auto load folder
Enable Auto Load
![image](https://user-images.githubusercontent.com/379976/78654227-dbb2c400-7889-11ea-83b5-2410ac38f18e.png)
![image](https://user-images.githubusercontent.com/379976/78654872-d3a75400-788a-11ea-8651-ef45b8d4bb82.png)

New Game - > The way of all flesh - >  still kicking
1.- get out of the grave
2.- go for the secret TNT in the corner.
3.- load the hitting "6" key
4.- hold the primary fire key and at the same time open the door.
Result: Caleb will automatically release the dynamite when the door opens.
5.- instantly load another TNT and holding the primary fire key run into the ramp....
Result: caleb will release the dynamite at least 2 times if you keep loading dynamite and holding the primary fire key and running up and down the ramp.

**Comment by CommonLoon102** [comment]
OK, I see r_maxfps is 30 for you, that is why you have the bug, it doesn't have anything to do with the movie folder or files in the autoload folder.

**Comment by MexMeRcUrY** [comment]
i can reproduce it with 100fps
![image](https://user-images.githubusercontent.com/379976/78708252-74236580-78d7-11ea-9d2b-287cefa09cc5.png)

**Comment by MexMeRcUrY** [comment]
just FYI, I have tried to reproduce this in ReNukem with our success so its just a blood code issue.

**Comment by MexMeRcUrY** [comment]
I have found the issue however i have not found the rootcause :(
void ProcessFrame(void)
gPlayer[i].input.buttonFlags = gFifoInput[gNetFifoTail & 255][i].buttonFlags;

gFifoInput[gNetFifoTail & 255][0].buttonFlags.shoot is getting updated to 0 when you have not released the fire button.

**Comment by MexMeRcUrY** [comment]
related to this issue I have found that in Nblood and Raze when you hold the fire button with a dynamite and you click the "PrtScreen" key it also releases the dynamite. it does not happen with any other key.

**Comment by MexMeRcUrY** [comment]
I have been able to fix commonloon issue when setting up MAXFPS values. however not when the game performance hiccups with add ons.
https://github.com/MexMeRcUrY/NBlood/tree/FPSValidationFrameDelay

**Comment by MexMeRcUrY** [comment]
never mind... i have found the fix for the root cause of the issue. Lucky me :)
