### ISSUE TITLE
No cutscenes [GOG version]

### ISSUE THREAD

**Issue by neuromancer** [nukeykt/NBlood#33]
This is probably a known issue, but the latest release of NBlood (9b35374896870445afc0acbf515c022e350594b6) has no cutscenes, at least when it is using the GOG version.

**Comment by Manuel-K** [comment]
Did you copy the MOVIE folder from the CD image (game.ins is a cue file, game.gog is a bin file)?

**Comment by neuromancer** [comment]
Oh, right. Sorry!
