### ISSUE TITLE
FOV above 120 gets reset, Voices above 128 gets reset

### ISSUE THREAD

**Issue by RazTK** [nukeykt/NBlood#330]
Settings the FOV above 120 is reset when NBlood is launched again.
Voices is reset when set above 128.
EDIT: Another really minor thing I noticed: vid_gamma is saved twice in settings.cfg. Thought I'd mention it here instead of opening a new issue about it.

**Comment by carnivoroussociety** [comment]
This has been fixed in this PR https://github.com/nukeykt/NBlood/pull/509
