### ISSUE TITLE
Blood: Caleb doesn't talk in coop

### ISSUE THREAD

**Issue by CommonLoon102** [nukeykt/NBlood#333]
Things like "I need a key", "Nevermore", "Open for business", and so on.
In single player Caleb says these but not in coop. Not even for the host. In 1.01 stable release this worked.

In bloodbath these lines were not played in 1.01 either.
BUT
Now the "Let the bloodbath begin" doesn't plays either anymore.

**Comment by MexMeRcUrY** [comment]
I have added a fix for these to scenarios you mention Coop & Blothbath
https://github.com/MexMeRcUrY/NBlood/tree/CalebSoundsMultiplayer
