### ISSUE TITLE
Blood: EVICTION: The Hive mirror

### ISSUE THREAD

**Issue by BSzili** [nukeykt/NBlood#334]
I found a mirror in the recently updated Eviction map pack that is broken. Here's how it looks with software:
![blud0001](https://user-images.githubusercontent.com/3398465/77225468-a1e67b80-6b6f-11ea-9836-d8be6f493156.png)
and Polymost:
![blud0000](https://user-images.githubusercontent.com/3398465/77225464-9d21c780-6b6f-11ea-9917-d96ff83bdece.png)

Eviction:
http://www.blood.freeminded.de/index.php?section=episodes&id=617
Save game at the exact location.
[game0005.zip](https://github.com/nukeykt/NBlood/files/4362767/game0005.zip)

**Comment by CommonLoon102** [comment]
If you don't save and load just start the map and enter cheats and go to that mirror, is it broken in that case? If not, then this is the same issue as https://github.com/nukeykt/NBlood/issues/338

**Comment by BSzili** [comment]
I just checked and the mirror is fine if I don't save/load. This issue is a duplicate then.
