### ISSUE TITLE
Blood: Cinematic/Movie + Custom content/Addons

### ISSUE THREAD

**Issue by MexMeRcUrY** [nukeykt/NBlood#343]
when setting up Nblood with the movie folder + custom content (texture load) it duplicates the number of textures every time you die until Nblood crashes:
Frist time:
Loding 1915 textures
Die 1:
Loading 1915 * 2 = 3830 textures
die 2:
Loading 1915 * 3 = 5745 textures
......
....
Nblood Crash: nblood.exe has triggered a breakpoint.
![image](https://user-images.githubusercontent.com/379976/78462871-a6448580-7693-11ea-8a9d-a8365cbd74d1.png)

**Comment by CommonLoon102** [comment]
I can't reproduce it. What do I need to do exactly? Show a screenshot about your startup window.

**Comment by MexMeRcUrY** [comment]
Let me try the new setup you just told me about (single ZIP file) and ill try to reproduce it. if I cannot I will close this issue

**Comment by MexMeRcUrY** [comment]
> I can't reproduce it. What do I need to do exactly? Show a screenshot about your startup window.

@CommonLoon102  were you able to replicate this?

**Comment by CommonLoon102** [comment]
> 
> 
> > I can't reproduce it. What do I need to do exactly? Show a screenshot about your startup window.
> 
> @CommonLoon102 were you able to replicate this with the steps i provided above?

I haven't tried, sorry.

**Comment by CommonLoon102** [comment]
OK, now I have reproduced it. What is interesting is that you have to have your movie folder there, otherwise it doesn't happen.

**Comment by MexMeRcUrY** [comment]
ok. Ill do the PR for the fix again. I just wanted to confirm. Thank you!!
