### ISSUE TITLE
Blood: Host Game does not work after cancel

### ISSUE THREAD

**Issue by MexMeRcUrY** [nukeykt/NBlood#350]
1.-Multiplayer - > Host a Game -> keep defaults - > click Host Game
2.- Waiting for players 1/ x
3.- hit Esc key
4.- Multiplayer - > Host a Game -> keep defaults - > click Host Game
Result: returns to demo (main menu)
does not let you start a host, and you need to restart Nblood to do so.

**Comment by CommonLoon102** [comment]
Yes, this is a known issue. In the original you don't have an option to start a new multiplayer game from the menu. You need to start a new multiplayer game from `setup.exe`. So I guess this is why we have this bug, but it could be definitely ironed out.

**Comment by Hendricks266** [comment]
Is this issue still present?
