### ISSUE TITLE
Blood: Multiplayer game "Start Game" button should be available/enabled only for host

### ISSUE THREAD

**Issue by MexMeRcUrY** [nukeykt/NBlood#351]
when waiting for players and they are all connected the option to config the game is availablae to every body instead of only for Host.

Blood GDX - disables the Start Game button for everybody except the host

**Comment by MexMeRcUrY** [comment]
is this a bug or feature?

**Comment by CommonLoon102** [comment]
> 
> 
> is this a bug or feature?

Dunno, but @nukeykt is against this idea:
https://github.com/nukeykt/NBlood/pull/182#issuecomment-533663641

**Comment by MexMeRcUrY** [comment]
thnx... then its a feature :)

**Comment by NY00123** [comment]
I can add that the exact opposite happened for Duke Nukem 3D, interestingly.

In version 1.3d, only the first player (identified as the master) can start a game. This is also the case while already having another game in progress. This was changed in version 1.4, for which any player can start a new game.

**Comment by CommonLoon102** [comment]
Yeah, because what if the host quits, then nobody could change the map anymore.
