### ISSUE TITLE
Blood: Fresh supply search path not working

### ISSUE THREAD

**Issue by MexMeRcUrY** [nukeykt/NBlood#352]
I was testing fresh supply files and i noticed that even that in the code the search path exists ("%s/steamapps/common/Blood") it does not load it, however "One unit whole blood" works fine.
![image](https://user-images.githubusercontent.com/379976/79560303-fa287480-806c-11ea-88d8-11bfbe3931de.png)
![image](https://user-images.githubusercontent.com/379976/79560366-1c21f700-806d-11ea-853f-d32200bc77ab.png)

-J Param as workaround does not work when One unit whole blood is found:
nblood.exe -j "D:\Program Files (x86)\Steam\steamapps\common\Blood"

![image](https://user-images.githubusercontent.com/379976/79560825-ecbfba00-806d-11ea-8c6a-0a4cb7373ffc.png)

**Comment by CommonLoon102** [comment]
You need to uninstall One Unit Whole Blood, and only then it will look after Fresh Supply.
Also, the screenshot about the code: it shows the code for Linux, OSX and BSD, and your other screenshots are from Windows.

**Comment by Jan200101** [comment]
Here is the relevant code
https://github.com/nukeykt/NBlood/blob/cb2022fb238c4fdbbe8e34f9bede8ba42508f4fe/source/blood/src/common.cpp#L350-L396
it would be useful if someone could supply the steamid of Blood so it can be added

**Comment by CommonLoon102** [comment]
> it would be useful if someone could supply the steamid of Blood so it can be added

What steamid? Both is in the code already.

**Comment by Jan200101** [comment]
Right, my bad, I forgot Fresh Supply had its folder called Blood

**Comment by MexMeRcUrY** [comment]
Or modified to take the one (prioritize) the one I'm sending in the CMD. is another solution to what Jan200101 already said

**Comment by MexMeRcUrY** [comment]
> You need to uninstall One Unit Whole Blood (or just rename the folder), and only then it will look after Fresh Supply.

I already tried renaming... it does not find it (its the first screen shot with the red-X)

**Comment by Jan200101** [comment]
I don't know exactly how Steam stores information in the registry but I assume a simple rename won't do the job because the registry entry still exists

**Comment by MexMeRcUrY** [comment]
@Jan200101  it is correct my registry match with the code... so ill have to debug and find the root cause of the issue. thanks for pointing out the correct code.
![image](https://user-images.githubusercontent.com/379976/79598968-62497b80-80aa-11ea-909a-51e53e4a7d1f.png)

**Comment by Jan200101** [comment]
no what I mean is
it checks for Steam App 299030 (One Unit Whole Blood) in the registry first and because you moved the directory instead of uninstalling the game via steam the registry entry still exists and never checks for Steam App 1010750 (Fresh Supply)

**Comment by Jan200101** [comment]
I guess one solution would be removing the found boolean entirely

**Comment by MexMeRcUrY** [comment]
yet if i send -J it should take my parameter so i'll work on that insted and leave the steam lookup as it is

**Comment by Jan200101** [comment]
oh yeah about the -j argument
you need to use it like this:
`nblood.exe -j="directory"` notice the equal sign, it won't work without it, though you can work to improve this behavior and not require it

**Comment by MexMeRcUrY** [comment]
thank you for the tip... looks like the documentation needs to be corrected in the "usage" to keep the current functionality and don't get into more trouble.
![image](https://user-images.githubusercontent.com/379976/79601523-8dce6500-80ae-11ea-845a-b4cfdc0672d9.png)
