### ISSUE TITLE
Microstutter

### ISSUE THREAD

**Issue by UninhabitedCranium** [nukeykt/NBlood#355]
I get microstutter when moving with this release. Sometimes its fine until I open the menu or autosave, but other times I get it even starting a new game. Its not fps drops, I monitored that and it is solid. Any idea what I could do to stop this?

**Comment by CommonLoon102** [comment]
Which release you use? What OS you running it on? On what kind of hardware? What are your settings? V-Sync on? G-Sync/Freesync on? FPS cap? FPS offset? Renderer mode?

**Comment by UninhabitedCranium** [comment]
v1.01
Windows 10
gtx 970 i7 4970k 8gb ram hard drive no ssd
I have everything set to  on or at default in polymost renderer
vysnc is on with 60 fps limit 0 fps offset

**Comment by UninhabitedCranium** [comment]
After testing some options out, it is 100% having vsync on. Its odd though, I can use an earlier build and not have the problem.

**Comment by Hendricks266** [comment]
I just pulled some vsync/stutter fixes from upstream EDuke32. You can give them a try the next time the buildbot runs, or you can build a fresh binary on your own. https://lerppu.net/wannabethesis/

**Comment by UninhabitedCranium** [comment]
Thanks I'll give it a try.
