### ISSUE TITLE
Blood: Fresh Supply Cryptic Passage texture problems

### ISSUE THREAD

**Issue by CommonLoon102** [nukeykt/NBlood#356]
Because in FS the filenames are different for 2 files (FS doesn't have `CPART07.AR_` and `CPART15.AR_`), the textures don't load correctly when playing Cryptic Passage.

**Comment by Asais10** [comment]
I personally did a thing where I renamed the Fresh Supply Cryptic Passage's modified art files tiles007.art and tiles015.art to cpart07.ar_ and cpart15.ar_ AKA as they were originally called in OUWB. It seems to have worked, as the first level in Cryptic Passage then used the correct skybox.

**Comment by Hendricks266** [comment]
I believe I fixed this in c6a7ed096f5af7eade3bea82a80fb34bc62e3cee and 4077a0821b786fd5c9fcaaf2fb8a0ebc118ab481. See also #673.
