### ISSUE TITLE
NBlood - Jerky framerate with newest builds

### ISSUE THREAD

**Issue by Trystanosaurus** [nukeykt/NBlood#358]
I played through Blood and Cryptic passages fine using automated build 20200404-2488  from https://lerppu.net/wannabethesis/nblood/

I updated recently to 20200428-11380 to play through Bloody Pulp Fiction and the framerate became quite jerky, most noticeable when turning quickly. I tried all sorts of different vsync and framerate limiter settings (setting it in game and in the graphics card software) but no luck. rolling back to my previous version was the only thing I found that fixed it.

**Comment by UninhabitedCranium** [comment]
I think I have the same issue, but it isn't framerate related. It's really bad microstutter like the 64 Hz bug in the gamebryo engine.

**Comment by Trystanosaurus** [comment]
I've just tried the latest version (20200527-11614) and it seems to have fixed my problems. I guess it was the previous commit that improved them main loop and input.

**Comment by UninhabitedCranium** [comment]
Yeah, the current build fixes it for me as well.

**Comment by Trystanosaurus** [comment]
Perfect, I'll close this issue then. Thank you devs for all of your work on the build series, it's great to see these games getting the love they deserve.
