### ISSUE TITLE
Bizarre graphic glitch

### ISSUE THREAD

**Issue by PopeRigby** [nukeykt/NBlood#36]
[Yeah...](https://photos.google.com/photo/AF1QipO1t4wVxUe1FF9P4Lq5quuW_H5D-T5wKO7p8NFR )

**Comment by david0rk** [comment]
> [Yeah...](https://photos.google.com/photo/AF1QipO1t4wVxUe1FF9P4Lq5quuW_H5D-T5wKO7p8NFR)

404-ing

**Comment by PopeRigby** [comment]
What do you mean by that?

**Comment by david0rk** [comment]
The image you linked is giving a 404 file not found error.

**Comment by PopeRigby** [comment]
Oh. Sorry. Here: https://photos.app.goo.gl/w1GwVuhzD3XrUYPe6

**Comment by nukeykt** [comment]
Weird, never seen this glitch. What's your pc's specs? Do you have similar issues with EDuke32 or Rednukem?

**Comment by clobber** [comment]
@david0rk for reference: https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests

**Comment by PopeRigby** [comment]
> 
> 
> Weird, never seen this glitch. What's your pc's specs? Do you have similar issues with EDuke32 or Rednukem?

Specs:
GTX 1060 6GB
16GB RAM
i7-7700

I've never played EDuke32 or Rednukem.

**Comment by littletijn** [comment]
Looks like some of the .ART files are missing. Are you sure you have files TILES000.ART till TILES017.ART in the directory of NBlood?

**Comment by PopeRigby** [comment]
Hmmm. I guess I didn't have TILES000.ART. Sorry

**Comment by littletijn** [comment]
Can happen. Have fun playing!
