### ISSUE TITLE
PCExhumed: player weapon sound position is off on moving platforms

### ISSUE THREAD

**Issue by BSzili** [nukeykt/NBlood#366]
On horizontally moving platforms I hear the player's weapon sound from the wrong position, as if it was ahead of the actual player position if that makes sense. It can be reproduced by firing the M60 while standing on a moving platform.

**Comment by sirlemonhead** [comment]
I tried this on the platform that moves back and forth across the lava on the training level and it sounded OK - is there somewhere else I can test this where you had the problem?

**Comment by BSzili** [comment]
I tested it on the training level, and it happens there too, but it's a bit trickier to reproduce than I remembered. You have to face the walls so the movement happens in a left-right direction, and it only happens in one direction, when the platform is moving "backwards".

**Comment by sirlemonhead** [comment]
Thanks! Can recreate it now! very odd that it only happens in that direction! the sound appears to come from the left. It's an original bug too. I'll get that fixed hopefully!
