### ISSUE TITLE
Error when compileing Redneck Rampage

### ISSUE THREAD

**Issue by Exarkuniv** [nukeykt/NBlood#369]
im working on a Raspberry Pi3b running Retropie
someone just posted that they got NBlood working along with Exhumed and Redneck Rampage.

i was able to get Blood to compile and play.
but when i got to Redneck Rampage i get this

`Failed building obj/rr/player.o from source/rr/src/player.cpp!
GNUmakefile:1599: recipe for target 'obj/rr/player.o' failed
make: *** [obj/rr/player.o] Error [1`

i did see [this ](https://github.com/nukeykt/NBlood/issues/332) so i used that as a guild line to get it working...for the most part.

im very new with trying my hand at compiling games or any software for that matter. so any help would be great

**Comment by Exarkuniv** [comment]
still cant get Redneck Rampage to compile and now Blood fails. but  PCExhumed works fine
still trying on my Raspberry Pi3b running Retropie.
im running Buster 4.19.118-v7+

not sure if that helps
this is what i get each time

`/usr/bin/ld: /tmp/ccsppsEa.ltrans11.ltrans.o: in function `enet_time_get':
<artificial>:(.text+0xccc): undefined reference to `__atomic_load_8'
/usr/bin/ld: <artificial>:(.text+0xd28): undefined reference to `__atomic_compare_exchange_8'
collect2: error: ld returned 1 exit status
Failed linking rednukem!
If the build options, environment, or system packages have changed, run \'make clean\' and try again.
make: *** [GNUmakefile:1487: rednukem] Error 1
`

**Comment by actraiser30** [comment]
hello i got the same error did you fix it ??

**Comment by Exarkuniv** [comment]
no. i did get help from a dev and he turned off a bunch of the flags, but it still never worked. so for Redneck Rampage it will only work on the Pi4 since it supports OpenGL

**Comment by actraiser30** [comment]
did you install all the depends?

**Comment by Exarkuniv** [comment]
yes i did since they all use the same depends and i had blood and PCExhumed work fine

see [here ](https://github.com/nukeykt/NBlood/issues/398 )what Commonloon said about it 
and [here ](https://github.com/nukeykt/NBlood/pull/397) what Hendricks266 saids about turning off the flags.

i did get it to compile just fine on a Pi4, i just have not tried it yet

**Comment by actraiser30** [comment]
did you install it in raspbian desktop or lite?

Στις Τετ, 2 Δεκ 2020 στις 6:41 μ.μ., ο/η Exarkuniv <notifications@github.com>
έγραψε:

**Comment by Exarkuniv** [comment]
none, i run RetroPie and there is no desktop. (they have it disabled) i believe it is Debian/ stretch. i dont remember what version

**Comment by actraiser30** [comment]
Stretch its old try the latest retropie buster

Στις Πέμ, 3 Δεκ 2020, 21:16 ο χρήστης Exarkuniv <notifications@github.com>
έγραψε:

**Comment by Exarkuniv** [comment]
That's what my pi4 is running and I got it to compile just fine. Just have not tested it

I'm not going to bother with my pi3 build. I have it just the way I want it so I don't care if it is running stretch

**Comment by retro24** [comment]
i tried under retropie and is not working how you make your under retropie running?

**Comment by retro24** [comment]
its not working anyway in a Rpi4 raspbian desktop dont bother to try its working flawless in Rpi3 thought

**Comment by retro24** [comment]
its not working anyway in a Rpi4 raspbian desktop dont bother to try its working flawless in in Rpi3 thought

**Comment by Exarkuniv** [comment]
i just tested Rednukem on my Pi4 and it works just fine. the music is missing but someone else has a ticket open about that.
im running the latest Retorpie build so i know it has buster and no desktop

i just followed the instrstions on how to compile from this post on the RetroPie fourms [here](https://retropie.org.uk/forum/topic/22308/suggestions-for-ports/235?_=1607348430379)

and also followed [this ](https://github.com/nukeykt/NBlood/issues/332) for more help
