### ISSUE TITLE
Rednukem: Rides Again REDINT.MVE playback crashes

### ISSUE THREAD

**Issue by BSzili** [nukeykt/NBlood#370]
I can see the first frame, but then it crashes. The last version that worked was "r11576 - May 26 2020", so I think it was this merge that broke it:
6b43f62825900e264605e0b82db2866c33f8e6ad

**Comment by sirlemonhead** [comment]
Seems Exhumed was broken too. A fix is on the way :) Thanks for reporting these things! :)

**Comment by sirlemonhead** [comment]
Fixed in 8d77510
