### ISSUE TITLE
Damage Sectors Not Working Properly when Data=0

### ISSUE THREAD

**Issue by Bloatoid** [nukeykt/NBlood#38]
Sectors with a number set to "DamageType" are doing greatly reduced damage/sec when Data=0. Previously, if you set the Data value to "0", the damage output was almost equivalent to an instant-kill.

If you want to see the difference, go to Blood's e1m3 Phantom Express. In DOSBox, jumping off the train kills almost instantly. In nBlood, you can hop along the ground and make it all the way to the back of the train because the damage output is so low. 

As a side-note, this instant-kill feature should work as long as a DamageType is set to anything other than 0 regardless of the sector Type. Originally in Mapedit, you didn't need to actually tag a sector as "Type: 618 Damage Sector" to do damage. If you look at the Death Wish mod, dwe1m2 has moving sectors (the cars/trucks) that deal damage/sec despite being sliding sectors. They currently don't work as intended in nBlood since the Damage output for Data=0 is so low.

**Comment by nukeykt** [comment]
Which version did you test? Does this happen with version built from sources? This should be already fixed in 3925b3c6cd23cd2a4e1b374ab585cfbdf824bdcb

**Comment by Bloatoid** [comment]
I downloaded from here last night: http://nukeykt.retrohost.net/nblood.zip
I assumed this is where the most recent version would be since all the threads link to: http://nukeykt.retrohost.net/

**Comment by nukeykt** [comment]
This version predates this fix, so i'll close this issue. DM me in discord if you want to try binary built from sources
