### ISSUE TITLE
[PS] Voxels don't use x offset from seq

### ISSUE THREAD

**Issue by fgsfds** [nukeykt/NBlood#380]
Can be tested with invincibility pickup. Voxel is only moving along the y axis, while sprite is moving in a circle.
[psvoxels.zip](https://github.com/nukeykt/NBlood/files/4817442/psvoxels.zip)

![capt0000-1](https://user-images.githubusercontent.com/4870330/85368245-55328800-b544-11ea-8210-93c02ce3b801.png)

**Comment by nukeykt** [comment]
Should be fixed in 437e61efe73c27efb3673e1215a6078abc596433
