### ISSUE TITLE
cant compile blood on buster 4.19.97 Raspberry pi4

### ISSUE THREAD

**Issue by Exarkuniv** [nukeykt/NBlood#381]
`
source/blood/src/menu.cpp: In function ‘StartNetGame’:
source/blood/src/menu.cpp:2247:13: warning: ‘strncpy’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
     Bstrncpy(gPacketStartGame.userMapName, zUserMapName, Bstrlen(zUserMapName));
             ^
/usr/bin/ld: /tmp/cc4Xwtk2.ltrans17.ltrans.o: in function `enet_time_get':
<artificial>:(.text+0xd08): undefined reference to `__atomic_load_8'
/usr/bin/ld: <artificial>:(.text+0xd64): undefined reference to `__atomic_compare_exchange_8'
collect2: error: ld returned 1 exit status
Failed linking nblood!
If the build options, environment, or system packages have changed, run \'make clean\' and try again.
`

not sure what dependencies im missing that i keep getting this. i have looked around and everything i have tried i still get this. 
hope someone can point me in the right direction

**Comment by Hendricks266** [comment]
I've seen this issue. We need to add `-latomic` to our linker flags on ARM platforms.

**Comment by Exarkuniv** [comment]
ok, least im not crazy.

is it something that i could do on my setup, or is it best to wait for a fix on your end.

**Comment by Exarkuniv** [comment]
i did figure it all out. 
looking at the other ticket for getting this to work on the Pi. i found out what i was doing wrong.

**Comment by patitocareri222** [comment]
> Lo resolví todo.
> mirando el otro boleto para hacer que esto funcione en el Pi. Descubrí lo que estaba haciendo mal.

And the link for other ticket?... :(

**Comment by Exarkuniv** [comment]
> 
> 
> > Lo resolví todo.
> > mirando el otro boleto para hacer que esto funcione en el Pi. Descubrí lo que estaba haciendo mal.
> 
> And the link for other ticket?... :(

https://github.com/nukeykt/NBlood/issues/332
