### ISSUE TITLE
When naming CD audio tracks bloodXX.flac/ogg, start at 00, 01, or 02?

### ISSUE THREAD

**Issue by NessInOnett** [nukeykt/NBlood#384]
When working with CD audio tracks, the README says:

> Optionally, if you want to use CD audio tracks instead of MIDI, provide FLAC/OGG recordings in following format: bloodXX.flac/ogg, where XX is track number. Make sure to enable Redbook audio option in sound menu.

Because of the nature of mixed-mode discs, there's some confusion about this.  

* The first audio track on the CD is track 2 (track 1 being data) (**start at blood02.flac?**)

* But the first audio track is the first audio track (**start at blood01.flac?**)

* Or maybe it's zero-based?  (**start at blood00.flac?**) 

Which is the correct way to name these files?  I think the README should be updated to clarify

Thanks!

**Comment by CommonLoon102** [comment]
Both Fresh Supply and One Unit Whole Blood comes with the ogg tracks, starting with **blood02.ogg**. So people usually just copy these files and not creating their own tracks. In `blood.ini` you can see which track is played on each map (look at the `Track` key).

**Comment by NessInOnett** [comment]
> Both Fresh Supply and One Unit Whole Blood comes with the ogg tracks, starting with **blood02.ogg**. So people usually just copy these files and not creating their own tracks. In `blood.ini` you can see which track is played on each map (look at the `Track` key).

Ohh, gotcha. 

That must be only for the GOG version.  I was ripping as FLAC from the original game CD.  When it came time to name the ripped audio tracks, I wasn't sure how to name them.  Thanks
