### ISSUE TITLE
Bugged Fanatics in E3M2 do not render correctly compared to DOS

### ISSUE THREAD

**Issue by ghost** [nukeykt/NBlood#385]
In E3M2, there's some bugged out Fanatics that are set to use the colour scheme as the standard Cultist instead. However on Nblood, their graphics will swap between the two. Video example of this glitch compared to both DOS and Nblood can be seen below:

[Youtube video URL](https://youtu.be/t72879y_tos)

Tested on NBlood rr11753-ce8f23d2c-ce8f23d2c

**Comment by CommonLoon102** [comment]
This happens in DOS too, I haven't created a video so you have to believe me. Try it a few more times.
