### ISSUE TITLE
Layered Transparent Sprites Not Displaying Properly 

### ISSUE THREAD

**Issue by Bloatoid** [nukeykt/NBlood#39]
When 2 sprites occupy the same space and one of the them is transparent, there are instances where only the transparent sprite is visible (rather than both). Here's an example from Death Wish's dwe1m2:

https://i.imgur.com/8JOHWfE.png

![DOTS](https://user-images.githubusercontent.com/48483932/54210289-991b8e00-44b5-11e9-8ee8-e0a4bca10507.png)

DOSBox vs nBlood:

DOSBox
https://i.imgur.com/dBFIwXm.png
![dots-DOSBOX](https://user-images.githubusercontent.com/48483932/54210420-d122d100-44b5-11e9-8865-94c5ef03891d.PNG)

nBlood
https://i.imgur.com/rKFlOzd.png
![dots-nblood](https://user-images.githubusercontent.com/48483932/54210458-e697fb00-44b5-11e9-9c3e-bb205af719f5.PNG)

I'm not sure why this would happen in some spots and not in others. As you can see from the images, there are a few places where the sprites appear correctly.

**Comment by nukeykt** [comment]
I think this is z-fighting issue due to how polymost renders sprites. Does this happen with software renderer?

**Comment by Bloatoid** [comment]
This only happens when Renderer=Polymost. Renderer=Classic looks correct.

**Comment by nukeykt** [comment]
Fixed in 169cf97
