### ISSUE TITLE
(Feature) NBlood: Ability to quickly load last quicksave instead of restarting level with only pitchfork after dying + one small thing I don't think is worth it's own issue

### ISSUE THREAD

**Issue by Asais10** [nukeykt/NBlood#391]
Basically, when you die, you should be able to quickly load last quicksave instead of restarting the level with nothing but your pitchfork. And with the autosaves I suggested earlier, if no quicksave would be present in the level then you should be able to restart from autosave. 

And that other small thing: 
Basically there are some sounds in the Blood.rff file that aren't in the game by default, I know there is an additional sound made by the innocents: "please don't hurt me" and I've heard that there also was an additional burning sound. AFAIK, BloodGDX did restore at least that additional innocent line. So that would be a bit of a minor restoration.

**Comment by Asais10** [comment]
Oh and another small thing I forgot to mention: 

In the BloodBath multiplayer mode there was text that appeared when a player died; that in the singleplayer is only when you kill yourself. BloodGDX restored this text and I think NBlood should have it too. Example: "Shotgun Cultist ripped Joe a new orifice"

**Comment by CommonLoon102** [comment]
You have to open a separate issue for everything.

**Comment by CommonLoon102** [comment]
> So that would be a bit of a minor restoration.

That wouldn't be a restoration. It wouldn't be faithful to the original. Game developers removed that sound on purpose. It sounded lame.

**Comment by Asais10** [comment]
okay i'll close this issue
