### ISSUE TITLE
NBLOOD: Ambient SFX do not play from beginning when triggered.

### ISSUE THREAD

**Issue by SP1LL** [nukeykt/NBlood#393]
I have an Ambient SFX sprite that is off.

When it is triggered to start it does not play the SFX correctly.

It chops the beginning part of the SFX off.

This does not happen in Dos.

If you can't replicate, I can send the map that this is occurring in.

**Comment by CommonLoon102** [comment]
Yeah, please send the map.

**Comment by CommonLoon102** [comment]
Map: https://cdn.discordapp.com/attachments/740234381473480744/740234716422340608/SSGARAGE.MAP
Video: https://www.youtube.com/watch?v=uNwBWDaFEdQ

> Go to this area and trigger the tornado
> Notice how the emergency siren SFX is playing wrong
> In fact you can hear it at 0:11 in the video
> In Dos the sound plays from the correct start
