### ISSUE TITLE
Suggestion: quick save/load bindings in setup

### ISSUE THREAD

**Issue by George22x** [nukeykt/NBlood#394]
It seems that there is no quick save/load bindings in keyboard setup. Could you please add this feature?

**Comment by CommonLoon102** [comment]
There isn't any more keybinds left to add there, so this idea was dropped before (eduke32 engine limitation).
You can bind quicksave and quickload from console.
`bind mouse5 quickload`
`bind mouse4 quicksave`
Type `bind showkeys` to show the available keys to use in the bind command.
Type `listsymbols` to see the available commands.
Type `bind help` to see help.

**Comment by George22x** [comment]
Thanks for info. There are four keys for load, save, quickload, quicksave in the original game (viz. help chart). In nBlood I see only quickload and quicksave commands. I tried to bind them and while quickload works ok, quicksave only opens the save menu. Would it be possible to add missing commands?
Also are these mentioned limits for all menus or the keyboard menu only? If for the keyboard menu, I would suggest moving mouse aiming and toggle crosshair (functions that most players set only once) to the game menu, thus leaving space for quick save/load commands in the keyboard menu. One slot could be also gained if console bind was in console only, as most players probably will not need to change that.
