### ISSUE TITLE
OSX support?

### ISSUE THREAD

**Issue by tgiachi** [nukeykt/NBlood#40]
Hi everybody,
I've successfull compile NBlood for osx (same method of EDuke32) but when I start ./nblood (with blood file in same directory) still stuck.

Why?
Thanks
Tom
![Screen Shot 2019-03-20 at 18 26 31](https://user-images.githubusercontent.com/942730/54705715-c1eaf580-4b3d-11e9-9344-7f2e4d7b5837.png)

**Comment by alexey-lysiuk** [comment]
NBlood must be launched via application bundle. Starting executable directly most likely will fail due to missing resources.

**Comment by tgiachi** [comment]
Hi alexey! Thanks for great work !

I ve the same configuration for eduke, blood data files in the Resources directory but fails run. How i can enable debug/logs files?

**Comment by alexey-lysiuk** [comment]
I don't have any issues running NBlood via application bundle. I'm using Xcode to build it. Also, I never tried to run the executable directly. 
AFAIK log file is created by default in the current directory.

**Comment by tgiachi** [comment]
Hi alexey,
The log is empty, also I'm using Xcode (on mojave). There are other test I can do?

Thanks

**Comment by alexey-lysiuk** [comment]
Hard to say. I think you should be able to see startup window regardless of game files presence.
I'll try to run the NBlood myself as I didn't check it for a while.

**Comment by tgiachi** [comment]
Problem resolved! Which IDE you use for develop / extend NBlood? Thanks!
