### ISSUE TITLE
[Blood] Super Secret is counted to level stats.

### ISSUE THREAD

**Issue by Dzierzan** [nukeykt/NBlood#403]
If you find a super secret, it is added to the level stats. Although if you finish the level, the said super secret is not added, which is true to DOS version. So... it should not be added to the level stats activated in Display Setup.

Example from E1M1:

![blud0000](https://user-images.githubusercontent.com/17529329/93706568-dbe90800-fb27-11ea-89ed-cefc02e42381.png)

**Comment by CommonLoon102** [comment]
The fix seems straight-forward, the question is if we want to see 0/11 or 1/12 in this case?

**Comment by Dzierzan** [comment]
0/11 would be true to the DOS version. Although it is a bit counter-intuitive.

**Comment by CommonLoon102** [comment]
But there is no level stats displayer in the original DOS version. It would be the most true to the original if it was completely disabled. What can be done from the settings.
