### ISSUE TITLE
[Blood] Cutscene plays in the wrong place

### ISSUE THREAD

**Issue by ThunderTurtle7** [nukeykt/NBlood#407]
CS5 plays when starting episode 4, which seems to be the wrong spot because BloodGDX and Fresh Supply do not play that cutscene there. I haven't found any other reports of this or any other cutscenes in the wrong places yet.

**Comment by CommonLoon102** [comment]
It is an error in the ini file and in the whole logic in the game. The same bug is in the DOS version.
