### ISSUE TITLE
Controller support for menus

### ISSUE THREAD

**Issue by Jan200101** [nukeykt/NBlood#42]
gamepads can't be used in menus at all

**Comment by nukeykt** [comment]
Gamepad support is broken atm

**Comment by CommonLoon102** [comment]
How can you select 12 different weapons with a controller?

**Comment by nukeykt** [comment]
Rebasing to the latest eduke32 is not enough (mapedit branch already rebased to recent revision with controller support). Some additional coding on my side is required as well (update input code, add controller to the menu, etc)

**Comment by CommonLoon102** [comment]
@nvllsvm That must be very slow. There should be a smart solution, a weapon wheel or something. Not the one which is in Fresh Supply, that is lame and also slow. But something like the buy menu in CSGO.

**Comment by Jan200101** [comment]
I've actually implemented partial controller support in my NBlood fork NXBlood
[1](https://github.com/Jan200101/NXBlood/commit/1cad120bf91d12ab66f3ea1a9299b25ce6595ac7)  
Its not kept as up to date as it probably should have duo to me wanting to rework it after the merge of mapedit into master

**Comment by CommonLoon102** [comment]
Just out of curiosity, how did you solve going back one level in the menu? NBlood doesn't have a back button like EDuke32 does. You can use Esc or right mouse button, but what do you use in case of the controller to go back?

**Comment by Jan200101** [comment]
just like the right mouse button I just set the Escape event 
```
    else if (JOYSTICK_GetButtons()&SWITCH_BUTTON_B)
    {
        event.at0 = kMenuEventEscape;
        JOYSTICK_ClearButton(SWITCH_BUTTON_B);
    }
```

**Comment by SeongGino** [comment]
> 
> 
> I've actually implemented partial controller support in my NBlood fork NXBlood
> [1](https://github.com/Jan200101/NXBlood/commit/1cad120bf91d12ab66f3ea1a9299b25ce6595ac7)
> Its not kept as up to date as it probably should have duo to me wanting to rework it after the merge of mapedit into master
> 
> ignore the bottom most change
> it was an attempt at fixing something with limited knowledge of the codebase

The linked repo is down.
Do you still have these changes available in a place that we could view? I'm attempting to get NBlood (all engines) running on a similarly embedded device which only uses a gamepad as primary input.

**Comment by Jan200101** [comment]
> The linked repo is down.
> Do you still have these changes available in a place that we could view? I'm attempting to get NBlood (all engines) running on a similarly embedded device which only uses a gamepad as primary input.

yeah sorry for that
I haven't had time to maintain the Switch port for Blood and because it was seemingly unmaintainable from my perspective I deleted the repo

In a previous comment

> just like the right mouse button I just set the Escape event
> 
> ```
>     else if (JOYSTICK_GetButtons()&SWITCH_BUTTON_B)
>     {
>         event.at0 = kMenuEventEscape;
>         JOYSTICK_ClearButton(SWITCH_BUTTON_B);
>     }
> ```
> 
> [reference](https://github.com/nukeykt/NBlood/blob/master/source/blood/src/gamemenu.cpp#L1534)

I have talked about the exact actions I took to achieve gamepad support in menus
SWITCH_BUTTON_B in this case is an macro to the bit that signifies if the buttoin is pressed.
