### ISSUE TITLE
Black screen with videoSetGamma() errors, game logic seems to be running?

### ISSUE THREAD

**Issue by uncletrunks** [nukeykt/NBlood#422]
I'm building with `make CROSS=/opt/gcw0-toolchain/bin/mipsel-linux- RENDERTYPESDL=1 USE_OPENGL=0 POLYMER=0 WITHOUT_GTK=1 USE_LIBVPX=0 CXXFLAGS='-latomic' -j$(nproc)`. This platform (an Anbernic RG350M running OpenDingux) doesn't support OpenGL so I'm building without that. I'm not really sure what the issue with is and I'm not abundantly familiar with this codebase. If anyone has some idea of what the problem is I'd appreciate it.

```
Exhumed r11979-d3c5f9c08
Built Nov 21 2020 22:23:45, GCC 10.2.0, 32-bit
Using /media/data/local/home/pcexhumed/ for game data
Using /media/data/local/home/.config/pcexhumed/ for game data
Initializing SDL 2.0.12
Using "KMSDRM" video driver
Searching for game data...
Using "STUFF.DAT" as main game data file.
Initializing OSD...
Game controllers:
  1. joysticks
Using joystick joysticks
Joystick 1 has 4 axes, 0 buttons, no hats, and no balls.
Initialized 96.0M cache
Setting video mode 640x480 (8-bpp fullscreen)
Refresh rate: 60.00Hz
videoSetGamma(): That operation is not supported
Initializing sound: SDL ALSA driver on ylm-audio, 10020000.audio-controller-jz4770-hifi 100200a4.audio-codec-0: 44.1 KHz stereo with 32 voices
videoSetGamma(): That operation is not supported
```

**Comment by CommonLoon102** [comment]
Try to set `r_vsync "0"` in `settings.cfg`.

**Comment by uncletrunks** [comment]
No dice there. Seems to be an issue with SDL2 on this specific platform right now. Attempts to build with SDL1 fail, gonna consider this a no-go until SDL2 is working properly on this thing. Thanks though.

**Comment by Jan200101** [comment]
it has to do with videoSetGamma() calling SDL_SetWindowGammaRamp and it returning a negative value.
It shouldn't cause any issues though, unless your platform doesn't set the screen gamma
