### ISSUE TITLE
Shadow Warrior Support

### ISSUE THREAD

**Issue by actraiser30** [nukeykt/NBlood#424]
Hello,great engine

will you add support for the Shadow Warrior game ??

thanks

**Comment by Hendricks266** [comment]
The NBlood Group is a downstream of EDuke32, which has Shadow Warrior support in the form of VoidSW. Grab a copy from: https://dukeworld.duke4.net/eduke32/synthesis/

**Comment by actraiser30** [comment]
Thanks but this is for windows i want to build it for linux

Στις Δευ, 23 Νοε 2020, 15:29 ο χρήστης Evan Ramos <notifications@github.com>
έγραψε:

**Comment by Hendricks266** [comment]
```
git clone https://voidpoint.io/terminx/eduke32.git
cd eduke32
make voidsw
```
