### ISSUE TITLE
Blood Fresh Supply

### ISSUE THREAD

**Issue by symbios24** [nukeykt/NBlood#427]
Hello is your engine support the blood fresh supply game and the One Unit Whole Blood ??
If yes how i can make the play?

Thanks

**Comment by Jan200101** [comment]
NBlood works with One Unit Whole Blood and Fresh Supply (though maybe it shouldn't)
it even tried to automatically tries to find Steam and Gog installations

**Comment by Dzierzan** [comment]
Why shouldn't? Fresh Supply uses the same OUWB files, but it's just without demo files.

@nukeykt you should probably close this ticket, as there's no issue.

**Comment by Jan200101** [comment]
It is just me being salty at the poor quality of Fresh Supply (though that is Atari's fault)
this should indeed be closed, it serves no purpose and is already explained elsewhere
