### ISSUE TITLE
strafing on gamepads reversed

### ISSUE THREAD

**Issue by Jan200101** [nukeykt/NBlood#43]
after testing using various controllers and two systems I've come to the conclusion that analog_strafing is reversed e.g. holding left goes right

**Comment by Jan200101** [comment]
after looking into it a bit more the issue seems to be here in [control.cpp#L599](https://github.com/nukeykt/NBlood/blob/master/source/mact/src/control.cpp#L599)

**Comment by nukeykt** [comment]
Should be fixed now, thanks for reporting and diagnosing bug
