### ISSUE TITLE
PCExhumed: moving the contents of psa.ini into setup.cfg

### ISSUE THREAD

**Issue by BSzili** [nukeykt/NBlood#431]
Currently settings are split between psa.ini and the .cfg files. I think the volumes, screen size and gamma could be moved into setup.cfg under the "FXVolume", "MusicVolume", "ScreenSize" and "ScreenGamma" entries. This would remove the need of keeping a separate psa.ini around.

**Comment by sirlemonhead** [comment]
Hey, that's done now :)
