### ISSUE TITLE
PCExhumed: no "Next_Weapon" and "Previous_Weapon" game functions

### ISSUE THREAD

**Issue by BSzili** [nukeykt/NBlood#433]
Currently there are no bindable game functions for switching to the next or previous weapon. These would come in handy for the mouse wheel and controllers.

**Comment by sirlemonhead** [comment]
Thanks, have added code for that now. Would you mind checking it if you get a chance? I have a bad habit of breaking things... :)

**Comment by BSzili** [comment]
Great! I gave it a quick test, and I couldn't find any issues, but I noticed something. The previous-/next weapon functions work even when the current weapon being fired, but the direct weapon switching only works when the weapon is idle. Maybe prev/next the weapon switching should be the same for consistency.

**Comment by sirlemonhead** [comment]
Yep you're right - it's the same in Duke3D too. I've changed that now so you can't next/prev when firing.

**Comment by BSzili** [comment]
Now it's perfect, thanks again!
