### ISSUE TITLE
Raspberry pi build error

### ISSUE THREAD

**Issue by retro24** [nukeykt/NBlood#435]
Hello,upon building in a raspberry pi 3 i got an error saying :

source/build/src/xxh_x86dispatch.c:44:4 error: #error "Dispatching is currently only supported on x86 and x86_64"
    error "Dispatching is currently only supported on x86 and x86_64"

source/build/src/xxh_x86dispatch.c:48:12: fatal error: immintrin.h: No such a file or directory
     include <immintrin.h> /* sse2 */

compilation terminated.
Failed building obj/build/xxh_x86dispatch.o from source/build/src/xxh_x86dispatch.c!
make *** [GNUmakefile:1524: obj/build/xxh_x86dispatch.o] Error 1

its strange 10 days ago i could build it succefully using the commit: b89e16f 
but now something probably changed/updated in the latest NBlood commit/s can you take a look at it and tell me how to fix it please ?

thanks

**Comment by Hendricks266** [comment]
Thanks for letting us know, it was a regression from upstream. We don't currently have any non-x86 CIs that would have caught this. Should be fixed in master.
