### ISSUE TITLE
PCExhumed: vertical panning is not affected by Z-velocity

### ISSUE THREAD

**Issue by BSzili** [nukeykt/NBlood#436]
Something about the movement in PCExhumed felt different, and playing it side by side with the DOS version, I noticed that in the original game vertical panning is affected by the player's Z-velocity. When moving up it looks a bit up, when falling it looks a bit down.  It can be seen when jumping or walking up/down stairs for example. This panning effect has the same limits as the player's looking up/down, so for example if you look all the way up then the upward momentum has no effect on the panning.

~~I checked and PowerSlaveGDX retains this behavior, but only when playing back the demos.~~
**edit:** I forgot that the vertical panning values are recorded in the demo file, so it's visible in PCExhumed too during the demo.

**Comment by BSzili** [comment]
Sorry, I should have checked this more carefully. This "lookspring" vertical panning works fine, but only when the mouse aiming is turned off, which makes perfect sense, as it could throw off your aim otherwise.

**Comment by sirlemonhead** [comment]
Ah! I had been trying to figure out what was wrong but wasn't having much luck! :D Glad everything is OK as is though!
