### ISSUE TITLE
"autoload" doesn't work correctly

### ISSUE THREAD

**Issue by Blackgrowl** [nukeykt/NBlood#437]
I have Blood Voxels, SmoothBlood and Custom Cultists mods, but only Voxels are loaded, SmoothBlood and Custom Cultists are ignored.

Can this be fixed?

**Comment by CommonLoon102** [comment]
It is not a bug. The autoload folder can only load one zip. You need to manually combine all the mods into one zip and merge their def files. This is an eduke32 limitation.

**Comment by Blackgrowl** [comment]
> 
> 
> It is not a bug. The autoload folder can only load one zip. You need to manually combine all the mods into one zip and merge their def files. This is an eduke32 limitation.

Thanks, tried it myself, all I had to do was merge as you said and only change one text file, "blood.def".
Would have liked to know this better, on a documentation or so, but I understand it's not top priority.
