### ISSUE TITLE
Very rare bug when Bloated Butcher don't throw axe projectile [NBlood r12109]

### ISSUE THREAD

**Issue by akjdssdfg** [nukeykt/NBlood#439]
https://clips.twitch.tv/ClumsyEnergeticSalsifyUWot clip from twitch., it's ultra rare, saw once in ~70 hours of using NBlood.

**Comment by carnivoroussociety** [comment]
This has been fixed in this PR https://github.com/nukeykt/NBlood/pull/509

**Comment by derek57** [comment]
I personally would like to review this specific bug as I'm having issues porting NBlood to a big-endian machine where the bloated butcher's knife (when he throws it) immediately get's vanished within the sprite of the bloated butcher itself (you can see the "dust" of the knife hitting himself). And that is always the case - not related to any specific map...

**Comment by Hendricks266** [comment]
@derek57 Could you record a demo where this occurs? Comparing the result when played back on LE and BE targets will help us pinpoint the difference.
