### ISSUE TITLE
Raspberry pi 4 build error

### ISSUE THREAD

**Issue by retro24** [nukeykt/NBlood#445]
Hello,upon building today in a raspberry pi 4 i got an error saying :

/usr/bin/ld: /tmp/ccfFHtYV.ltrans12.ltrans.o: in functions 'enet_time_get'_8
<artificial>:(.text+0xcc8): undefined reference to '__atomic_load_8
/usr/bin/ld: <artificial>:(.text+0xd24): undefined reference to '__atomic_compare_exchange_8'
collect2: error: ld returned 1 exit status
Failed linking nblood!
if the build options, enviroment, or system packages have changed, run make clean and try again
make: *** [GNUmakefile:1431: nblood] Error 1

again 2 weeks ago i could build it without any problem so something must changed again in the latest NBlood commits can you take a look at it and tell me how to fix it please ?

thanks

**Comment by Hendricks266** [comment]
Could you tell me the output of the command `uname -m`?

**Comment by symbios24** [comment]
Its aarch64 but i did not use 64bit raspian

**Comment by Hendricks266** [comment]
Does this fix it?

```diff
diff --git a/Common.mak b/Common.mak
index f13a2f4a3..9d9e50fb1 100644
--- a/Common.mak
+++ b/Common.mak
@@ -986,7 +986,7 @@ else ifeq ($(PLATFORM),WII)
     LIBS += -laesnd_tueidj -lfat -lwiiuse -lbte -lwiikeyboard -logc
 else ifeq ($(SUBPLATFORM),LINUX)
     LIBS += -lrt
-    ifneq ($(findstring armv6,$(IMPLICIT_ARCH))$(findstring armv7,$(IMPLICIT_ARCH)),)
+    ifneq ($(findstring armv6,$(IMPLICIT_ARCH))$(findstring armv7,$(IMPLICIT_ARCH))$(findstring aarch64,$(IMPLICIT_ARCH)),)
         LIBS += -latomic
     endif
 endif
```

**Comment by symbios24** [comment]
I have to edit the common.mak file or something?

**Comment by retro24** [comment]
ok i did it i changed this line in common.mak file and it compiled succefull
now when i run it with ./nblood i get a "bus error" message

**Comment by Hendricks266** [comment]
Try a clean recompile where you pass `USE_OPENGL=0` as a parameter to make.

**Comment by symbios24** [comment]
I did bus i still get this error on Raspberry pi 4 only
On Raspberry pi 3 works perfect

**Comment by Hendricks266** [comment]
Are you sure you it was a clean rebuild, e.g. `make clean && make USE_OPENGL=0`? I don't have an RPi4 to test.

**Comment by retro24** [comment]
yes im sure,is it the fact that im using raspbian lite ?
the rpi3 version works great under raspbian lite

**Comment by Hendricks266** [comment]
Does an AArch64 Raspbian Lite even exist? I'm not sure why `uname -m` would report aarch64, especially if you did not use a 64-bit OS. What about `gcc -dumpmachine`?

Did you install something that caused certain things to get overwritten with the wrong architecture?

**Comment by symbios24** [comment]
Its in berryboot for rpi4 the kernel is 64bit even if the os is 32bit it uses the 64bit kernel of berryboot

**Comment by arrowgent** [comment]
compiles fine on raspberry pi 4 - raspbian 32bit armhf

can you update title to show this was an arm64/aarch64 compile issue?
