### ISSUE TITLE
PCExhumed: Exhumed Demo

### ISSUE THREAD

**Issue by BSzili** [nukeykt/NBlood#446]
I noticed that the Exhumed Demo detection is currently disabled. Was there a compatibility issue? I tried enabling it, and it appears to work. The only difference I see is that the PowerSlave demo has 4 levels while Exhumed has only 3.

**Comment by sirlemonhead** [comment]
It wasn't quite finished - there isn't code to handle finishing the last level of the Exhumed demo and then exiting out after the splash screen. I just tested it again there by skipping through the levels (typing HOLLY then EXIT) and it tries to load into level 4 and glitches out.

I think at the time I just figured if anyone was going to play a free demo, they might as well get the Powerslave one which is more featured.

Did you play through all 3 levels of the Exhumed demo? does it just exit back to dos or is there any sort of "please buy the retail game!" credits? There's no level skip in that demo I'm aware of and I don't fancy playing through it to be honest!

**Comment by BSzili** [comment]
Thanks for the explanation! I discovered this because I had someone accidentally downloading the Exhumed demo, and telling to me that the game is broken. I'll play through the Exhumed demo to see how it ends and get back to this.

**Comment by BSzili** [comment]
This turned out to be different from what I expected. After level 1, the game will unceremoniously exit to DOS with the usual "Thanks for playing Exhumed Demo!" message, the same thing happens when I try to load the save game. I edited savegamea.sav, and Level 3 actually loads, upon finishing the map screen appears to continue from Level 4, but if I try to enter it exits as lev4.map not present in stuff.dat. This suggests that the Exhumed demo was hardcoded to have only one playable level despite the 3 map files in stuff.dat.
I think PCExhumed could make all 3 levels playable and then show the advert text after finishing them.
