### ISSUE TITLE
Error compiling on macOS 

### ISSUE THREAD

**Issue by heatershield** [nukeykt/NBlood#448]
Not really sure what's going on here. Also tried building eduke32 to see if it was some dependencies I was missing, worked fine. Regardless, here is the error: 

> Built object obj/build/rev.o 
> 
> Linked nblood 
> Building: /Library/Developer/CommandLineTools/usr/bin/make  -s
> -rwxr-xr-x  1 nothanks  staff  2866392 Feb  2 18:18 nblood
> error: unable to open output file 'obj/rr/n64/reality.o': 'No such file or
>       directory'
> 1 error generated.
> Failed building obj/rr/n64/reality.o from source/rr/src/n64/reality.cpp!
> make: *** [obj/rr/n64/reality.o] Error 1

**Comment by Hendricks266** [comment]
Use gmake, not make.
