### ISSUE TITLE
gargoyles cant melee when a flare is attached

### ISSUE THREAD

**Issue by M00nBr1ght** [nukeykt/NBlood#449]
when lit by a flare, gargoyles try repeatedly to attack but are unable to, the animation for melee starts and the sound effect plays but almost immediately starts again causing the sound effect to play near constantly and no damage actually being delt.

**Comment by Hendricks266** [comment]
Is this present in the original game under DOSBox?

**Comment by M00nBr1ght** [comment]
closing this, sorry misremembered it is in dosblood
