### ISSUE TITLE
Spray Can HUGE damage scale after game restart and loading a savegame.

### ISSUE THREAD

**Issue by Viscont23** [nukeykt/NBlood#451]
I have stumbled upon a Spray Can bug while playing through NBlood.
The exact way to reproduce:
1) Get a spray can and save the game;
2) Exit to desktop.
3) Start the game.
4) Load your game.
After completing these four steps the Spray Can **seems to deal MUCH more damage** than it is normally supposed to. The glitch fixes itself once the current level is finished.
This **DOES NOT happen in the DOS version**, so I presume this is a Nblood-exclusive bug.

https://user-images.githubusercontent.com/78764887/107287476-0f92e300-6a73-11eb-8cf8-70832a2fe59d.mp4

https://user-images.githubusercontent.com/78764887/107287494-16215a80-6a73-11eb-9c5d-713ba29ecd6c.mp4

**Comment by carnivoroussociety** [comment]
This has been fixed in this PR https://github.com/nukeykt/NBlood/pull/509
