### ISSUE TITLE
Bats can crash the game

### ISSUE THREAD

**Issue by CommonLoon102** [nukeykt/NBlood#454]
From Discord:

> Okay, I want to ask about this, but I keep forgetting, and now is the time
> I encountered this twice.
> How to reproduce: save near a bat
> load save
> https://cdn.discordapp.com/attachments/563824469982969896/811229610746183700/unknown.png
> I encountered it twice while streaming, i don't have the old clip, i might have the newer one still.
> Last time i "fixed it" by commenting out the assertion. I really didn't want to replay the episode, because i was close to the end of the game

Could we just convert to assert into an if, so the bat won't attack if the target is invalid? Instead of crashing the game.

**Comment by fhomolka** [comment]
Hi, I'm the guy who wrote the message.
Bats don't crash the game, the execution pauses because of the failed assertion.
Pressing "OK" just causes the same assertion to fail again. I haven't actually tried for how much the assertion fails in a row.
