### ISSUE TITLE
Rednukem can't find duke64 file on raspberry pi build

### ISSUE THREAD

**Issue by TheOneAnthony** [nukeykt/NBlood#457]
After building the port, i found that while it can recognize all the other games. it refuses to acknowledge the existence of the game rom for duke nukem 64. this same file works fine on windows. i even tried to specify the exact rom with the -GRP parameter at launch and also tried renaming the rom while launching. when i do that it just said the renamed file doesn't exist either.

ssh command prompt:
---------------------------------------------------------------------------------------------------------------------------------------------
 ./rednukem -GRP /home/NBlood/duke.z64
Rednukem r12159-e28976b68
Built Feb 23 2021 16:22:44, GCC 6.3.0, 32-bit
Application parameters: -GRP /home/NBlood/duke.z64
Using /home/pi/NBlood/ for game data
Using /home/pi/.config/rednukem/ for game data
Initializing SDL 2.0.10
Using "x11" video driver
Searching for game data...
Warning: could not find main data file "Duke Nukem 64 (U) [!].z64"!
Warning: could not find main data file "Duke Nukem 64 (U) [!].z64"!
Could not find file "/home/pi/NBlood/duke.z64".
Required game data was not found.  A valid copy of "Duke Nukem 64 (U) [!].z64" or other compatible data is needed to run EDuke32.

You must copy "Duke Nukem 64 (U) [!].z64" to your game directory before continuing!
-----------------------------------------------------------------------------------------------------------------------------------------------
the same folder also has Duke Nukem 64 (U) [!].z64 in it as well as the rename. both dont work

**Comment by Hendricks266** [comment]
- `-GRP` is not a valid parameter
- the ports do not accept absolute paths, only relative ones inside the virtual filesystem established with paths listed in the log as "Using ... for game data"
- your path is wrong, `/home/NBlood/` is not valid unless you have a user named NBlood (and not one named pi as the log shows elsewhere

Move duke.z64 to `/home/pi/.config/rednukem/` and launch without any parameters.

**Comment by TheOneAnthony** [comment]
the /home/NBlood was a typo on my part. ive tried that before.  but even after doing as you say it still won't recognize both this and the default rom name for the file

**Comment by TheOneAnthony** [comment]
ok, this is odd. when launching through xinit. it shows the launcher, but even selecting duke 64 and clicking start, still results in it saying its not found even though the launcher can see it

**Comment by nukeykt** [comment]
Do you use opengl enabled builds? DN64 renderer requires it. Performance most likely going to be bad though, because pi does not support opengl natively.

**Comment by TheOneAnthony** [comment]
well it worked.. you weren't kidding about the slowdown though.
