### ISSUE TITLE
Game freeze with Life Leech and/or Cerberus

### ISSUE THREAD

**Issue by Buntar0** [nukeykt/NBlood#46]
I've found a reproducable game freezing bug in E4M8: Hall of the Epiphany. Here's how to reproduce it:

Before facing the Cerberus, place a Life Leech staff in turret mode (weapon 9, secondary fire)  just around the corner so it shoots at the Cerberus, then go back a few steps, see screenshot for details - I've placed the staff where the crosshair is pointing to. 
Ideally The cerberus will try to attack but get stuck and constantly fired at by the life leech in turret mode. After a while, likely when the cerberus loses one head, this message comes up: 

Assertion failed: nTarget >= 0 && nTarget < kMaxSprites in file source/blood/src/ai.cpp at line 854

Files: 
- savegame to reprodce the bug
- screenshot of the message
- screenshot where to place the staff to easily reprodce the bug
[game0000.sav.zip](https://github.com/nukeykt/NBlood/files/3051398/game0000.sav.zip)
![bug1](https://user-images.githubusercontent.com/15014701/55681607-87989b00-5928-11e9-9385-d5d17852382e.png)
![bug1a](https://user-images.githubusercontent.com/15014701/55681611-8e271280-5928-11e9-8e3e-49dba27cddcf.png)

**Comment by nukeykt** [comment]
Tried to reproduce bug, but no success. I remember i've fixed similar crash some time ago. Which version do you run? Development version or v1.0 release?

**Comment by Buntar0** [comment]
v1.0 on Linux Mint Cinnamon 19.1

**Comment by nukeykt** [comment]
Try development version

**Comment by Buntar0** [comment]
Just compiled & tried to reproduce it: 
-3 times on development version (jumped there via cheat since the save game has become incompatible) --> no problems
-3 times on v1.0 just to make sure --> freezed 3 times

I think this is fixed, thanks!
