### ISSUE TITLE
Cant do / in console

### ISSUE THREAD

**Issue by user85475485** [nukeykt/NBlood#464]
Is there a way to change the keyboard layout in config?My Layout is set correctly in Windows but @ is on shift 2 in nblood, so its US my current layout is DE.I think it definitely worked before

Thx in advance

**Comment by CommonLoon102** [comment]
Try pressing the hyphen.

**Comment by user85475485** [comment]
Tried that too, hyphen just does - for me :/ tried pretty much every key

**Comment by user85475485** [comment]
> 
> 
> Try pressing the hyphen.

I found out: 
![Capture](https://user-images.githubusercontent.com/64977518/111393476-1f789500-86b9-11eb-8794-36908c68e303.PNG)
 when i press T i can do / in the chat thing when pressing hyphen, still not in console tho.Also at the Bottom it says it loaded a Us Keyboard

**Comment by user85475485** [comment]
On other Applications the keyboard layout is right

**Comment by arrowgent** [comment]
english & US layout
linux
latest master compile

/ - \ all work correctly for me.

what version are you using?

seems to be a localization issue with the input
