### ISSUE TITLE
NBlood Controls

### ISSUE THREAD

**Issue by ghost** [nukeykt/NBlood#47]
I cleared a few controls when I First ever used NBlood and and when I started it up again today it had the bindings that I cleared/deleted 
https://youtu.be/6EjgEx3fn6s

**Comment by Jan200101** [comment]
how are you exiting NBlood?
The configurations aren't saved unless you fully quit the game using the QUIT option in the menu

**Comment by CommonLoon102** [comment]
Cannot reproduce in master, should be closed.
