### ISSUE TITLE
Blood: Process hangs after quit on Fedora 34

### ISSUE THREAD

**Issue by CommonLoon102** [nukeykt/NBlood#477]
I have to kill the process.
The `atexit()` fix doesn't fix this.

**Comment by Jan200101** [comment]
can't recreate on 21cea950ab6faee2335137876cdb13e34a2260cd using Fedora 34

**Comment by CommonLoon102** [comment]
The issue is with VirtualBox and with its sound handling. I'm having sound issues in general. The game is freezing when SDL is trying to close the audio device. I'm closing this since the issue is with VirtualBox, not NBlood.
