### ISSUE TITLE
Autoload doesn't seem to be loading content.

### ISSUE THREAD

**Issue by ghost** [nukeykt/NBlood#480]
I can only load the single mod I use (3D skyboxes) through selecting a custom content folder and unticking autoload, despite everything setup correctly for autoload use. This did not happen on older versions of the software.

Tested on version rr12196.

**Comment by user85475485** [comment]
same for me. Im on Ubuntu 21.04

**Comment by CommonLoon102** [comment]
Maybe give raze a try, it is better in mod loading:
https://github.com/coelckers/Raze

**Comment by user85475485** [comment]
lmaooooo
