### ISSUE TITLE
How can I keep NBlood settings/saves in seperate user folders (Windows)?

### ISSUE THREAD

**Issue by dankcuddlybear** [nukeykt/NBlood#482]
I have a Windows 10 gaming PC in the living room which is shared between family members. I have an admin account while everybody else has a standard account. I have NBlood v1.01 inside directory C:\PROGRAMS\nblood alongside the Blood game files, settings and saves. The problem is that standard users cannot save the game because they don't have write permissions for the C:\PROGRAMS directory. So I thought each user should instead keep their settings/saves in their own folders, like %USERPROFILE%\Saved Games\nblood or %APPDATA%\nblood.

I tried launching nblood with the following command line arguments: nblood.exe -nosetup -ini blood.ini -cfg %USERPROFILE%\Saved Games\nblood\nblood.cfg -game_dir %USERPROFILE%\Saved Games\nblood

However, it didn't work as expected. The game demo did not load (which is no big deal). Most options were not saved (except for the renderer) and I could create save games but not load them.

Can somebody help me with this? I'm not familiar with programming or C++ so I can't fix bugs by myself.

**Comment by Jan200101** [comment]
https://github.com/nukeykt/NBlood/blob/25d08f8abb13af8617df194ecf9bb6e6b94e8773/source/blood/src/common.cpp#L155-L165

with Bgethomedir being defined here
https://github.com/nukeykt/NBlood/blob/82028271de3e84df064f173da5295313a2de9daa/source/build/src/compat.cpp#L80

someone correct me if I am wrong, but from what I am reading it seems to saving in appdata when it can
https://github.com/nukeykt/NBlood/blob/82028271de3e84df064f173da5295313a2de9daa/source/build/src/compat.cpp#L98-L107

**Comment by dankcuddlybear** [comment]
That doesn't help at all. I do not understand code. Besides, it looks like it applies to Linux only as Windows users don't have a .config directory.

**Comment by sirlemonhead** [comment]
Jan200101 is correct, but I think what you need to do is create a file called 'user_profiles_enabled' (with no extension) and place it where nblood.exe is, and it should start using the AppData\Roaming\NBlood folder

**Comment by dankcuddlybear** [comment]
Thanks! Works perfectly now.
