### ISSUE TITLE
[Duke Nukem 64] No gamepad support?

### ISSUE THREAD

**Issue by Tasosgemah** [nukeykt/NBlood#486]
My gamepad is not recognized when i select "all devices" in the launcher and there are no gamepad options in the menu.

Is this normal?

**Comment by CommonLoon102** [comment]
Yes, it is normal, there is no gamepad support.

**Comment by Tasosgemah** [comment]
Any chance will be implemented in the future?

**Comment by CommonLoon102** [comment]
Sorry, it is very unlikely.

**Comment by skynettx** [comment]
@Tasosgemah you can test the rednukem-gamepad branch. Duke Nukem 64 should be run fine
with gamepad.

**Comment by Tasosgemah** [comment]
> rednukem-gamepad branch

Could you point me to the right direction? Not sure what to download from a quick google search

**Comment by skynettx** [comment]
Install Git on your system.
Open up shell or terminal, change or create directory to clone the repository in a folder of your choice. Then type in:
`git clone --branch rednukem-gamepad https://github.com/nukeykt/NBlood.git`

**Comment by sirlemonhead** [comment]
OK the gamepad support should be 'live' now - download from https://lerppu.net/wannabethesis/

Anything wrong or missing, please create a new issue :)
