### ISSUE TITLE
NBlood hangs on launch (shows empty window)

### ISSUE THREAD

**Issue by FridgeRacer** [nukeykt/NBlood#489]
I've compiled NBlood as per [EDuke32 instructions](https://wiki.eduke32.com/wiki/Building_EDuke32_on_Linux) and made sure I launch NBlood with the proper game files present. I'm getting the game files from GOG, and it is the 1.21 version.

To build, I first installed all the dependencies and executed "make blood", there were some errors when building, although I'm not entirely sure if they matter much.

Either way, here's the build log just in case: https://paste.ubuntu.com/p/NFdbTzYn57/

 nblood.log writes the following and nothing else:
```
NBlood r12372-fa990acc9
Built Jul 20 2021 04:19:52, GCC 11.1.0, 64-bit 
Using /home/ridge/Games/blood/data/ for game data
Using /home/ridge/.config/nblood/ for game data
```

![Blank NBlood window accompanied by the aforementioned terminal output](https://i.imgur.com/3oN38m2.png)

Running Manjaro Linux, Kernel 5.13.1-3, Nvidia Driver 470.42.01

**Comment by CommonLoon102** [comment]
>  there were some errors when building, although I'm not entirely sure if they matter much.
There were no errors, those were just warnings, they don't matter at all.

Try building an older version, this should work:
https://github.com/nukeykt/NBlood/commit/a1689a4f5275a416448880ab64433a3af16091ec

**Comment by Hendricks266** [comment]
@FridgeRacer Could you use GDB to get a backtrace of the hang?

```bash
$ make clean && make blood RELEASE=0 -j4
$ gdb ./nblood
(gdb) r
```

When the hang occurs, press Ctrl+C in the GDB window. Then:

```bash
(gdb) thread apply all bt
```

**Comment by FridgeRacer** [comment]
> There were no errors, those were just warnings, they don't matter at all.
> 
> Try building an older version, this should work:
> [a1689a4](https://github.com/nukeykt/NBlood/commit/a1689a4f5275a416448880ab64433a3af16091ec)

Thanks for clearing that up, I had a hunch but couldn't be confident about my assumption.
Unfortunately [a1689a4](https://github.com/nukeykt/NBlood/commit/a1689a4f5275a416448880ab64433a3af16091ec) had the same issue on my machine, but I appreciate the suggestion nonetheless. Let's see if the following has anything interesting...

> @FridgeRacer Could you use GDB to get a backtrace of the hang?

@Hendricks266 
Certainly, here it is! Hope this helps.
https://paste.ubuntu.com/p/pg4CM36pCx/

**Comment by Hendricks266** [comment]
> > @FridgeRacer Could you use GDB to get a backtrace of the hang?
> 
> @Hendricks266
> Certainly, here it is! Hope this helps.
> https://paste.ubuntu.com/p/pg4CM36pCx/

Thanks for the quick response! I see some issues in the code referenced by your backtrace, and [others have reported the same issue](https://voidpoint.io/terminx/eduke32/-/issues/148). Could you attach your `~/.steam/steam/steamapps/libraryfolders.vdf` file here? Steam must have changed something about this file's contents that exposes the issue. I have some fixes but need to test them on a file with the problem before I push.

**Comment by FridgeRacer** [comment]
> Could you attach your `~/.steam/steam/steamapps/libraryfolders.vdf` file here? Steam must have changed something about this file's contents that exposes the issue. I have some fixes but need to test them on a file with the problem before I push.

Sure! I very very rarely use Steam and currently, I have nothing installed via Steam anymore, so I had a peek in this file and it points to a folder that no longer exists. Could that be problematic?

I renamed that file to "libraryfolders.bak" and now NBlood works! 😄
It still refuses to work if the folder in "libraryfolders.vdf" simply exists with no contents, so as long as it can't find "libraryfolders.vdf" it's all good.
Thank you very kindly! Time to make some cultists pay.

Keeping the upload here just in case you wanna look at it anyways:
[libraryfolders.zip](https://github.com/nukeykt/NBlood/files/6850750/libraryfolders.zip)

**Comment by Hendricks266** [comment]
Thanks for sharing the file! I've pushed a fix.
