### ISSUE TITLE
NBlood: The delirium effect is too fast

### ISSUE THREAD

**Issue by BSzili** [nukeykt/NBlood#494]
Compared to the DOS version the delirium shake is too fast. The duration is the same, but it seems to do two full cycles instead of just one.

**Comment by CommonLoon102** [comment]
What about the software renderer? It should be the same in that case. In polymost it is using an OpenGL solution, basically completely re-implemented from scratch. It just looks similar.

**Comment by BSzili** [comment]
The software renderer and Polymost are the same in this regard, they "play" the delirium effect twice. This is probably a timing issue that affects both renderers.

**Comment by sirlemonhead** [comment]
Should be fixed in PR #541 if you'd like to retest? Thanks!

**Comment by BSzili** [comment]
Absolutely, now the delirium looks like it does in the DOS version.

**Comment by sirlemonhead** [comment]
Perfect, thanks everyone!
