### ISSUE TITLE
NBlood - Black Status Bar Edges

### ISSUE THREAD

**Issue by Trashlyn** [nukeykt/NBlood#506]
When saving or loading a save in NBlood using the full status bar (the one with the gargoyles that has stone texturing to the left and right of the respective gargoyles to fit widescreen monitors), the status bar past the gargoyles will turn black. The issue is resolved by pausing and unpausing, which will restore the texture. This has no effect on gameplay, but will occur every time you save and reload a previously made save.

**Comment by Trashlyn** [comment]
I've also recorded a quick demonstration of the issue, github be willing it should be attached to this post, however it isn't displaying, I can upload this to youtube and link it through this comment via edit.

**Comment by OpenRift412** [comment]
Giving this a bump, since there's been a fix around for a while. Also, it'd be nice if the edge texture was scaled to match the status bar's resolution, for consistency's sake.
