### ISSUE TITLE
[PCExhumed/Rednukem/VoidSW] Micro Stuttering with refresh rate > 60hz (PCExhumed/Rednukem SOLVED)

### ISSUE THREAD

**Issue by Kappa971** [nukeykt/NBlood#522]
As described in ticket #468 (closed because it became too confusing), with monitors with a refresh rate higher than 60hz (tested with 144hz freesync monitor but I guess it also happens without freesync), PCExhumed and Rednukem have micro stuttering. VoidSW also suffers from framerate issues (doesn't look smooth despite fixed 144fps), but this is still in beta. In the old ticket, it is said that some changes have probably been made to Eduke32, which have probably been ported to Nblood but not to PCExhumed and Rednukem. It happens in both Windows and Linux. Raze runs smoothly at 144fps/144hz.

**Comment by CommonLoon102** [comment]
Wow, you put a lot of effort into this.
I checked the NBlood repo for Blood, here are the commits I think have changed the microstuttering case:
442aefc6
a189828b

You can build and test after and before these commits and see if these are really the ones.

**Comment by CommonLoon102** [comment]
There is no build for 442aefc on lerppu.
But you can find the a189828 one.

This is for a189828:
https://lerppu.net/wannabethesis/nblood/20200527-11613/nblood_win64_20200527-11613.zip

And this is the one right before it:
https://lerppu.net/wannabethesis/nblood/20200527-11612/nblood_win64_20200527-11612.zip

You can check if there is microstuttering change between the two.

You need to compile 442aefc and the one before it yourself though.

**Comment by CommonLoon102** [comment]
The changelog for EDuke32 r9202 says:
`Engine: fix sprite sorting issue that caused broken voxel rendering in polymost`
It is by nukey who also had this change in NBlood. Maybe this is causing the stuttering?
It is a small change made in NBlood, and then it was backported to eDuke32.
Here is the commit for NBlood: 888bda5c

There is no build on lerppu which only contains this change, so you would need to build yourself (what you are unable to do).
This sprite sorting stuff is together with a lot of other changes from upstream in release r11612 (what you have already tried). So maybe try one before it, the r11576 one.
It is here: https://lerppu.net/wannabethesis/nblood/20200526-11576/nblood_win64_20200526-11576.zip

**Comment by CommonLoon102** [comment]
I made a huge mistake. Somehow I checked the wrong changelog.
The changelog for r9202 is here: https://dukeworld.com/eduke32/synthesis/20200726-9202-edac43bc4/ChangeLog.txt

And in it, this is very suspicious:

>     Duke3d: add an additional layer of camera vec3_t position smoothing across frames
>     
>     This is intended to mask a slight jitter that occurs when strafing and turning at the same time as a result of turning being decoupled from movement.

I'll have a look in this.

**Comment by CommonLoon102** [comment]
It (a359877b) is completely Duke Nukem 3D related, and it was reverted in 600ce46a.

**Comment by CommonLoon102** [comment]
I would recommend using the original git repo, the commit in question is here:
https://voidpoint.io/terminx/eduke32/-/commit/a359877b2a01182f06e1db910c660a654a0727a2

Clone the repo with VS and then open the solution at \platform\Windows\eduke32.sln. Right click on master branch -> view history -> search for a359877b2, see the commit below it (ca76197c as you mentioned), right click, new branch, build, run, test. Then do the same with a359877b2.

**Comment by Kappa971** [comment]
I found this commit https://github.com/nukeykt/NBlood/commit/0f928a1fd5eb23e37c48d7eb547a176ff9cf6eab and in EDuke32 source/duke3d/src/game.h it has been changed like this:

![duke3d](https://user-images.githubusercontent.com/62349018/137331999-76fa3834-e0b8-4878-9b68-510e85686967.png)

In Rednukem (source/rr/src/game.h) it is like this:

![rr](https://user-images.githubusercontent.com/62349018/137332810-ca7c1ff2-0578-4efa-a7df-0242c086b01c.png)

**Comment by CommonLoon102** [comment]
It is not a simple issue at all. The eDuke32 dev team was struggling with stuttering issues in whole July.
https://voidpoint.io/terminx/eduke32/-/issues/100
https://voidpoint.io/terminx/eduke32/-/issues/161
https://voidpoint.io/terminx/eduke32/-/issues/174

They fixed it first, it thought to be OK, but for some it wasn't, then they fixed it in some other way. Then reverted something and re-fixed. I cannot really follow it anymore, there are a lot of references to commits and everything in the mentioned issues. You can have your fun time there but I think this is still an open issue.

**Comment by CommonLoon102** [comment]
> Use 40 for the 3rd parameter, SW has a 40Hz timer

@mjr4077au What about PCExhumed? Is 30 OK there?

**Comment by Kappa971** [comment]
I apologize if I still haven't closed the problem, but unfortunately in the EDuke32 GitLab repository I see that things are working very slowly. There are fixes waiting to be merged for a year! Now I don't want to complain to you that you have nothing to do with it, but this is about replacing a line of code, I would do it so I would close the problem today but I don't think I have permission.

**Comment by CommonLoon102** [comment]
You can learn git basics and open a Merge Request for your issue. There you can change that single line yourself and that would speed up the process. Then the maintainers would just need to click "Merge" and that's it.

You need to fork the eduke32 repo, then create a new branch from the master branch (name it `sw-stutter-fix`). Change that one line and push your changes. Then you can open a Merge Request for those changes. You can google the details.

**Comment by Kappa971** [comment]
> You can learn git basics and open a Merge Request for your issue. There you can change that single line yourself and that would speed up the process. Then the maintainers would just need to click "Merge" and that's it.
> 
> You need to fork the eduke32 repo, then create a new branch from the master branch (name it `sw-stutter-fix`). Change that one line and push your changes. Then you can open a Merge Request for those changes. You can google the details.
> 
> You can do everything above with the GitLab web interface, no need to install anything onto your PC.

I will do a Google search, but I imagined that the maintainers would have implemented it immediately as the fix is ready and doesn't require massive changes.
I'll try to do what you told me, but probably even done all this, it will still remain in the "Merge request" list for quite some time (some I've seen have been there for a year). Anyway thanks for the answer, always very helpful :)

**Comment by Hendricks266** [comment]
I've seen your report, here and on the GitLab. I'll get to it, I need to fix the mouse sensitivity as well. My attention has been elsewhere recently.

**Comment by Kappa971** [comment]
I created a merge request to fix the problem. I hope I have done everything correctly. @Hendricks266 can you check? https://voidpoint.io/terminx/eduke32/-/merge_requests/176

**Comment by TerminX** [comment]
I checked the merge request and something seems to be wrong with it that blocks it from rebasing against the current contents of the master branch. I don't know what could be wrong with it that would make that happen, being that the change is only one line. Regardless, I created a local commit for it and will manually push it to master later. Thanks for the contribution.

**Comment by Kappa971** [comment]
> I checked the merge request and something seems to be wrong with it that blocks it from rebasing against the current contents of the master branch. I don't know what could be wrong with it that would make that happen, being that the change is only one line. Regardless, I created a local commit for it and will manually push it to master later. Thanks for the contribution.

I helped find the problem, @CommonLoon102 and @mjr4077au created the fix. I don't know what's wrong with the merge request (never done this before), anyway thank you for creating a local commit. When this is applied, I will close all issues

**Comment by Kappa971** [comment]
Problem solved, thanks to all.
