### ISSUE TITLE
PCExhumed: Messages don't show correctly in some aspect ratio

### ISSUE THREAD

**Issue by CommonLoon102** [nukeykt/NBlood#523]
In 1280x1024 windowed mode (OpenGL) when I pick up "Life" it writes "Khed" on the top left corner. Actually, it is not just life but anything what is written there is gibberish. If I play in 1920x1080 in fullscreen, it is working fine.

**Comment by CommonLoon102** [comment]
It seems for me that the letters are cropped out from a larger tile which contains all the letters.

**Comment by sirlemonhead** [comment]
Fix just in for this, in commit e9d9c4c. Provided by Nukey :)
