### ISSUE TITLE
Rednukem: WWII GI Crashes on Level Load

### ISSUE THREAD

**Issue by OpenRift412** [nukeykt/NBlood#529]
Whenever I try to load World War II GI in Rednukem, the game just crashes. Mind you, this never happens with NAM or any other supported game, just WWII GI.

**Comment by mjr4077au** [comment]
Do you have a log or any screenshots or anything to help the devs out?

**Comment by nukeykt** [comment]
Fixed in cc8d57ee5d6ac8a3c3f400501df25892cb9db6b1
