### ISSUE TITLE
Slope sprites do not respect the y-flip bit

### ISSUE THREAD

**Issue by coelckers** [nukeykt/NBlood#537]
It looks like rendering slope sprite just ignores the y-flip bit (8).
Unfortunately I cannot provide a test map, because I found the issue with a map I got privately for testing.
Having this bit on or off does not seem to make the slightest difference when using both Polymost or Classic renderer.

I only noticed the discrepancy in Raze's new renderer which is using the same standard function for retrieving the coordinates that Polymost uses for regular slope sprites, so this function actually did flip the sprite.

See here: 

https://github.com/coelckers/Raze/commit/9680ff1863c23dd690732f8b0d943e16f64ca031

**Comment by StrikerMan780** [comment]
Intended behaviour. Flip Y flips the side a 1-sided floor-aligned sprite will render. To flip it visually, you'll want to rotate the opposite way and invert the slope. Works the same was as a non-sloped floor-aligned sprite (only flips along the X axis. Flip Y controls which side of a one-sided floor-aligned sprite draws.)
