### ISSUE TITLE
turning right prevents attacks

### ISSUE THREAD

**Issue by dyrverE** [nukeykt/NBlood#54]
Version: NBlood v1.01-23-g527f6aa
Arch: linux_amd64

Standing in one spot, rotating to the right and trying to attack, but the pitchfork doesn't attack anymore. Works fine while rotating left however.

**Comment by Jan200101** [comment]
can't replicate

**Comment by dyrverE** [comment]
Seems to happen pretty frequently in my monitors max res, 1920x1080, but isolated mainly to running both Nblood and Eduke32 with fullscreen on regardless. It's weird. I've tested other SDL2 games but not hit this on them.
