### ISSUE TITLE
Blood: When floor is over floor, shadows of higher floor are on lower floor

### ISSUE THREAD

**Issue by zZeck** [nukeykt/NBlood#561]
Seen in e2m5 the haunting
![e2m5ShadowIssue](https://user-images.githubusercontent.com/18518874/151676102-606b30cb-7537-451d-9cc1-d34f5e1e961c.png)

**Comment by zZeck** [comment]
This does happen in the original exe as well.
![dosShadow](https://user-images.githubusercontent.com/18518874/151683261-a969e9dd-f74e-4687-b46d-fbad095cfc25.png)

**Comment by zZeck** [comment]
e2m1
Shadow through box.
![shadowThroughBox](https://user-images.githubusercontent.com/18518874/151694416-2505cf15-e488-4a1b-bcf3-0e19c47cf14c.png)
Shadow disappears completely when you jump beyond the room.
![shadowVanishWhenLeaveRoom](https://user-images.githubusercontent.com/18518874/151694421-9a4cf8cf-ea25-45e6-a503-c7702a8021a8.png)

**Comment by carnivoroussociety** [comment]
I believe these are simply fake floors used by maps - it might be possible to detect these using hitscan collision for shadow rendering.

**Comment by CommonLoon102** [comment]
RTX, when?
