### ISSUE TITLE
Ceiling scrolling reversed

### ISSUE THREAD

**Issue by Bloody-Tom** [nukeykt/NBlood#569]
When a ceiling texture is scrolling an it's not made "relative" in mapedit, the scrolling is reversed. In DOS ist stays in the direction its supposed to scroll. I edited E2M6 for that purpose (in mapedit, not in xmapedit (to exclude a potential problem with xmapedit))

Take  a look:
![NBlood 2022-02-11 04-52-09](https://user-images.githubusercontent.com/99460972/153535933-c2f385c9-3c3c-410e-9a5b-4e2ee2e0fd18.gif)

And for reference here the same map in Dosbox (sorry for the crappy framerate):
![blood_000](https://user-images.githubusercontent.com/99460972/153539995-eac4e88c-67ac-42de-8ce5-fc08fc6cf957.gif)

**Comment by carnivoroussociety** [comment]
Hi, can you upload the modified level?

**Comment by Bloody-Tom** [comment]
Here you are:
[https://www.mediafire.com/file/pm9wedjfqvnbm93/TEST.MAP/file](url)

**Comment by carnivoroussociety** [comment]
Thanks, I've submitted a PR that fixes this.

**Comment by sirlemonhead** [comment]
Thanks for reporting! Fixed in PR #570
