### ISSUE TITLE
sprites misbehave and other problems

### ISSUE THREAD

**Issue by revelator** [nukeykt/NBlood#57]
Hello. First good job on the port :).

Im having a bit of a snag but i dont see my problem specifically mentioned by anyone else, so im not sure if the problem is on my end.

Sprites for flames are misbehaving, sometimes drawing as green haze.
Heart sprites flicker.
Some wall textures seem to not draw correctly (smearing ?, looks like those textures only draw as tilted lines).

I used the gog version of one unit whole blood as the base, is there any thing different with that version besides the bundled dosbox ?.

If i use the high res pack for BloodGDX the viewport goes all bonkers.

Skyboxes have no top tile (just a large black square when looking up).

**Comment by Jan200101** [comment]
I tried replicating those issues with the one unit whole blood pack on v1.0, v1.01 and master to no avail

the skybox not having a top tile seems to be a issue with the polymost renderer

**Comment by revelator** [comment]
just noticed the 1.01 release does not exhibit these problems,
only if i build it myself from git sources.

Im using Msys2/MinGW64 for building as i dont have msvc 2019, but i sure hope the compiler used aint 
the problem here, since i can build other game engines with it that have no problem, so hunting down what might cause it to misbehave will be a nasty job.

**Comment by Jan200101** [comment]
I have just compiled NBlood using MinGW64 myself and I am experiencing the same issues you have been

For now I suggest using the v1.01 release or compiling using msvc 2019

**Comment by revelator** [comment]
Ouch was afraid of that, i do not have access to msvc 2019 so im stuck it seems :(

**Comment by revelator** [comment]
further info if needed for future reference, i use gcc-7.4.0 binutils-2.29. Latest is gcc-8.3 but that version 
breaks a lot of stuff and has problems with gnat so i stuck with the last known fully working version.

Tried opening the project in msvc 2017 and adjusting windows api's for that version but im running into a xaml error in masm in build, so for the moment im unable to build a working version.

**Comment by nukeykt** [comment]
Does 294b884 fix these issues?

**Comment by revelator** [comment]
Ill give it a go in a sec, recently had a bypass operated in for a kidneystone, so i been having some trouble sitting up.

**Comment by revelator** [comment]
hmm ok this one fixes the viewport going crazy with the hd packs but now i have a partial second viewport at the top of the screen where the dripping blood in bloods menu is. 

Also some textures are upscaled like crazy in the menu with the hd pack (bottom hud fills the entire screen) this also was a problem before the patch.

Still getting smearing on some textures to.

**Comment by revelator** [comment]
Hmm i got visual studio 2019 community now but the masm error still prevails (xaml error).
This error seems to be arecurring issue with some later msvc versions, unfortunatly there is no 100% working fix and it seems to be rather stubborn on my PC since none of the workarounds work for me.

I do have a working clang for building on windows, but im having trouble building nblood with it since it seems the makefiles are not setup for windows clang builds.

**Comment by Jan200101** [comment]
Building using clang on windows should be possible
please see if the instructions in the [EDuke32 Wiki](https://wiki.eduke32.com/wiki/Building_EDuke32_on_Windows#clang) work

**Comment by revelator** [comment]
finally managed to build nblood with visual studio.
But it turns out that the problems are the exact same with the visual studio 2019 compiler as with mingw-w64 :S skyboxes are broken in the polymer renderer (all black), some sprites still misbehave to, but atleast not as much as before. And i still get broken textures on some walls.
The funny thing though is that everything works fine with the classic renderer, so it seems these problems are caused by something in the polymer renderer code. 

Unfortunatly i have no previous experience with this engine else i might try to fix stuff and submit some patches, but i just recently discovered where in the code the renderer was located and i still need to figure out the interactions between the client code and that.

**Comment by revelator** [comment]
Ok it seems this odd behaviour has nothing to do with the compiler used as i get the same result in clang msvc 2019 and mingw64. It might be something with my gfx card nblood does not like (R9 390 radeon).
This is an older but else very well behaved card, but there have been a few situations where i had to use workarounds or wait for fixed drivers. The game works splendidly with the java client bloodgdx, but i would prefer something that does not rely on external runtimes.

**Comment by Jan200101** [comment]
I compiled eduke32 using MinGW64 and the polymer render worked perfectly

**Comment by Jan200101** [comment]
The issue seems to have been fixed on the mapedit branch

**Comment by CommonLoon102** [comment]
@Jan200101 is it now fixed in master too? I never had such issue on any of my PCs so I can't verify myself.

**Comment by Jan200101** [comment]
I'll rebuild it as soon as I find the time

**Comment by Jan200101** [comment]
recompiled on 922c2f6d3c6de453f930219eaf26449440f84d49 using [MXE](https://github.com/mxe/mxe) and building with this command
```
make PLATFORM=WINDOWS CROSS=i686-w64-mingw32.static- SDLCONFIG=i686-w64-mingw32.static-sdl2-config AS=nasm -j
```
ran the resulting binary using wine and found no issues with the polymost renderer

**Comment by CommonLoon102** [comment]
Thanks, then I think this is fixed too and can be closed.
