### ISSUE TITLE
Building on Linux: case-sensitivity issue

### ISSUE THREAD

**Issue by wildweasel486** [nukeykt/NBlood#59]
Attempting to `make` NBlood on Linux (Mint 19) produces the following error:
`weasel@lettfeti:~/games/nblood/NBlood$ make
Built object obj/blood/blood.o 
source/blood/src/actor.cpp:54:10: fatal error: AIUNICULT.H: No such file or directory
 #include "AIUNICULT.H"
          ^~~~~~~~~~~~~
compilation terminated.
Failed building obj/blood/actor.o from source/blood/src/actor.cpp!
GNUmakefile:1160: recipe for target 'obj/blood/actor.o' failed
make: *** [obj/blood/actor.o] Error 1`
This is because, in actor.cpp, the #include line refers to AIUNICULT.H with a capital H. Renaming it to AIUNICULT.h does not solve the problem either, but correcting line 54 of actor.cpp to reference it with a lowercase h fixes this.

**Comment by nukeykt** [comment]
Does c9f8948ac5bf94dc0ce0e243493f6c0016918e65 fix this issue?

**Comment by Jan200101** [comment]
this seems to have fixed the issue for me atleast

**Comment by h3xx** [comment]
Was able to get this compiling and running on Linux using current master. Recommend closing.

**Comment by CommonLoon102** [comment]
Compiles just fine on Lubuntu.

**Comment by CommonLoon102** [comment]
Also compiles on Fedora 30 64 bit.

**Comment by CommonLoon102** [comment]
This should be closed as it builds just fine on Linux and FreeBSD too.

**Comment by wildweasel486** [comment]
Oh, yikes, was **I** supposed to close it? Sorry I forgot about it for so long. Sounds like we're good.
