### ISSUE TITLE
PCExhumed: Vanilla Save Compatibility

### ISSUE THREAD

**Issue by OpenRift412** [nukeykt/NBlood#599]
Would it be possible to make PCExhumed compatible with the DOS version's savegame files? Is that part of it's design philosophy or goals?

**Comment by CommonLoon102** [comment]
It is not part of the design philosophy or goals. Not even NBlood's save games are backwards compatible.
What use-case would you have for save game compatibility?

**Comment by OpenRift412** [comment]
> It is not part of the design philosophy or goals. Not even NBlood's save games are backwards compatible between its older versions. What use-cases would you have for save game compatibility?

Like if I had a save that I started in vanilla, but I wanted to switch over to PCExhumed. That happened to me yesterday.

**Comment by CommonLoon102** [comment]
This use-case doesn't worth the effort compared to the impact. The effort would be so huge, I can't even describe.
As a workaround, you can just use cheat codes to start from where you left off.
