### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JakeSmokie** [nukeykt/NBlood#6]
![image](https://user-images.githubusercontent.com/14360046/52825458-df0b4f00-30cd-11e9-826f-35b425713f8e.png)

**Comment by Porcozo** [comment]
Did it happen in vanilla or not?

**Comment by Tru-tu-hc** [comment]
![image](https://user-images.githubusercontent.com/10754122/55225914-051b2780-5214-11e9-8468-184fdd7491c9.png)

This picture: Assertion failed in file aiboneel.cpp at line 86.

**Comment by alexey-lysiuk** [comment]
> This picture: Assertion failed in file aiboneel.cpp at line 86.

This one was already reported in #31.

**Comment by Tru-tu-hc** [comment]
I just saw it. Thanks.

**Comment by CommonLoon102** [comment]
Seems to be fixed:
https://github.com/nukeykt/NBlood/blob/master/source/blood/src/aiboneel.cpp#L87
