### ISSUE TITLE
[Nblood] blood.pal not found when launching the game

### ISSUE THREAD

**Issue by dankcuddlybear** [nukeykt/NBlood#601]
On the latest Windows and Linux x64 builds, when I launch the game I get a popup which says:
`source/blood/src/screen.cpp(215): BLOOD.PAL not found (RFF files may be wrong version)`
Neither the DOS version or Steam version (Blood: Fresh supply) include this file.

**Comment by CommonLoon102** [comment]
BLOOD.PAL is not a separate file, it is part of BLOOD.RFF. Check again that NBlood found your files. You can have a look in nblood.log for logs.

**Comment by dankcuddlybear** [comment]
I have all my game files in /usr/share/nblood. Unfortunately the log file doesn't say much. I was able to get it working though, by manually specifying the location of some files:
`nblood -j=/usr/share/nblood -rff=/usr/share/nblood/BLOOD.RFF -ini=/usr/share/nblood/BLOOD.INI`
