### ISSUE TITLE
NBlood Icon/Logo Proposal

### ISSUE THREAD

**Issue by OpenRift412** [nukeykt/NBlood#602]
For a while now, NBlood has shared the same icon as Rednukem, so I thought I'd throw together a simple logo for NBlood.

Here's the full-size version:
![NBlood-full](https://user-images.githubusercontent.com/29780788/162800748-ad3c08c2-aab9-4d30-9c25-04452f2a7329.png)

Here's the 128x128 version
![NBlood-small](https://user-images.githubusercontent.com/29780788/162800846-02f5cc67-91c8-41aa-8a61-cf461c523e16.png)

And here's a tiny 16x16 version
![NBlood-16x16](https://user-images.githubusercontent.com/29780788/162801956-f73e3d98-01f8-40f0-99dd-fc65743b6ceb.png)

Thoughts?

**Comment by cher-nov** [comment]
"N" would fit better in the center of the palm, I believe.
