### ISSUE TITLE
[NBlood] game crashes without error message when MAP CRC does not match

### ISSUE THREAD

**Issue by Die4Ever** [nukeykt/NBlood#610]
initprintf("Map File does not match CRC");

I extracted E1M1.MAP, it worked fine, then I used a hex editor to change the last byte of the file to 0 and now the game crashes but there's no message like that in nblood.log

https://github.com/nukeykt/NBlood/blob/master/source/blood/src/db.cpp#L1243-L1245

**Comment by Die4Ever** [comment]
so how do I see those logs?

**Comment by CommonLoon102** [comment]
You can't. But if you add just one line of code then you will see it in `nblood.log`.

`initprintf()` in `baselayer.cpp`:
```
    initputs(buf);
    LOG_F(INFO, buf); // Add this line
    Xfree(buf);
```
