### ISSUE TITLE
[Issue] Whenever I download the new updates, the exes are missing

### ISSUE THREAD

**Issue by Akis-02** [nukeykt/NBlood#613]
So i think the guy forgot to packup the exes, i downloaded an early version of nblood and rednukem and it had the exes

**Comment by mjr4077au** [comment]
> So i think the guy forgot to packup the exes, i downloaded an early version of nblood and rednukem and it had the exes

https://github.com/nukeykt/NBlood/issues/609

**Comment by martyfender** [comment]
Yes, I have noticed this also. On his site, he states issues should be reported to him, oasiz, but he does not give a link to report issues.

Thanks,
 I love your builds.

**Comment by NY00123** [comment]
Closing this as #609 should be resolved.
