### ISSUE TITLE
v1.01 Pitchfork produces no smoke puffs on impact

### ISSUE THREAD

**Issue by nashmuhandes** [nukeykt/NBlood#63]
When the pitchforks hits a solid part of the level (like the floor, or walls), no smoke/impact puffs appear.

Report based on v1.01 binary. I am unable to build my own binary from the latest commit.

**Comment by alexey-lysiuk** [comment]
> I am unable to build my own binary from the latest commit.

Building with Visual Studio now requires version 2019.

**Comment by nukeykt** [comment]
Do you have surfaces.dat in your nblood folder?

**Comment by nashmuhandes** [comment]
Right, seems like I forgot to copy surface.dat. Sorry for the false report. Closing issue.
