### ISSUE TITLE
[NBlood] Report missing Blood.rff

### ISSUE THREAD

**Issue by Phredreeke** [nukeykt/NBlood#666]
When NBlood is run without Blood.rff, it reports that Blood.pal is missing. While this is technically correct, it's somewhat confusing for the user as the file is normally not found outside of Blood.rff. It would IMO be helpful if the error message reported that Blood.rff was missing, since this is the file that the user is expected to see

**Comment by MexMeRcUrY** [comment]
This is not limited to BLOOD.RFF but also GUI.RFF, SOUNDS.RFF

**Comment by MexMeRcUrY** [comment]
creating a pull request but I'm rusty LOL
```
void Resource::Init(const char *filename)
{
    RFFHeader header;
#ifdef USE_QHEAP
    dassert(heap != NULL);
#endif

    if (filename)
    {
        handle = kopen4loadfrommod(filename, 0);
        if (handle == -1)
        {
            const char *e = "File not found ";
            char error[100];
            strcat(error, e);
            strcat(error, filename);
            ThrowError(error);
        }``
```

**Comment by MexMeRcUrY** [comment]
![image](https://user-images.githubusercontent.com/379976/211143970-cfe5ac0c-936b-48f4-ae55-9369324fcab4.png)
![image](https://user-images.githubusercontent.com/379976/211143955-bda7a1ce-8672-497c-ba94-830f86f04b0a.png)
![image](https://user-images.githubusercontent.com/379976/211144017-0b64ef21-e034-4751-ba14-2cb59e0de29e.png)
