### ISSUE TITLE
GUI cursor is difficult to see

### ISSUE THREAD

**Issue by nashmuhandes** [nukeykt/NBlood#67]
I use the mouse to navigate the menus and the cursor is hard to see, initially. I have some suggestions on how the experience might be improved:

A) Dim the 3D viewport while the menu is up (like GZDoom). Would default to off to replicate vanilla visuals.

B) Ability to customize the mouse cursor graphic. I feel like it hides into the surroundings too much because it re-uses the in-game crosshair as the cursor.

C) Always place the mouse cursor at the center of the screen when the UI is first opened. This is my biggest issue... when you are playing the game using the mouse, the cursor moves with your mouselook actions in the game, even if the UI isn't opened. So every time I re-open the menu, the cursor would be at some random position and I'll have to move the mouse around first to find the cursor before I can even begin to operate the menu.

**Comment by CommonLoon102** [comment]
I've placed the mouse cursor to the middle when the menu is first opened, I've also replaced the cursor to a rotated bloody arm gib (tile 3521), I might decorate it with dripping blood or something and then let's see what @nukeykt thinks about it.

**Comment by CommonLoon102** [comment]
Fixed in master.

**Comment by PopeRigby** [comment]
@CommonLoon102 What happened to the bloody arm? It's an arrow in master.

**Comment by CommonLoon102** [comment]
Bloody arm idea has been dropped, didn't look that good.
