### ISSUE TITLE
Cryptic Passage tiles always being loaded when using Fresh Supply install

### ISSUE THREAD

**Issue by Phredreeke** [nukeykt/NBlood#673]
When NBlood detects a Fresh Supply install, it will include the directory addons/Cryptic Passage
Unfortunately due to the way FS packages the game its ART files will override those used in the game's Episode 6.

Could this be fixed without having the user copy the effected files manually into NBlood's running directory?

**Comment by Hendricks266** [comment]
I believe I fixed this in c6a7ed096f5af7eade3bea82a80fb34bc62e3cee and 4077a0821b786fd5c9fcaaf2fb8a0ebc118ab481.
