### ISSUE TITLE
[Rednukem] Showstopper in "Shaky Grounds"

### ISSUE THREAD

**Issue by NightFright2k19** [nukeykt/NBlood#676]
At the beginning of the very first map of the Duke3D mod ["Shaky Grounds"](https://www.moddb.com/mods/shaky-grounds/downloads/shaky-grounds), "Apocollapse" (sg1.map), you have to escape from a collapsing building into a tunnel. On your way there, you have to drop down a ventilation shaft. 

In Rednukem, escaping this shaft is not possible since the player is unable to crawl through the final duct section ahead to reach the tunnel. This is not a problem in EDuke32. It is the only issue in the entire episode, all other four maps have no showstoppers.

**Comment by Hendricks266** [comment]
If you remove other parts of the map to get it under vanilla limits, does the same issue happen in the original EXE under DOSBox? If so, this is not a bug in Rednukem.

**Comment by Phredreeke** [comment]
Raze had the same issue, The map relies on [eduke32 unsetting a cstat bit](https://forum.zdoom.org/viewtopic.php?p=1225720#p1225720)

**Comment by Phredreeke** [comment]
I have no idea but it seems so. But the fix would be to modify the map itself, not change the behavior of Rednukem which is in line  with the original game. Maybe Merlijn will release Shakier Grounds? 😜

**Comment by Phredreeke** [comment]
This issue can be closed now that Merlijn has corrected the behavior in the map itself.

**Comment by NightFright2k19** [comment]
That's right, actually. Almost forgot about it. Would still be nice if RN didn't treat invisible masterswitch sprites like blocking objects, but well...
