### ISSUE TITLE
[Blood] 1.21 demo desync/inaccuracy

### ISSUE THREAD

**Issue by tmyqlfpir** [nukeykt/NBlood#683]
Testing with 1.21 demos I encountered a desync issue with the cryptic passage shareware version of Monstery. This demo plays correctly on BloodGDX, but desyncs with NBlood. I've also tried a NBlood build from May-2020 (r11615-5a3f17acc) and Feb-2019 (NBlood r7326) and it they share the same desync issue.

[demo desync.zip](https://github.com/nukeykt/NBlood/files/10366975/demo.desync.zip)

Left is DOS, right is NBlood (r13373-f0b373322)

Video: https://files.catbox.moe/zhefml.mp4

Left is BloodGDX, right is NBlood (r13373-f0b373322)

https://files.catbox.moe/nn9ase.mp4

**Comment by Hendricks266** [comment]
@nukeykt Do you know what's going on with this?

**Comment by nukeykt** [comment]
can anyone check if this happen with reconstructed exe?
[BLOOD.zip](https://github.com/nukeykt/NBlood/files/11865886/BLOOD.zip)

**Comment by Hendricks266** [comment]
> It could be something like how gSpriteHit is not init as zero and results in the demo desync for BLOOD002.DEM

Do you mean the stock demo by this name? Is this desync still present?

**Comment by nukeykt** [comment]
watcom 10.6 and tasm 3.1/3.2 should be sufficient. Just type `wmake` in helix, qtools and then in blood directories

**Comment by nukeykt** [comment]
hmm, what about? maybe `fix16_to_int` does some rounding
`pPlayer->q16ang = ((pPlayer->q16ang&0x7ff0000)+(pInput->q16turn&0x7ff0000))&0x7ffffff;`
