### ISSUE TITLE
Pi4 fail to build. 

### ISSUE THREAD

**Issue by Exarkuniv** [nukeykt/NBlood#696]
Raspberry Pi4
Buster 10/RetroPie

downloaded the latest git 
cd NBlood
sudo make blood USE_OPENGL=0 STARTUP_WINDOW=0

I have a old version that i use to install, but i want to see how much things have changed all the work you guys have done since then

i have gone through all of the closed issues to see what files i need to change. 
but when i looked at the files that where mentioned in the tickets. i did not see the lines to be changed.

so i decided to give it a shot, 
this error is a new one that i was not expecting. 

```
Built object obj/blood/config.o
source/blood/src/controls.cpp: In function ‘void ctrlGetInput()’:
source/blood/src/controls.cpp:525:50: error: ‘(1.156e+3 / 6.0e+1)’ is not a constant expression
         CONSTEXPR double lookStepUp = 4.0*upAngle/60.0;
                                       ~~~~~~~~~~~^~~~~
source/blood/src/controls.cpp:526:55: error: ‘(1.388e+3 / 6.0e+1)’ is not a constant expression
         CONSTEXPR double lookStepDown = -4.0*downAngle/60.0;
                                         ~~~~~~~~~~~~~~^~~~~
Failed building obj/blood/controls.o from source/blood/src/controls.cpp!
make: *** [GNUmakefile:1586: obj/blood/controls.o] Error 1
```

**Comment by derek57** [comment]
If you remove the "CONSTEXPR" right before those to lines and therefore make it look like this within the code...:

double lookStepUp = 4.0*upAngle/60.0;
double lookStepDown = -4.0*downAngle/60.0;

...then the code will build further.

Note that there are also lines like these within these files:

nnexts.cpp
player.cpp
polymer.cpp *
view.cpp

...which require this change to make it build.

* For file "polymer.cpp" it's these lines required for a change:

    (ORIGINAL):
            static constexpr float factor_new = 1.f / ((2048.f * (1.07f / 1.024f) * (150.f / 230.f) / 35.f) * material_visibility_divisor);
            static constexpr float factor_old = 1.f / ((2048.f * (1.07f / 1.024f) / 35.f) * material_visibility_divisor);

   (MOD:)
            static float factor_new = 1.f / ((2048.f * (1.07f / 1.024f) * (150.f / 230.f) / 35.f) * material_visibility_divisor);
            static float factor_old = 1.f / ((2048.f * (1.07f / 1.024f) / 35.f) * material_visibility_divisor);

**Comment by Exarkuniv** [comment]
I forgot this was even open.
I have not tried this in over a year and not sure if it's even irrelevant anymore. 

Thanks for the information though
