### ISSUE TITLE
See what weapon a player possesses in his arms in multiplayer

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [nukeykt/NBlood#698]
I am not sure if it is possible to implement in a build engine. Probably, it will be even required to have additional animations.

Currently, in multiplayer, everybody see the opponent's weapon as an icon above their heads and all players only have visually pistols in their arms (in Blood for example).

It would be cool to see a current weapon in the player's arms.

**Comment by Hendricks266** [comment]
This is more the domain of a mod than a source port.
