### ISSUE TITLE
E2M1 Clipping issue

### ISSUE THREAD

**Issue by shockinglycavalier** [nukeykt/NBlood#70]
![blud0001](https://user-images.githubusercontent.com/50780884/57974311-9c873600-798c-11e9-98d3-061e09f398a6.png)

Diving suit is visible through the wall in E2M1 using Polymost renderer in latest dev build. Issue is not reproducible using classic renderer nor in version 1.01 (both renderers).

**Comment by CommonLoon102** [comment]
Issue is not reproducible in the mapedit branch.

**Comment by CommonLoon102** [comment]
How difficult it would be to cherry pick and merge only those changes which fix this issue from mapedit to master?

**Comment by CommonLoon102** [comment]
@nukeykt: How difficult it would be to cherry pick and merge only those changes which fix this issue from mapedit to master?

**Comment by CommonLoon102** [comment]
Fixed in master.
