### ISSUE TITLE
[BUG] Exhumed: No `nVertPan` setting since late 2019, affecting momentum

### ISSUE THREAD

**Issue by mjr4077au** [nukeykt/NBlood#703]
During `093c3c5d268de2fca3b9049140d718fdb42cf949`, `nVertPan[]` was replaced with a new variable for the player's pitch/horizon. The problem is that the game's code is applying the pitch adjustment when going up/down stairs etc to `nVertPan[]` still and therefore the player doesn't experience it.

Since the game has no bobbing or swaying, without the pitch tilting up/down as the player's Z changes, there's not a lot of feel to the game. We've got a working implementation in Raze, and GDX does as well. We've reworked ours differently though so that the effect can always be in use so long as `cl_slopetilting` is enabled whereas GDX and the original code only applied if the player had mouse aiming off and their pitch/horizon was locked at 92.

The code in question where this is done is below: https://github.com/nukeykt/NBlood/blob/b0ca8e0d7238ad755297d930752fd0d553d16727/source/exhumed/src/player.cpp#L2842-L2877

**Comment by mjr4077au** [comment]
I tried to capture a video to demonstrate what I mean. This is with the engine's clock reduced to half speed to counter for the low frame rate of the recording.

https://user-images.githubusercontent.com/48643140/227767451-badd5605-f751-4f43-a13a-eb525bc8f2ad.mp4

**Comment by mjr4077au** [comment]
When this gets looked at, I'd love to know for sure whether the formula in PCExhumed or the one in GDX is correct according to your RE notes: https://gitlab.com/m210/PowerslaveGDX/-/blob/master/core/src/ru/m210projects/Powerslave/Player.java#L1322-L1332

In both PCExhumed and GDX, the horizon/nDestVertPan delta is divided by 4 and then is clamped at -4/+4 if it exceeds it. However, in GDX, if the divided delta doesn't exeed 4, the delta is applied at half its value, or 2x the divided by 4 value.

Can be easily seen in the link, but I'd love to accurately preserve it if I can.

**Comment by sirlemonhead** [comment]
What I have (or had, nukey tweaked this I believe) looks to be correct based on a quick look at the disassembly again. I'm not sure if M210 just tweaked it then to make it work better.

I quickly compared PCExhumed to the DOS release and the behaviour seems the same between them when going up and down stairs. Is that correct?

**Comment by mjr4077au** [comment]
It could have been tweaked by M210 for sure, I don't think the original formula was super great, thanks for checking!

I'm also very sorry, I just checked again and I don't believe I properly toggled mouse aiming when I was testing this one 🤦‍♂️. I can confirm when mouse aiming is off that the feature works as expected.
