### ISSUE TITLE
[Feature] Exhumed: Fix noclipping

### ISSUE THREAD

**Issue by mjr4077au** [nukeykt/NBlood#705]
The original noclipping kind of sucks due to the `inside()` check in `FuncPlayer()` unconditionally bounding the player even if they're noclipping or not.

If this branch of code is moved into the `else` block above it, it'll allow the player to freely noclip wherever they want. Aside from being better for the player, it's better for debugging as well when you just want to get somewhere in the level fast.

https://github.com/nukeykt/NBlood/blob/372cab1596e81c2d6db92141e50cc59307e7a3c4/source/exhumed/src/player.cpp#L2091-L2102

**Comment by sirlemonhead** [comment]
Yep good shout, thanks! :)
