### ISSUE TITLE
[blood] 'loguru' compilation error on OpenBSD 7.3

### ISSUE THREAD

**Issue by lea2501** [nukeykt/NBlood#709]
Hi! i'm trying to compile NBlood port under OpenBSD 7.3 stable, and i'm getting the following error.

I used the following gmake command in cloned directory:

`$ gmake CXX=eg++ USE_OPENGL=1 POLYMER=1 HAVE_GTK2=1 STARTUP_WINDOW=0 USE_LIBVPX=1 CLANG=1 NOASM=1 PACKAGE_REPOSITORY=1 RELEASE=1`

Error 'error: static_cast from 'pthread *' to 'uintptr_t' (aka 'unsigned long') is not allowed
':

```
gmake: gcc: No such file or directory
clang++: warning: argument unused during compilation: '-fuse-ld=lld' [-Wunused-command-line-argument]
source/build/src/loguru.cpp:1152:5: error: use of undeclared identifier 'pthread_getname_np'; did you mean 'pthread_get_name_np'?
                                pthread_getname_np(pthread_self(), buffer, length);
                                ^~~~~~~~~~~~~~~~~~
                                pthread_get_name_np
/usr/include/pthread_np.h:50:6: note: 'pthread_get_name_np' declared here
void pthread_get_name_np(pthread_t, char *, size_t);
     ^
source/build/src/loguru.cpp:1185:34: error: static_cast from 'pthread *' to 'uintptr_t' (aka 'unsigned long') is not allowed
                                                           : static_cast<uintptr_t>(native_id);
                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
Failed building obj/build/loguru.o from source/build/src/loguru.cpp!
gmake: *** [GNUmakefile:1588: obj/build/loguru.o] Error 1
```

Thanks in advance.

**Comment by Hendricks266** [comment]
For the first error, what happens if you make the suggested replacement (adding the underscore in the right place)? I tried searching for information about this and actually found someone reporting the same error upstream: https://github.com/emilk/loguru/issues/225

The second error confuses me, because it should be valid to cast a pointer to `uintptr_t`. Maybe it just needs to be `reinterpret_cast` instead of `static_cast`. Does that fix it?

**Comment by seanm** [comment]
@lea2501 @Hendricks266 I have a loguru patch here if you'd like to review/test: https://github.com/emilk/loguru/pull/245

**Comment by Hendricks266** [comment]
@seanm I merged in most of that patchset, thanks!

**Comment by Hendricks266** [comment]
I believe this is fixed, please reopen if not.
