### ISSUE TITLE
[Blood] Only sprites render. [W10] [Nvidia]

### ISSUE THREAD

**Issue by Tarentaise** [nukeykt/NBlood#713]
![aaaaa](https://github.com/nukeykt/NBlood/assets/98259606/52e99a6d-a7ee-4519-a1dd-17896f87ce8c)
Game version: Blood Plasma Pak
OS: Windows 10
Happens on software and polymost renderers. 
Specs can be provided if needed.

**Comment by nukeykt** [comment]
looks like some of TILESXXX.ART files are missing
