### ISSUE TITLE
Read this sirlemonhead 

### ISSUE THREAD

**Issue by Milan978** [nukeykt/NBlood#715]
Care to explain why you closed my topic and deleted my last comment? Are you affraid of the truth? Remove that picture of Charles Bronson from your profile cause you are nothing but the coward who deletes people that speak truth. I wish you very bad life and suffering.

**Comment by CommonLoon102** [comment]
I think it was closed because you have reported 3 problems in one issue, also one of them was a duplicate.

**Comment by Milan978** [comment]
No! He deleted my last comment where I'm telling you all who defended nblood that if you want to see a good port for old game should visit this page: https://veg.by/en/projects/nfs3/

The game is from 98 and what this guy manage to pull off alone without any source code is mind blowing. Just read carefully what he wrote on his patch.  He made it to work on all Windows version from 95 to 11. It's even working on superold processors. That is something that nblood aspire to.

**Comment by CommonLoon102** [comment]
It doesn't even run on Linux.

**Comment by Milan978** [comment]
For my entire life I never known a person that uses Linux. Linux is irrelevant cause people that are using it can be counted on fingers of one hand.

**Comment by CommonLoon102** [comment]
Do you have an Android phone? Or do you know anyone who does? Or Smart TV?

**Comment by sirlemonhead** [comment]
You're adding nothing useful to this repository. Please stop commenting and go away.
