### ISSUE TITLE
[Blood] Graphical glitch (room-over-room?) in E2M7: Bowels of the Earth

### ISSUE THREAD

**Issue by Matthaiks** [nukeykt/NBlood#720]
https://github.com/nukeykt/NBlood/assets/3577122/206ddf03-e2e7-4220-8ede-9d587c064590

r13558, Windows 10 22H2 x64

**Comment by CommonLoon102** [comment]
This can be a bug in the map. Try the DOS version, go to the same place and check what you see.

**Comment by Matthaiks** [comment]
Yes, it does happen in the DOS version too.
