### ISSUE TITLE
Question about the code of tekwar and witchaven

### ISSUE THREAD

**Issue by orderorder** [nukeykt/NBlood#723]
I have seen in the source code that there have been changes that seem to reference tekwar and witchaven. Will Nblood work with these games in the future?

**Comment by sirlemonhead** [comment]
It's unlikely - I was the one who started adding them but quickly lost interest. The code is still there in case someone else wants to do it or if I someday decide to get back to it, but I wouldn't hold my breath.

**Comment by orderorder** [comment]
I guess there is no interest in those games. I heard that the code is a mess. I think the Raze launcher doesn't want to add those games
