### ISSUE TITLE
[QUESTION] NBlood version number in HUD

### ISSUE THREAD

**Issue by BreakinBenny** [nukeykt/NBlood#725]
The number v1.01 is shown in NBlood's HUD even if this source code is probably based on **v1.11**, and much has been done with this eDuke32-based port since. If you don't mind me asking, what's up with that number down there?
![image](https://github.com/nukeykt/NBlood/assets/4566768/c9590ec0-fe9a-45d3-8d8b-7fe989c37374)

**Comment by Hendricks266** [comment]
v1.01 refers to NBlood as a port. This version was our last "stable" release before moving to a rolling release format. We sync accurately to playback demos made with version v1.21 of the original game.

**Comment by CommonLoon102** [comment]
> > We sync accurately to playback demos made with version v1.21 of the original game.
> 
> There is a [demo that I've reported](https://github.com/nukeykt/NBlood/issues/683) that manages to desync with NBlood while GDX/DOS playbacks fine. I know this is off-topic but I'd love to see this eventually solved as I haven't been able to track down the cause of the discrepancy.

Have you tried `git bisect`?

**Comment by BreakinBenny** [comment]
Well, then it seems reasonable to leave that number at v1.01 until way further down the line when you manage to get something extra up and running for these reverse-engineered ports.

**Comment by Hendricks266** [comment]
I'm considering changing it to the revision number.

**Comment by Hendricks266** [comment]
Releases using GitHub Actions are now live. Thanks @tmyqlfpir.

@BreakinBenny Does the change to the version box resolve this issue?

**Comment by BreakinBenny** [comment]
> Releases using GitHub Actions are now live. Thanks @tmyqlfpir.
> 
> @BreakinBenny Does the change to the version box resolve this issue?

Yes, I see an "R1" in the left corner now.

**Comment by Hendricks266** [comment]
Great. When b275cb1595f10ae1d6d773e624b78985dae40118 is done building it should correctly say r13655,
