### ISSUE TITLE
[Blood] Voxel pack using wrong voxel in software mode

### ISSUE THREAD

**Issue by tmyqlfpir** [nukeykt/NBlood#727]
Using the [voxel pack addon](https://github.com/fgsfds/Blood-Voxel-Pack) and compiling NBlood in debug mode results in bottles being used for the wrong picnum. This only happens with the software renderer. Attempts to debug show it loading `BOTTLE5` for picnum 74.
This issue is also present in NotBlood release mode despite little change to the build engine itself - suggesting that there is some undefined behavior for classic voxel overrides.

![blud0001](https://github.com/nukeykt/NBlood/assets/80724828/b5d5fd5a-136c-4953-9008-138952d979d7)

**Comment by Hendricks266** [comment]
We have some fixes in review upstream and one of them relates to voxels in classic. If it's easy to test, could you see if this resolves the issue?

```diff
diff --git a/source/build/src/engine.cpp b/source/build/src/engine.cpp
index dbf186743..b6c14cc3e 100644
--- a/source/build/src/engine.cpp
+++ b/source/build/src/engine.cpp
@@ -5004,7 +5004,7 @@ typedef zint_t voxint_t;
 static void classicDrawVoxel(int32_t dasprx, int32_t daspry, int32_t dasprz, int32_t dasprang,
                              int32_t daxscale, int32_t dayscale, int32_t daindex,
                              int8_t dashade, char dapal, const int32_t *daumost, const int32_t *dadmost,
-                             const int8_t cstat, const int32_t clipcf, int32_t floorz, int32_t ceilingz)
+                             const int16_t cstat, const int32_t clipcf, int32_t floorz, int32_t ceilingz)
 {
     int32_t i, j, k, x, y, mip;
```

**Comment by Hendricks266** [comment]
Does this issue happen with Shadow Warrior's voxel pack too? If not, could `qloadvoxel` be interfering with proper function in some way?
