### ISSUE TITLE
[Blood] Character and Viewport is not in sync

### ISSUE THREAD

**Issue by Darkthus** [nukeykt/NBlood#728]
I have noticed that in NBlood what I see is not accurate to where my "body" is facing, this means that doing fast flicks with a shotgun for example is not going to hit the enemy, as my shots lag behind my crosshair (so doing a fast flick to the right, my shot won't land where my crosshair is, instead they will appear to the left of it).

It also makes shooting moving enemies with the Tommy gun hard, as you have to aim in front of them, as if you are lagging in a multiplayer game.

I first thought this is an issue with NotBlood fork (see here: https://github.com/clipmove/NotBlood/issues/44), but after testing it in NBlood the results were the same.

Is it possible to fix this, so that the camera and the character is in sync? VoidSW for example doesn't have this issue.

**Comment by CommonLoon102** [comment]
Do you experience this in the original DOS version?

**Comment by Darkthus** [comment]
Tested in DOS: there, the camera itself lags, however the shots go where the crosshair is. So what I think is happening in NBlood is that the character turns the same delayed way as in the DOS version, however the camera itself has that delay removed, so these two are not in sync.

**Comment by CommonLoon102** [comment]
Does Raze use a higher tickrate or what?

**Comment by mjr4077au** [comment]
We haven't, we run Blood at 30Hz like NBlood and this will never change, however we poll for mouse input at frame rate speeds but so does NBlood. Ticrate input polling can be forced by using `cl_syncinput 1` though.

There's something about our Windows backend that we share with GZDoom that is just second to none when it comes to mouse input and responsiveness. If I'm on Linux where we use SDL, it feels about the same as an EDuke port in terms of responsiveness.

**Comment by Hendricks266** [comment]
Thanks for the dedicated work! That fix looks good to me, and feels good in-game. I've applied it to NBlood to get wider testing.

**Comment by CommonLoon102** [comment]
> Great! It's a wonder how the original devs never noticed firing was a frame behind.

People were playing on the keyboard without a mouse. On a Pentium 1 at 30 FPS on average. I don't think anyone noticed such things.
For me, DN3D's shotgun always felt weird. The shotgun shoots half second after you clicked. By that time the crosshairs is far away where I clicked.

**Comment by Hendricks266** [comment]
@Darkthus How do the latest builds feel now that we've made this change? https://github.com/nukeykt/NBlood/releases/tag/latest
