### ISSUE TITLE
[NBlood] Randomly choose between MIDI and CD Audio if both are found

### ISSUE THREAD

**Issue by BreakinBenny** [nukeykt/NBlood#731]
In even Vanilla Blood (and Fresh Supply) we can only ever choose to play either MIDI music, or CD audio, not both. How would this proposal sound: allow alternating between CD and MIDI (if both are specified for a map and you have the respective audio option active)?

**Comment by Hendricks266** [comment]
This feels like something that would be better suited to a mod. You might want to suggest it for [NotBlood](https://github.com/clipmove/NotBlood).
