### ISSUE TITLE
[QUESTION] Cultist color palette re-creation, in SLADE or similar

### ISSUE THREAD

**Issue by BreakinBenny** [nukeykt/NBlood#732]
This is not an issue at all, though I wasn't sure where else I could ask it: what code controls the Cultists' robes' palette (plus what weapon or ability they have), and what are the values for 'em? I'm attempting to re-create the higher "ranks" using **SLADE**, which on top of supporting opening .RFF files also allows remapping colours.
![image](https://github.com/nukeykt/NBlood/assets/4566768/d0bccfe6-865b-46cf-b837-368f06fdfda2)

**Comment by Hendricks266** [comment]
The palswaps are stored in the PLU files in the RFF. They contain 8bpp 256x64 (= 16384 bytes) palookup tables. You probably only need the first 256 bytes of them for the unshaded remapping indexes. The rest of the table contain the full shades due to the implementation of palswaps in the engine.

**Comment by BreakinBenny** [comment]
Mhm, this should be tough given **SLADE** was primarily made with idTech 1 in mind and only sometimes allowing tinkering with Build (or other Doom-similar) engine assets. I thought about going ingame to capture the colors by hand, though this will save time albeit having to say, manually make **.PAL**s from the **.PLU**s.

There's NORMAL (likely without modifications whatsoever), SATURATE, BEAST (Post-Mortem bosses pre-Beast form?), TOMMY (Fanatics?), GRAY, GRAYISH, SPIDER1 through SPIDER3, FLAME, and COLD. P1 through P4 is just Caleb colors

**Comment by BreakinBenny** [comment]
@Hendricks266 I've figured it out... kind of, and I chose not to continue with SLADE: XMAPEDIT allows previewing ART graphics and palookups, which allows for quickly taking screenshots later (like I did for TV Tropes just now). Thanks anyway!
