### ISSUE TITLE
[Blood] Low frame rate when map is open

### ISSUE THREAD

**Issue by oifj34f34f** [nukeykt/NBlood#734]
Compared to Rednukem, Blood has a low frame rate when the map is open. I'm not sure if this bug exists in Windows (I use Linux), so please check it.

## Rednukem (good)
https://github.com/nukeykt/NBlood/assets/128177553/40da24dd-ff03-426f-a36b-e744de839013

## Blood (bad)
https://github.com/nukeykt/NBlood/assets/128177553/4773ca14-52c5-4c30-ad1a-96c90980f73e

**Comment by oifj34f34f** [comment]
> This is by design, Blood does not interpolate the view/angle for 2D map view. It can be fixed [by interpolating](https://github.com/clipmove/NotBlood/commit/40198b8512795afa55bcf25ab40f41c12ee0dc2c) much like the 3D view does.

Thank you, nice work!

**Comment by Hendricks266** [comment]
> This is by design, Blood does not interpolate the view/angle for 2D map view. It can be fixed [by interpolating](https://github.com/clipmove/NotBlood/commit/40198b8512795afa55bcf25ab40f41c12ee0dc2c) much like the 3D view does.

I would be interested in upstreaming that, expanding the extent of interpolation is definitely in scope. I believe we've already done stuff like that in VoidSW.
