### ISSUE TITLE
[Blood] DEF Glow Mapping does not work

### ISSUE THREAD

**Issue by MexMeRcUrY** [nukeykt/NBlood#746]
https://wiki.eduke32.com/wiki/Glow_mapping
things get worse if you use Polymost > Y-Shearing = OFF

Example:
[nblood.zip](https://github.com/nukeykt/NBlood/files/12340552/nblood.zip)

![image](https://github.com/nukeykt/NBlood/assets/379976/90273091-ca59-4e6e-84ef-c0c983fac174)

**Comment by Hendricks266** [comment]
Very strange, it's using the indexed tile atlas as a texture.

**Comment by MexMeRcUrY** [comment]
confirmed it also happens with the cop-pig glow eyes in the latest Nblood code/project (HRP Mod), I have tracked back and the the code from Febuary works fine. I havent found at what point in time this got broken 
![image](https://github.com/nukeykt/NBlood/assets/379976/27ed0d66-905f-40de-af3b-548a334953ce)

**Comment by MexMeRcUrY** [comment]
Eduke32 autoload folder
[duke3D.zip](https://github.com/nukeykt/NBlood/files/12343254/duke3D.zip)

**Comment by Hendricks266** [comment]
So it happens in eduke32.exe when built from the NBlood repository, but not upstream?

Could you try the branch `tmp/nblood-engine` upstream? https://voidpoint.io/terminx/eduke32/-/commits/tmp/nblood-engine

If it has the issue too, could you bisect through the commits in that branch to see which one introduces the issue?

**Comment by MexMeRcUrY** [comment]
@Hendricks266  the issue started here:
https://voidpoint.io/terminx/eduke32/-/tree/d53cefa84716fbbed647aa26d2f00fa77c6f5793

**Comment by Hendricks266** [comment]
@nukeykt do you know what's going on? It seems likely to me that the issue relates to the change to the fragment shader.

**Comment by nukeykt** [comment]
looks like coordX, coordY was changed to vector at some point in mainline and broke shader compilation

**Comment by nukeykt** [comment]
```
    coord = mix(gl_TexCoord[4].xy,gl_TexCoord[4].yx,u_usePalette);
    odCoordYnpotEmulationFactor = mod(coord.y,u_npotEmulation.y);
    coord.xy = vec2(floor(modCoordYnpotEmulationFactor)*u_npotEmulation.x+coord.x, floor(coord.y*u_npotEmulation.y)+modCoordYnpotEmulationFactor);
    newCoord = mix(gl_TexCoord[4].xy,mix(coord.xy,coord.yx,u_usePalette),u_npotEmulation.z);
```
something like this should work

**Comment by Hendricks266** [comment]
@nukeykt I would be most comfortable if you pushed the fix to this repo

**Comment by MexMeRcUrY** [comment]
@nukeykt  thank you for the quick turnaround on this issue, I have tested it and looks to be fixed and working as expected!!! :)
![image](https://github.com/nukeykt/NBlood/assets/379976/9bda15f4-e901-4c0b-a426-4a699b069825)

**Comment by MexMeRcUrY** [comment]
Issue fixed with the following commit:
https://github.com/nukeykt/NBlood/commit/509439895a9934aa4fd4e05804968137ffa7734e
