### ISSUE TITLE
All graphics except HUD is nothing but a pink void

### ISSUE THREAD

**Issue by BoneofMalkav** [nukeykt/NBlood#76]
Specs:
NVidia GTX 960 (Driver is version 430.86)
Intel Core i5-2400 Quad Core 3.10GHz
8 GB DDR3 Ram
Windows 10 64-Bit

After moving all the required files into their own directory (Blood's INI file, the DEM and RFF files ect.) I noticed that no matter what renderer I set it to, or graphical filtering settings I set. the game's rendered in a pink or purpleish void with the exception of HUD elements. Here's a screenshot of what it looks like and the log file.
![blud0000](https://user-images.githubusercontent.com/17387089/59002585-e96a6980-87e0-11e9-9130-5ab77057f03d.png)
[nblood.log](https://github.com/nukeykt/NBlood/files/3259715/nblood.log)

I will note that I wouldn't be surprised if it's an issue on my part.

**Comment by nukeykt** [comment]
Do you have all the tiles.art files in your folder? IIRC there are 24 art files

**Comment by BoneofMalkav** [comment]
You sure it's 24 art files? Cause checking both Steam and GOG's version (One Unit Whole versions) only counts 18 excluding Cryptic Passage's ART files (CPART07 and 15)

**Comment by nukeykt** [comment]
You right, it's 18 art files

**Comment by BoneofMalkav** [comment]
Then that has me wondering if there's some sort of software dependency that I'm missing? (Which is odd since EDuke32 itself runs just fine for me.)

**Comment by nukeykt** [comment]
Try to run game with `-usecwd` parameter. nblood can detect files from steam or gog installation and maybe there's some interference, usecwd forces game to only use current folder

**Comment by BoneofMalkav** [comment]
using the usecwd parameter, and still the same

**Comment by Hendricks266** [comment]
Please reopen if not fixed.
