### ISSUE TITLE
[PCExhumed] Small Feature Request - Add Option to Skip Intro Screens and Pharoah's Laugh and Go Straight to Main Menu

### ISSUE THREAD

**Issue by MasterO2** [nukeykt/NBlood#767]
@tmyqlfpir, @Hendricks266 or anyone else:

Currently, in PCExhumed, you have to press `Enter` multiple times to skip the company logos, intro movie, and pharaoh's laugh before the main menu even appears.

So, on the PCExhumed windows that pops up, there should be an option called `Skip intros` that takes you straight to the main menu. It can be placed under the `Fullscreen` and `Polymer` options.

**Comment by Hendricks266** [comment]
Pass the `-quick` command line parameter.

A checkbox on the startup window is not the way.

**Comment by MasterO2** [comment]
> Pass the `-quick` command line parameter.
> 
> A checkbox on the startup window is not the way.

Ok, thanks for clarifying. On that note, that `-quick` command line parameter should be mentioned in https://github.com/nukeykt/NBlood#pcexhumed. 

I'm sure I'm not the only one who has wanted to know how to skip the intro screens like that.
