### ISSUE TITLE
[Pcexhumed]Garbled textures

### ISSUE THREAD

**Issue by petran79** [nukeykt/NBlood#769]
Using the latest Windows  build. I tried both the GOG and the Exhumed CD version of the files, same issue, both in Opengl and software mode
![exhumed](https://github.com/nukeykt/NBlood/assets/8232210/8edb5476-8542-4414-b80b-7902b02bdef7)

**Comment by Phredreeke** [comment]
Don't run PCExhumed from the same folder as Blood
