### ISSUE TITLE
macOS artifacts/release files?

### ISSUE THREAD

**Issue by sofakng** [nukeykt/NBlood#770]
Are there any macOS artifacts/release files?

I see it was enabled in the CI but it looks like only win32 and win64 files are produced.

Also, does this engine feature the latest eduke32 or is it something different?  (I'm a little confused on the relationship between this engine [Build port] and eDuke32?)

**Comment by Hendricks266** [comment]
> Are there any macOS artifacts/release files?
> 
> I see it was enabled in the CI but it looks like only win32 and win64 files are produced.

Unfortunately not, you will have to compile from source, however that is a simple process.

> Also, does this engine feature the latest eduke32 or is it something different? (I'm a little confused on the relationship between this engine [Build port] and eDuke32?)

Yes, it incorporates the latest EDuke32. Upstream contains ports derived from official source code releases, this one houses anything else. Development tracks closely, and you can see updates being pulled downstream on a regular basis in the commit logs.
