### ISSUE TITLE
Voxels not transparent in Classic (software) renderer

### ISSUE THREAD

**Issue by Tiddalick** [nukeykt/NBlood#776]
The classic renderer is unable to show transparent voxels.
This is easily seen in E1M1 using the community voxel pack.
Though I don't know if the renderer was ever able to do this?
Obviously the Polymost renderer does, but that currently has the issue with the excess darkening when viewed at higher resolutions.

Polymost
![image](https://github.com/nukeykt/NBlood/assets/32033640/31588093-27e9-4d07-a98b-e26625b47d81)

Classic (Software)
![image](https://github.com/nukeykt/NBlood/assets/32033640/de9e718a-6fb1-4eb9-916e-51924acd810d)

**Comment by Hendricks266** [comment]
My understanding is that implementing voxel transparency in Classic is infeasible. We can reopen this if I am mistaken.
