### ISSUE TITLE
error: parameter 'XXX" is undefined when launching Liquidator 3D

### ISSUE THREAD

**Issue by fgsfds** [nukeykt/NBlood#792]
Steps to reproduce:
- Download https://github.com/fgsfds/Build-Mods-Repo/blob/master/Duke3D/Campaigns/liquidator3d_v15.zip and put it in a folder with rednukem.exe and duke3d.grp
- Start RedNukem with `.\rednukem.exe -g .\liquidator3d_v15.zip -x LIQUID.CON` and select DUKE3D.GRP as a main GRP

Result: `error: parameter 'RPG_WEAPON_STRENGTH' is undefined` and other similar errors. 'RPG_WEAPON_STRENGTH' is defined in `SOUND.CON` and included in `LIQUID.CON`

**Comment by NY00123** [comment]
Hi,

From what I've found, the CON code was made with v1.3d in mind, as shown by the `gamestartup` command. Unlike other ports, Rednukem does not include partial compatibility with v1.3d's data.
