### ISSUE TITLE
[NBlood] Enemy death sounds randomly cut out

### ISSUE THREAD

**Issue by oifj34f34f** [nukeykt/NBlood#804]
Demo (watch with sound on):

[demo.webm](https://github.com/nukeykt/NBlood/assets/128177553/91059ad1-af2d-452f-8ba4-e45ef462c679)

While full audio is:

https://github.com/nukeykt/NBlood/assets/128177553/158b7b1b-d7be-49bb-84d7-b67540dd4cd6

I'm not the first one to encounter this bug: https://old.reddit.com/r/bloodfps/comments/13evddl/nblood_sound_bug/

**Comment by CommonLoon102** [comment]
Isn't it happening in DOS too?

**Comment by oifj34f34f** [comment]
@CommonLoon102 I can't say for sure, as I haven't played Blood on DOS

**Comment by CommonLoon102** [comment]
Even if this happens in DOS, you can keep this opened because bugs like this gets fixed, especially if they don't cause a desync in demo playback.
I just usually ask if it is a vanilla bug or not.

**Comment by oifj34f34f** [comment]
@tmyqlfpir Thanks for your PR, but it looks like the bug is still there:

https://github.com/user-attachments/assets/2d9f70aa-3f67-428c-9b51-2cf0467b0800

(E4M6: The Ganglion Depths)

NBlood version: r14112-1456e5eb5
