### ISSUE TITLE
What license is nblood shipped under?

### ISSUE THREAD

**Issue by MIvanchev** [nukeykt/NBlood#815]
Hey, I'm currently packaging NBlood for Void Linux but can't find licensing information anywhere, could someone help?

**Comment by Jan200101** [comment]
NBlood is part GPL-2.0-only and part Build License.
You can find a copy of the Build license in `package/common/buildlic.txt`.
Be aware that the Build License could be considered open source but definitely not libre.

**Comment by MIvanchev** [comment]
@Jan200101 thanks, I'm aware, I already did the Raze and Eduke32 packages :D
