### ISSUE TITLE
All win64 ports crash (SSSE3 is still a Requirement)

### ISSUE THREAD

**Issue by LukasThyWalls** [nukeykt/NBlood#865]
Hello.

I was updating some of ports files (mostly all of them were from 2020), and when I got to NBlood, PCExhumed, etc... I saw that any of them worked anymore. At first I thought that the game files (I was extracting from my GOG versions that I bought a way back and I never used for this) were incorrect, but then I look up and with the old port files they worked normally.

### This doesn't work:

- Just start any of the ports (_NBlood_, _PCExhumed_ or _Rednukem_) of the [last version](https://github.com/nukeykt/NBlood/releases/tag/r14125) (_win64_20241119: r14125-fcb8c4109, Built Nov 19 2024 05:06:54, GCC 14.2.0, 64-bit_), it opens the start screen, detecting the game, keeping everything at default as it is.
- Click Start... and **it crashes** ([nblood_win64_20241119.log](https://github.com/user-attachments/files/17881981/nblood_win64_20241119.log), [pcexhumed_win64_20241119.log](https://github.com/user-attachments/files/17881985/pcexhumed_win64_20241119.log), [rednukem_win64_20241119.log](https://github.com/user-attachments/files/17881986/rednukem_win64_20241119.log)). **There is no message or error anywhere, It simply crashes**.

### This works:

- If instead, I use any of the ports 32-bit versions [latest version](https://github.com/nukeykt/NBlood/releases/tag/r14125) (_win32_20241119: r14125-fcb8c4109, Built Nov 19 2024 05:07:23, GCC 14.2.0, 32-bit_), They just work fine and I can play normally ([nblood_win32_20241119.log](https://github.com/user-attachments/files/17881990/nblood_win32_20241119.log), [pcexhumed_win32_20241119.log](https://github.com/user-attachments/files/17881991/pcexhumed_win32_20241119.log), [rednukem_win32_20241119.log](https://github.com/user-attachments/files/17881992/rednukem_win32_20241119.log)).

### Installation:
- For all the test with the ports, I launch all of them with a custom shortcut indicating a folder with the files (using _-j_) which all are in _D:\Juegos\PORTS\Build\_, with the all the ports folder there (_D:\Juegos\PORTS\Build\NBlood_, _D:\Juegos\PORTS\Build\NBlood_Test_, _D:\Juegos\PORTS\Build\PCExhumed_...)
  - For _NBlood_: Extracted data from _GOG's original DOS Blood_ is in _D:\Juegos\PORTS\Build\_Juegos\Blood_.
  - For _PCExhumed_: Extracted data from _GOG's original DOS Powerslave_ is in _D:\Juegos\PORTS\Build\_Juegos\Exhumed_.
  - For _Rednukem_: I'm using the _GOG's Duke3D Atomic Edition_, which Rednukem detects itself automatically from its GOG installation folder, which is _D:\Juegos\GOG\Duke Nukem 3D_. I added too _D:\Juegos\PORTS\Build\_Juegos\Duke_ with the Duke Nukem 64 data, but I'm not launching that for this test.
- Knowing this, and example of shortcut command line is `D:\Juegos\PORTS\Build\NBlood_Test\nblood.exe -j "D:\Juegos\PORTS\Build\_Juegos\Blood"`.

(I don't think these folder locations matters because I tested them also in the Desktop and they do the same, but I want to give all the info possible and I don't assume anything).

### Bisecting:

- The last version what the normal 64-bit builds work is the latest ones stored in the old website for builds ([https://lerppu.net/wannabethesis/](https://lerppu.net/wannabethesis/)), which are the _20230620-13623_ [nblood](https://lerppu.net/wannabethesis/nblood/20230620-13623/)/[pcexhumed](https://lerppu.net/wannabethesis/pcexhumed/20230620-13623/)/[rednukem](https://lerppu.net/wannabethesis/rednukem/20230620-13623/) (Logs from testing them 
[nblood_win64_20230620.log](https://github.com/user-attachments/files/17882011/nblood_win64_20230620.log), [pcexhumed_win64_20230620.log](https://github.com/user-attachments/files/17882012/pcexhumed_win64_20230620.log), [rednukem_win64_20230620.log](https://github.com/user-attachments/files/17882013/rednukem_win64_20230620.log)).

- The first 64-bit one that I could test that crashes in the same way is the oldest one here in the github releases: [r13657](https://github.com/nukeykt/NBlood/releases/tag/r13657).

I also tested the latest _EDuke32_ ([20240725-10593-19c21b9ab](https://dukeworld.duke4.net/eduke32/synthesis/20240725-10593-19c21b9ab/)), and It has the same issue with the normal version, however, in that case the last _Win64_ build that works is [20221026-10165-a9c797dcb](https://dukeworld.duke4.net/eduke32/synthesis/20221026-10165-a9c797dcb/) (and the first one to not work is the next one [20221225-10166-122aee012](https://dukeworld.duke4.net/eduke32/synthesis/20221225-10166-122aee012/)), but also with the latest _Win64_Debug_ version works fine alongside the _Win32_ version. _VoidSW_ crashes and works in the same way as _EDuke32_. I reported the _EDuke32_ issue there [https://voidpoint.io/terminx/eduke32/-/issues/314](https://voidpoint.io/terminx/eduke32/-/issues/314).

### Specifications:
-  Windows 10 Pro (22H2) x64
-  CPU: AMD Athlon II X3 450 3x3.2 Ghz.
-  Memory: 12 GB RAM.
-  Graphics: GeForce GTX 750.
-  Full specifications (from CPU-Z): [Specifications.txt](https://github.com/user-attachments/files/17882021/Specifications.txt).

## Additional info:

I'm gonna quote this directly from [the _EDuke32_ issue](https://voidpoint.io/terminx/eduke32/-/issues/314), because I think it's important:

> I'm not sure, and maybe the issue is something completely different so don't assume it, please, but a very very similar issue happened to me in this computer with other project: [DOSBox-Staging](https://www.dosbox-staging.org/).
> 
> In that case, updating the files like here, I found [since a few versions](https://github.com/dosbox-staging/dosbox-staging/issues/3669#issuecomment-2145015286) the main ones crash at launch without any error, but, with the daily builds there instead the debug versions here, the "other" version worked just fine.
> 
> In the end, It was that [my CPU lacks SSSE3 instruction set](https://github.com/dosbox-staging/dosbox-staging/issues/3669#issuecomment-2145709795), and because one library (_zlib-ng_) in the those normal builds with are build in a way you need to specify the CPU target before hand, but in the daily builds it does a runtime check instead (It's explained [there](https://github.com/dosbox-staging/dosbox-staging/issues/3669#issuecomment-2148559668), I don't have enough knowledge to understand it fully but I get the concept). They were changing the build method already and that's why the daily builds worked, and now the latest main version also works in my computer.
> 
> The issue here (and there) to me, first, It's there is an error anywhere to look up the issue, and also I don't know where to look the specifications to see If at any moment my computer was outdated for that task. Second, If there is a requirement issue, why the daily (debug version in this case) works, but not the normal one? That adds a problem for testing as one build has issues that the other one not, when ideally should be identical for testing. And third, as I understand my computer is old and some projects can't keep up the back compatibility (I know some that already left it behind) and that's life, there should be some explanation somewhere, of why and what's the last version usable, but also knowing that _EDuke32_ stills does 32 bits builds... It's strange that I did not found any information anywhere (...), so maybe It was an unexpected requirement that only a few people could detect. I don't know If it can be fixed in the normal version or I would need to stick to the debug version until they finally don't work anymore... but at least should be noted to be known.

<hr>

Thanks in advance!

**Comment by CommonLoon102** [comment]
> why the daily (debug version in this case) works, but not the normal one? 

Debug builds have optimizations disabled, including SIMD (e.g. SSSE3).

> That adds a problem for testing as one build has issues that the other one not, when ideally should be identical for testing.

Yes, this is something known and it is normal. The same problem happens for out-of-bounds indexing, because debug builds clearing not used memory and setting it to 0, while in release builds the memory has random-ish data at non-used spaces. This way the debug and release builds will behave differently.

> or I would need to stick to the debug version

Why don't you use the 32 bit version? That is more like for older PCs.

**Comment by Hendricks266** [comment]
> Thanks in advance!

Thanks for your detailed report, here and on EDuke32 upstream! You may want to check the various `-march -msse` etc options in Common.mak to see if changing them gets around the use of SSSE3 instructions. We don't use zlib-ng so that particular detail won't help here but it is possible something else we pull in is getting in the way.

**Comment by LukasThyWalls** [comment]
> > why the daily (debug version in this case) works, but not the normal one?
> 
> Debug builds have optimizations disabled, including SIMD (e.g. SSSE3).
> 
> > That adds a problem for testing as one build has issues that the other one not, when ideally should be identical for testing.
> 
> Yes, this is something known and it is normal. The same problem happens for out-of-bounds indexing, because debug builds clearing not used memory and setting it to 0, while in release builds the memory has random-ish data at non-used spaces. This way the debug and release builds will behave differently.

Thanks for the answer. I understand it a little bit but also is confusing for testing. Although, is more confusing not having an actual error to know what is happening.

> > or I would need to stick to the debug version
> 
> Why don't you use the 32 bit version? That is more like for older PCs.

It's for _older_ PCs than this. It's a 64-bit PC, which has 12 GB of RAM (Theoretically I could put 32 GB, but I think the realistic top is 16 GB) and I could put an RTX If i want (I'm not gonna... It's a bit stupid). The CPU could be upgraded a little bit, and I see it as a cool Win7/10 retro PC for the future, but still today can do mostly everything I want and I use it everyday for normal use.

As I explain above, the reason to report this is because It happens: It crashes. Maybe It's something easy to fix and If it's fixed I would be awesome, maybe not and that's life. But at least should be know because It is in fact a hard requirement somewhere that is not documented anywhere that I have been able to search. I understand It's an old rig and I don't expect big efforts to make it works.

I could use the 32-bit version, but as the scope of this building is to be compatible with a wider range of computers, is strange that an intermediate range are not supported, in the 64-bit variant. And as I experienced on other projects, probably is a library that are set to expect some CPUs instructions, but normally can also be set (during the compiling phase) to not expect them (that's why the 32-bit version works) or also set It to check and adapt in runtime depending what instructions sets are available. But like I said, I didn't expect a fix, I'm only reporting what happens and maybe can be fixed (easily).

The main issue using the 32-bit version is to use with mods, because If the game RAM print grows with that, It could be hitting the max 2GB for apps. I have the mods disabled right now, but I didn't even tried yet.

> > Thanks in advance!
> 
> Thanks for your detailed report, here and on EDuke32 upstream! You may want to check the various `-march -msse` etc options in Common.mak to see if changing them gets around the use of SSSE3 instructions. We don't use zlib-ng so that particular detail won't help here but it is possible something else we pull in is getting in the way.

Thanks! I'm gonna look it up to see If I found something from there.

**Comment by CommonLoon102** [comment]
The 32 bit release binary should give better performance than the 64 bit debug one.

You can try running the 64 bit release binary with `windbg` and see the illegal instruction error, showing the instruction causing it. Looking up that instruction would tell that it is part of SSSE3.

**Comment by LukasThyWalls** [comment]
Thanks for all the tips.

It took me a while because lately a has been a little busy, but I think I figured out what is happening here.

## WHAT

In the end, is nothing about a library, It's because how _EDuke32/NBlood/etc._ are compiled and optimised by the compiler. [Like Hendricks comment says](https://github.com/nukeykt/NBlood/issues/865#issuecomment-2498347140), that part of the [Common.mak](https://github.com/nukeykt/NBlood/blob/master/Common.mak#L557C1-L565C10) makefile is pretty clear:

```
    ifeq ($(findstring x86_64, $(IMPLICIT_ARCH)),x86_64)
        ifeq ($(findstring x86_64h, $(IMPLICIT_ARCH)),x86_64h)
            OPTOPT := -march=haswell -msse4.1 -msse4.2 -mpopcnt -mpclmul -mavx -mrdrnd -mf16c -mfsgsbase -mavx2 -maes -mfma -mbmi -mbmi2
            # -mcrc32 -mmovbe
        else
            OPTOPT := -march=core2
        endif
        OPTOPT += -mmmx -msse -msse2 -msse3 -mssse3 -mfpmath=sse
    endif
```

Any time the compiler do a _x86_64_ build, It is with _-march=core2_ and _-mmmx -msse -msse2 -msse3 **-mssse3** -mfpmath=sse_ instruction sets as default. [The Github Action Builds seems are like this](https://github.com/nukeykt/NBlood/blob/master/.github/workflows/build.yml#L24), and even compiling by default in a Haswell CPU (i7 4712MQ) it uses the _x86_64_ as it is what IMPLICIT_ARCH is in that system too (I suppose the _x68_64h_ you need to put it explicitly to make it work in that way, I don't know), so, all 64 bits builds are targeted to a _Core2_ with _SSSE3_ by default.

I try the builds in a notebook with a _Pentium Dual-Core T4200_, which is pretty similar, or maybe a rebranded, Core2, and the builds works fine there, funny enough, that notebook and that CPU is _older_ than the _Athlon II X3 450_ which is the one of the topic and what I normally use at the moment.

The thing here is, in the research that I could do, _almost all 64 bits CPUs have SSE3_ (It looks like some of the first Inter x64 CPUs for servers haven't), but _not all 64 bits CPUs have SSSE3_. SSSE3 was first made by Intel, and even some 32 bits Pentium 4 have it, but AMD didn't introduced their version until the FX line, so their 64 bits CPUs from the [K8](https://en.wikipedia.org/wiki/AMD_K8) and [K10](https://en.wikipedia.org/wiki/AMD_10h) lines don't have _SSSE3_ (Which they are a few, and the _Athlon II X3 450_ is one of the last K10s).

So, when was this changed? Because It was working before.

## WHEN

I could not check for the NBlood builds (like is said above the last source here [r13657](https://github.com/nukeykt/NBlood/releases/tag/r13657) doesn't work and the make file is like this one, and the last one working is from the old build website (https://lerppu.net/wannabethesis/) (20230620-13623 [nblood](https://lerppu.net/wannabethesis/nblood/20230620-13623/)/[pcexhumed](https://lerppu.net/wannabethesis/pcexhumed/20230620-13623/)/[rednukem](https://lerppu.net/wannabethesis/rednukem/20230620-13623/) and they don't have the source), but with the EDuke32 I could find when the source was changed, and I was not where I pointed out before within the last build that doesn't work ([20221225-10166-122aee012](https://dukeworld.duke4.net/eduke32/synthesis/20221225-10166-122aee012/))).

The code was changed way earlier that year, in the build [20220611-10112](https://dukeworld.duke4.net/eduke32/synthesis/20220611-10112-54177821c/). In the previous one, [20220517-10066](https://dukeworld.duke4.net/eduke32/synthesis/20220517-10066-6ae3c8317/), the optimisations part of the _Common.mak_ is like this:

```
    ifeq ($(findstring x86_64, $(IMPLICIT_ARCH)),x86_64)
        ifeq ($(findstring x86_64h, $(IMPLICIT_ARCH)),x86_64h)
            OPTOPT := -march=haswell -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mpclmul -mavx -mrdrnd -mf16c -mfsgsbase -mavx2 -maes -mfma -mbmi -mbmi2
            # -mcrc32 -mmovbe
        else
            ifeq ($(PLATFORM),DARWIN)
                OPTOPT := -march=core2 -mmmx -msse -msse2 -msse3 -mssse3
            else
                OPTOPT := -march=nocona
            endif
        endif
    endif
```

Which by default (if _x86_64h_ is not explicitly added or the PLATFORM is not detected as DARWIN), the arch is _nocona_, which is a 64 bits MMX, SSE, SSE2, SSE3 ([GCC Options reference](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html)).

At that point, for whatever reason, the DARWIN IF and the _nocona_ part was removed, but the DARWIN options were put as the default, which was what has _-mssse3_.

## THEN

So what? I though about two options:

* Put somewhere in the builds or in the readme file, that the 64 bits Builds require a CPU with SSSE3, because, like i said, not all 64 bits CPUs has that instruction set. In reality, at this year almost _all_ 64 bits CPUs have it, but It's true that SSSE3 is a requirement in the builds as they are targeted to work in a Core2, and _maybe_ can be compiled by yourself and made them work just fine without SSSE3 (like i did).

* Eliminate the requirement of SSSE3 in the builds. I compiled _NBlood/PCExhumed/Rednukem_ eliminating the SSSE3 option and _Rednukem_ at least worked just fine (I didn't do a extensive test, but I beat the first level and that's it). I don't know If It's required for something else or is only an optimisation of the compiler, but If it's only an optimisation, I don't think It's a big step to have an optimisation for any 64 bit CPU which is has at least SSE3, and for a Core2 which has the additional SSSE3. At this point in time, and optimisation should be using SSE4.x or even AVX-whatever (for "high-end" computers) but, If its not needed and the gains are slim, It should be better keep the compatibility wider as it can. Other projects even has two or several versions of the builds with this in mind.

I'm gonna post more or less the same in the [EDuke32 issue](https://voidpoint.io/terminx/eduke32/-/issues/314), which, it seems the origin of all of this.

And as I said above, whatever solution or not, It will be ok. I understand It's an old CPU, and who cares, but I reported because happens, and maybe It's an easy solution, maybe is not required, but at least the issue will be known.

Thanks in advance, and sorry for my big chunk of text 😂
