### ISSUE TITLE
Latest Linux build is broken - Caleb is too short and pitchfork not visible

### ISSUE THREAD

**Issue by billbeans** [nukeykt/NBlood#882]
I just built nblood multiple times on Debian (a new release came out a couple of hours ago) and every time I start up a new game Caleb is super short - I can't even get out of the coffin. I also can't see my pitchfork, or any first person weapons I assume. I still have a binary I built a few months ago and I can play that with no problems.

**Comment by billbeans** [comment]
It would also help a little bit to know which nblood files exactly need to be placed in the game directory. So far I've just been adding nblood (the binary) and nblood.pk3. But I've also tried copying all of my Blood data files into the source tree, and still had the same problem

**Comment by Hendricks266** [comment]
Please see README.md for a list of game data files required. On Linux, you should place them in `~/.config/nblood/`.

**Comment by billbeans** [comment]
Ok, that was my bad. I'm trying to write a script that automatically copies a user's data files over to the nblood directory and compiles the source code. I just put the new binary into the old folder and the game ran. So there's something wrong with my script

**Comment by billbeans** [comment]
ART is not included in the readme

> 2. Copy the following files from Blood 1.21 to NBlood folder:
>    * BLOOD.INI
>    * BLOOD.RFF
>   * BLOOD000.DEM, ..., BLOOD003.DEM (optional)
>   * CP01.MAP, ..., CP09.MAP (optional, Cryptic Passage)
>   * CPART07.AR_ (optional, Cryptic Passage)
>   * CPART15.AR_ (optional, Cryptic Passage)
>   * CPBB01.MAP, ..., CPBB04.MAP (optional, Cryptic Passage)
>   * CPSL.MAP (optional, Cryptic Passage)
>   * CRYPTIC.INI (optional, Cryptic Passage)
>   * CRYPTIC.SMK (optional, Cryptic Passage)
>   * CRYPTIC.WAV (optional, Cryptic Passage)
>   * GUI.RFF
>   * SOUNDS.RFF
>   * SURFACE.DAT
>   * TILES000.ART, ..., TILES017.ART
>   * VOXEL.DAT

**Comment by Hendricks266** [comment]
`TILES000.ART, ..., TILES017.ART`

**Comment by billbeans** [comment]
ok i know what i did. i had TILES.00*.ART when it should have been TILES.0*.ART

**Comment by billbeans** [comment]
This is my installer script so far, if anyone's interested (it works now)

It's kind of redundant because it compiles rednukem and pcexhumed then immediately deletes them. It deletes everything except for nblood and nblood.pk3, which is why I asked if those are the only required files.

```
#!/bin/bash

# Gets distro name for dependencies install later
distro_name=$(uname -n)

# Required dependencies for compiling NBlood with APT
dependencies_debian () {
    sudo apt-get install build-essential nasm libgl1-mesa-dev libsdl2-dev flac libflac-dev libvpx-dev libgtk2.0-dev freepats
}

# Required dependencies for compiling NBlood with dnf
dependencies_fedora() {
    sudo dnf groupinstall "Development Tools"
    sudo dnf install g++ nasm mesa-libGL-devel SDL2-devel alsa-lib-devel libvpx-devel gtk2-devel flac flac-devel
    echo "Freepats is not packaged in Fedora, you must download and install it by yourself if desired. See also the timidity-patch-freepats package on others RPM based distros"
}

# Gets location of game files
read -p 'Please enter the location of or drag the directory containing Blood 1.21 data files into the terminal window:' blood_files

# Copies all required files from Blood install to current directory
find $blood_files -type f \( -iname blood.ini -o -iname blood.rff -o -iname blood00*.dem -o -iname cp0*.map -o -iname cpart07.ar_ -o -iname cpart15.ar_ -o -iname cpbb0*.map -o -iname cpsl.map -o -iname cryptic.ini -o -iname cryptic.smk -o -iname cryptic.wav -o -iname gui.rff -o -iname sounds.rff -o -iname surface.dat -o -iname tiles0*.art -o -iname voxel.dat \) -print0 | xargs -0 cp -n -t .

# Creates a directory as a sandbox environment to run commands
mkdir temp
cd temp

# Grabs the latest release of NBlood from Github and extracts the tarball
wget $(curl -s https://api.github.com/repos/nukeykt/NBlood/releases/latest | grep -o -E 'https?://[^,]+' | tr '"' '\n' | grep tarball)
tar -xzvf *

# Enters the extracted directory and attempts to install dependencies based on the user's distro
cd nuke*

    if [ $distro_name = debian -o $distro_name = ubuntu ];
    then
        dependencies_debian
    fi
    
    if [ $distro_name = fedora ];
    then
	dependencies_fedora
    fi

# Attempts to build the NBlood binary and pk3 file. If successful, the files are moved back into the main directory with the data files    
make && mv nblood* ../..
cd ../..

# The source tree and tarball are deleted
rm -rf temp    

echo "Finished. Type './nblood' to play the game."
echo " "
echo "Optionally, if you want to use CD audio tracks instead of MIDI, provide FLAC/OGG recordings in following format: bloodXX.flac/ogg, where XX is track number. Make sure to enable Redbook audio option in sound menu."
echo " "
echo "Optionally, if you want cutscenes and you have the original CD, copy the 'movie' folder into NBlood's folder (the folder itself too)."
echo " "
echo "To play Cryptic Passage, launch with the '-ini CRYPTIC.INI' parameter"

exit
```
